//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AbstractMusicController : NSObject
{
}

- (id)appName;
- (BOOL)applicationInstalled;
- (BOOL)applicationIsRunning;
- (BOOL)applicationWithNameExists:(id)arg1;
- (id)bundleIdentiferForAppWithName:(id)arg1;
- (id)bundleIdentifier;
- (id)currentApplication;
- (BOOL)isRunningAndPlaying;
- (BOOL)pauseIfPlaying;
- (BOOL)playIfRunningAndNotPlaying;
- (void)tellCurrentAppToExecuteTerminalCommand:(id)arg1;
- (int)type;

@end

