//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ActivityViewModelFactory : NSObject
{
}

+ (id)dayModelsForList:(id)arg1;
+ (id)dayViewModelForKey:(id)arg1 date:(id)arg2 inDictionary:(id)arg3;
+ (id)dictionaryWithStartDate:(id)arg1 endDate:(id)arg2;
+ (void)insert:(id)arg1 onDate:(id)arg2 startDate:(id)arg3 endDate:(id)arg4 dict:(id)arg5;
+ (id)modelForStartDate:(id)arg1 endDate:(id)arg2;

@end

