//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSMutableArray;

@interface ActivityDayViewModel : NSObject
{
    NSDate *_date;
    NSMutableArray *_sessionArray;
    long long _totalSecondsLoggedIn;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
- (id)init;
@property(retain, nonatomic) NSMutableArray *sessionArray; // @synthesize sessionArray=_sessionArray;
@property(nonatomic) long long totalSecondsLoggedIn; // @synthesize totalSecondsLoggedIn=_totalSecondsLoggedIn;

@end

