//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLWindowController.h"

#import "CNGridViewDataSource.h"
#import "CNGridViewDelegate.h"

@class CNGridView, CNGridViewItemLayout, NSMutableDictionary, NSString;

@interface ActivityVizualizationController : NLWindowController <CNGridViewDataSource, CNGridViewDelegate>
{
    CNGridView *_gridView;
    CNGridViewItemLayout *_defaultLayout;
    CNGridViewItemLayout *_hoverLayout;
    CNGridViewItemLayout *_selectionLayout;
    NSMutableDictionary *_listOfDayViewModels;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CNGridViewItemLayout *defaultLayout; // @synthesize defaultLayout=_defaultLayout;
@property(retain, nonatomic) CNGridView *gridView; // @synthesize gridView=_gridView;
- (void)gridView:(id)arg1 didActivateContextMenuWithIndexes:(id)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didClickItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didDeselectItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didDoubleClickItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (id)gridView:(id)arg1 itemAtIndex:(long long)arg2 inSection:(long long)arg3;
- (unsigned long long)gridView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)gridViewDidFinishReloadingVisibleItems:(id)arg1;
- (void)hideGrid:(BOOL)arg1;
@property(retain, nonatomic) CNGridViewItemLayout *hoverLayout; // @synthesize hoverLayout=_hoverLayout;
@property(retain, nonatomic) NSMutableDictionary *listOfDayViewModels; // @synthesize listOfDayViewModels=_listOfDayViewModels;
- (void)loadLayout;
- (void)reloadData;
- (void)reloadDatasourceAndView;
- (void)reloadDatsourceWithCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) CNGridViewItemLayout *selectionLayout; // @synthesize selectionLayout=_selectionLayout;
- (void)setupGridViewLayout;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

