//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMenuItemManager.h"

@interface AdvancedMenuManager : BaseMenuItemManager
{
}

- (id)authAutomatically;
- (id)authDisabled;
- (id)authKnock;
- (id)authPass;
- (id)authRequestSections;
- (id)authYesNo;
- (id)createViewModel;
- (id)iconOnSleepScreen;
- (id)lockScreenOverlaySection;
- (id)lockSection;
- (id)loginNotification;
- (id)macNotificationsSection;
- (id)shourtcutSection;
- (id)startOnStartup;
- (id)startupOptionsSection;

@end

