//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMenuItemManager.h"

@interface AllCellsMenuManager : BaseMenuItemManager
{
    BOOL _bluetoothCollapsed;
}

@property(nonatomic) BOOL bluetoothCollapsed; // @synthesize bluetoothCollapsed=_bluetoothCollapsed;
- (id)createViewModel;

@end

