//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSView;

@interface AnimationViewModel : NSObject
{
    BOOL _hasNavbar;
    int _direction;
    NSView *_view;
    CDUnknownBlockType _completion;
}

- (void).cxx_destruct;
@property(copy) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) int direction; // @synthesize direction=_direction;
@property(nonatomic) BOOL hasNavbar; // @synthesize hasNavbar=_hasNavbar;
- (id)initView:(id)arg1 direction:(int)arg2 navbar:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
@property(retain, nonatomic) NSView *view; // @synthesize view=_view;

@end

