//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ANSActivity : NSObject
{
    id <NSObject> _processInfoToken;
    unsigned long long _options;
    NSString *_reason;
    unsigned long long _backgroundTaskIdentifier;
}

+ (id)beginActivity:(id)arg1 withOptions:(unsigned long long)arg2;
+ (id)beginActivity:(id)arg1 withOptions:(unsigned long long)arg2 expirationHandler:(CDUnknownBlockType)arg3;
+ (id)beginActivityIfAvailable:(id)arg1 options:(unsigned long long)arg2;
+ (void)performActivity:(id)arg1 options:(unsigned long long)arg2 withBlock:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(nonatomic) unsigned long long backgroundTaskIdentifier; // @synthesize backgroundTaskIdentifier=_backgroundTaskIdentifier;
- (unsigned long long)beginBackgroundTaskWithName:(id)arg1 expirationHandler:(CDUnknownBlockType)arg2;
- (void)dealloc;
- (void)end;
- (void)endAndInvalidateBackgroundTask;
- (void)endAndInvalidateInternalActivity;
- (id)initWithProcessToken:(id)arg1 options:(unsigned long long)arg2 reason:(id)arg3 backgroundTaskIdentifier:(unsigned long long)arg4;
@property(readonly, nonatomic) unsigned long long options; // @synthesize options=_options;
@property(retain, nonatomic) id <NSObject> processInfoToken; // @synthesize processInfoToken=_processInfoToken;
@property(readonly, nonatomic) NSString *reason; // @synthesize reason=_reason;
- (id)sharedAppInstance;
- (BOOL)supportsBackgroundTasks;

@end

