//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ANSBackoffTimer : NSObject
{
    unsigned long long _retryCount;
    double _initialValue;
    double _jitterCoefficient;
}

+ (BOOL)jitterCoefficientIsValid:(double)arg1;
- (double)computeDelayForInitialValue:(double)arg1 retryCount:(unsigned long long)arg2;
- (void)executeBlockAfterNextInterval:(CDUnknownBlockType)arg1;
- (double)generateRandomJitter;
- (id)init;
- (id)initWithInitialValue:(double)arg1;
- (id)initWithInitialValue:(double)arg1 jitterCoefficient:(double)arg2;
@property(nonatomic) double initialValue; // @synthesize initialValue=_initialValue;
@property(readonly, nonatomic) double jitterCoefficient; // @synthesize jitterCoefficient=_jitterCoefficient;
- (double)randomDoubleWithMin:(double)arg1 max:(double)arg2;
@property(nonatomic) unsigned long long retryCount; // @synthesize retryCount=_retryCount;

@end

