//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ANSEvent.h"

@class NSDictionary, NSString;

@interface ANSCustomEvent : ANSEvent
{
    NSString *_customEventName;
    NSDictionary *_customAttributes;
}

- (void).cxx_destruct;
- (id)attributesDictionary;
@property(retain, nonatomic) NSDictionary *customAttributes; // @synthesize customAttributes=_customAttributes;
@property(readonly, nonatomic) NSString *customEventName; // @synthesize customEventName=_customEventName;
- (id)description;
- (id)dictionaryRepresentation;
- (id)initWithCustomEventName:(id)arg1 customAttributes:(id)arg2;
- (id)name;

@end

