//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSApplicationDelegate.h"
#import "NSUserNotificationCenterDelegate.h"
#import "StateMachineDelegate.h"

@class NSString, StateMachine;

@interface AppDelegate : NSObject <NSApplicationDelegate, StateMachineDelegate, NSUserNotificationCenterDelegate>
{
    StateMachine *stateMachine;
    id _activity;
}

- (void).cxx_destruct;
@property(retain, nonatomic) id activity; // @synthesize activity=_activity;
- (void)applicationDidFinishLaunching:(id)arg1;
- (BOOL)applicationShouldHandleReopen:(id)arg1 hasVisibleWindows:(BOOL)arg2;
- (unsigned long long)applicationShouldTerminate:(id)arg1;
- (void)applicationWillFinishLaunching:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)applicationWillTerminate:(id)arg1;
- (void)disableAppFromSleeping;
- (void)macWillShutDown;
- (void)registerForNativeNotificationCallbacks;
@property(retain, nonatomic) StateMachine *stateMachine; // @synthesize stateMachine;
- (void)setupThirdPartFrameworks;
- (void)userNotificationCenter:(id)arg1 didActivateNotification:(id)arg2;
- (BOOL)userNotificationCenter:(id)arg1 shouldPresentNotification:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

