//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class NSGradient;

@interface APSwitchKnobLayer : CALayer
{
    NSGradient *ap_gradient;
    BOOL ap_enabled;
    BOOL ap_pressed;
}

- (void).cxx_destruct;
- (void)drawInContext:(struct CGContext *)arg1;
@property(nonatomic) BOOL enabled; // @synthesize enabled=ap_enabled;
- (id)init;
@property(nonatomic, getter=isPressed) BOOL pressed; // @synthesize pressed=ap_pressed;

@end

