//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class NSColor, NSGradient;

@interface APSwitchBackgroundLayer : CALayer
{
    NSGradient *ap_gradient;
    BOOL ap_enabled;
    NSColor *ap_onTintColor;
}

- (void).cxx_destruct;
- (void)drawInContext:(struct CGContext *)arg1;
@property(nonatomic) BOOL enabled; // @synthesize enabled=ap_enabled;
- (id)init;
@property(retain, nonatomic) NSColor *onTintColor; // @synthesize onTintColor=ap_onTintColor;

@end

