//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@protocol AuthConnectionDelegate <NSObject>
- (BOOL)allServicesDiscoveredAndUserAuthenticated;
- (void)authenticationFailed;
- (void)canNotReceiveResponse;
- (void)didAuthenticate;
- (void)didReceiveAuthRequest;
- (void)didReceiveDiconnectReqeust;
- (void)didReceiveMessage:(NSString *)arg1;
- (void)executeSend:(NSString *)arg1 onPrimaryChannel:(BOOL)arg2;
@end

