//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp, MessageEncoderDecoder, NSString, NSTimer;

@interface AuthConnectionManager : NSObject
{
    int _authStatus;
    id <AuthConnectionDelegate> _delegate;
    NSString *_remoteUniqueIdentifier;
    long long _keepAliveInt;
    NSString *_authentificationString;
    NSString *_authToken;
    NSTimer *_keepAliveTimer;
    NSTimer *_keepAliveResponseTimer;
    EventTimestamp *_responseTimestamp;
    MessageEncoderDecoder *_encoder;
}

- (void).cxx_destruct;
- (void)authFailed;
@property(nonatomic) int authStatus; // @synthesize authStatus=_authStatus;
- (void)authSuccess;
@property(retain, nonatomic) NSString *authToken; // @synthesize authToken=_authToken;
@property(retain, nonatomic) NSString *authentificationString; // @synthesize authentificationString=_authentificationString;
- (void)cleanup;
@property(nonatomic) __weak id <AuthConnectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didFullyConnect;
- (void)didReceiveAuthRequestWithAuthIdentifier:(id)arg1;
- (void)didReceiveAuthResponseWithAuthPayload:(id)arg1;
- (void)didReceiveCommand:(id)arg1 withPayload:(id)arg2;
- (void)didReceiveCompleteMessage;
@property(retain, nonatomic) MessageEncoderDecoder *encoder; // @synthesize encoder=_encoder;
- (id)init;
- (void)invalidateKeepAliveResponseTimer;
- (void)invalidateKeepAliveTimer;
@property(nonatomic) long long keepAliveInt; // @synthesize keepAliveInt=_keepAliveInt;
@property(retain, nonatomic) NSTimer *keepAliveResponseTimer; // @synthesize keepAliveResponseTimer=_keepAliveResponseTimer;
@property(retain, nonatomic) NSTimer *keepAliveTimer; // @synthesize keepAliveTimer=_keepAliveTimer;
- (void)noResponseReceived;
- (void)parseReveivedString:(id)arg1;
- (void)preapareForDisconnect;
@property(retain, nonatomic) NSString *remoteUniqueIdentifier; // @synthesize remoteUniqueIdentifier=_remoteUniqueIdentifier;
@property(retain, nonatomic) EventTimestamp *responseTimestamp; // @synthesize responseTimestamp=_responseTimestamp;
- (void)restartKeepAliveTimer;
- (void)sendAuthRequest:(id)arg1 payload:(id)arg2;
- (void)sendCommand:(id)arg1 withString:(id)arg2;
- (void)sendConnectionRequest;
- (void)sendKeepAliveMessage;
- (void)sendShutDownNotification;
- (void)sendString:(id)arg1 onPrimaryChannel:(BOOL)arg2;
- (void)setKeepAliveInterval:(long long)arg1;
- (void)startDisconnect;
- (void)startKeepAliveResponseTimer;
- (void)startKeepAliveTimer;
- (void)stopKeepAliveTimer;

@end

