//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface BaseEntry : NSObject
{
    NSString *_imagePath;
    NSDate *_date;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
@property(retain, nonatomic) NSString *imagePath; // @synthesize imagePath=_imagePath;
- (id)mugShotImage;
- (BOOL)mugShotImageExists;

@end

