//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBCentralManagerDelegate.h"

@class CBCentralManager, EventTimestamp, NSString;

@interface BluetoothLE : NSObject <CBCentralManagerDelegate>
{
    BOOL _bluetoothBLEstateisOn;
    BOOL _bluetoothBLEstateisOnAndReady;
    CBCentralManager *_central;
    long long _lastKnownState;
    EventTimestamp *_bluetoothTurnedOnTimestamp;
}

+ (id)shared;
- (void).cxx_destruct;
- (double)BLEStartupTime;
@property(nonatomic) BOOL bluetoothBLEstateisOn; // @synthesize bluetoothBLEstateisOn=_bluetoothBLEstateisOn;
@property(nonatomic) BOOL bluetoothBLEstateisOnAndReady; // @synthesize bluetoothBLEstateisOnAndReady=_bluetoothBLEstateisOnAndReady;
- (BOOL)bluetoothLEIsOn;
- (BOOL)bluetoothLEIsOnAndReady;
- (BOOL)bluetoothLEIsPoweredOff;
- (BOOL)bluetoothLEIsSupported;
- (long long)bluetoothState;
@property(retain, nonatomic) EventTimestamp *bluetoothTurnedOnTimestamp; // @synthesize bluetoothTurnedOnTimestamp=_bluetoothTurnedOnTimestamp;
@property(retain, nonatomic) CBCentralManager *central; // @synthesize central=_central;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)didUpdateState;
- (id)init;
- (BOOL)isInitializingBLE;
- (BOOL)isSafeToUseBLE;
@property(nonatomic) long long lastKnownState; // @synthesize lastKnownState=_lastKnownState;
- (double)secondsSinceBLETurnedOn;
- (void)updateBLEisOnAndReady;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

