//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor, NSString;

@interface ButtonViewModel : NSObject
{
    BOOL _isLoading;
    BOOL _isEnabled;
    NSString *_title;
    NSString *_iconName;
    NSColor *_color;
    NSColor *_textColor;
    CDUnknownBlockType _action;
}

- (void).cxx_destruct;
@property(copy) CDUnknownBlockType action; // @synthesize action=_action;
@property(retain, nonatomic) NSColor *color; // @synthesize color=_color;
- (void)executeAction;
@property(retain, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
- (id)initWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
@property(nonatomic) BOOL isEnabled; // @synthesize isEnabled=_isEnabled;
@property(nonatomic) BOOL isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) NSColor *textColor; // @synthesize textColor=_textColor;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;

@end

