//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CBUUIDManager : NSObject
{
}

+ (id)genRandStringLength:(int)arg1;
+ (id)generateCBUUIDForType:(int)arg1;
+ (id)generateCBUUIDFromString:(id)arg1;
+ (id)generateStringForType:(int)arg1;
+ (id)generateStringFromCBUUID:(id)arg1;
+ (int)getTypeOfCBUUID:(id)arg1;

@end

