//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasePagerViewController.h"

@interface ClearCacheController : BasePagerViewController
{
    BOOL _ignoreViewUpdates;
    int _cacheMessage;
    id <ClearCacheControllerDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) int cacheMessage; // @synthesize cacheMessage=_cacheMessage;
@property(nonatomic) __weak id <ClearCacheControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)deleteCacheFile;
- (id)descriptionText;
@property(nonatomic) BOOL ignoreViewUpdates; // @synthesize ignoreViewUpdates=_ignoreViewUpdates;
- (id)restartMac;
- (void)showAppropriateStepAnimated:(BOOL)arg1;
- (void)start;
- (id)titleDescriptionText;
- (id)turnBluetoothOff;
- (void)updateViewForBLEUpdate;
- (void)viewDidAppear;
- (void)viewDidLoad;

@end

