//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSButton, NSImageView, NSTextField;

@interface ClipboardView : NSView
{
    NSImageView *_clipboardSeparator;
    NSTextField *_clipboardLabel;
    NSImageView *_clipboardIcon;
    NSButton *_checkBox;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSButton *checkBox; // @synthesize checkBox=_checkBox;
@property(retain, nonatomic) NSImageView *clipboardIcon; // @synthesize clipboardIcon=_clipboardIcon;
@property(retain, nonatomic) NSTextField *clipboardLabel; // @synthesize clipboardLabel=_clipboardLabel;
@property(retain, nonatomic) NSImageView *clipboardSeparator; // @synthesize clipboardSeparator=_clipboardSeparator;

@end

