//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLWindowController.h"

@class NSButton, NSImageView, NSTextField;

@interface ClipboardInfoViewController : NLWindowController
{
    id <ClipboardInfoViewControllerDelegate> _delegate;
    NSTextField *_titleLabel;
    NSTextField *_descriptionLabel;
    NSButton *_sentClipboardButton;
    NSImageView *_shortcutImageVIew;
    NSTextField *_bottomLabel;
    NSTextField *_devicesNotConnectedLabel;
    NSTextField *_sentToMacLabel;
    NSTextField *_getFromMacLabel;
    NSTextField *_clipboardLabel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSTextField *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
- (void)buttonToggled:(id)arg1;
@property(nonatomic) __weak NSTextField *clipboardLabel; // @synthesize clipboardLabel=_clipboardLabel;
@property(nonatomic) __weak id <ClipboardInfoViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(nonatomic) __weak NSTextField *devicesNotConnectedLabel; // @synthesize devicesNotConnectedLabel=_devicesNotConnectedLabel;
@property(nonatomic) __weak NSTextField *getFromMacLabel; // @synthesize getFromMacLabel=_getFromMacLabel;
@property(nonatomic) __weak NSButton *sentClipboardButton; // @synthesize sentClipboardButton=_sentClipboardButton;
@property(nonatomic) __weak NSTextField *sentToMacLabel; // @synthesize sentToMacLabel=_sentToMacLabel;
@property(nonatomic) __weak NSImageView *shortcutImageVIew; // @synthesize shortcutImageVIew=_shortcutImageVIew;
@property(nonatomic) __weak NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setUpViewWhenConnectedToDevice;
- (void)setUpViewWhenNotConnectedToDevice;
- (void)updateStrings;
- (void)updateViewForCurrentState;
- (void)windowDidLoad;

@end

