//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLSCrashReportingController, CLSInternalReport, CLSSettings, NSString;

@protocol CLSCrashReportingControllerDelegate <NSObject>
- (NSString *)APIKeyForCrashReportingController:(CLSCrashReportingController *)arg1;
- (void)detectedCrash;
- (NSString *)installIDForCrashReportingController:(CLSCrashReportingController *)arg1;
- (BOOL)isFirstInstallForCrashReportingController:(CLSCrashReportingController *)arg1;
- (void)reportingController:(CLSCrashReportingController *)arg1 didDetectReportForLastExecution:(CLSInternalReport *)arg2 completionHandler:(void (^)(BOOL))arg3;
- (BOOL)reportingController:(CLSCrashReportingController *)arg1 ensureDeliveryOfUnixSignal:(int)arg2;
- (void)reportingController:(CLSCrashReportingController *)arg1 internalDidDetectReportForLastExecution:(CLSInternalReport *)arg2;
- (BOOL)reportingControllerCanUseBackgroundSessions:(CLSCrashReportingController *)arg1;
- (BOOL)reportingControllerMustInformDelegateOfReports:(CLSCrashReportingController *)arg1;
- (CLSSettings *)settingsForCrashReportingController:(CLSCrashReportingController *)arg1;
- (BOOL)shouldInstallCrashCallback;
@end

