//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class CLSFileManager, CLSInternalReport, NSString;

@interface CLSPackageReportOperation : NSOperation
{
    CLSInternalReport *_report;
    CLSFileManager *_fileManager;
    NSString *_finalPath;
}

- (void).cxx_destruct;
- (BOOL)compressData:(id)arg1 toPath:(id)arg2;
- (id)destinationDirectory;
- (void)encode:(id)arg1 data:(id)arg2 fromPath:(id)arg3;
@property(readonly, nonatomic) CLSFileManager *fileManager; // @synthesize fileManager=_fileManager;
@property(copy, nonatomic) NSString *finalPath; // @synthesize finalPath=_finalPath;
- (id)initWithReport:(id)arg1 fileManager:(id)arg2;
- (void)main;
- (id)packagedPathWithName:(id)arg1;
@property(readonly, nonatomic) CLSInternalReport *report; // @synthesize report=_report;
- (id)reportPath;
- (BOOL)writeBytes:(const void *)arg1 length:(unsigned long long)arg2 toGZFile:(struct gzFile_s *)arg3;

@end

