//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CLSFileManager, CLSNetworkClient, NSOperationQueue;

@interface CLSReportsController : NSObject
{
    id <CLSReportsControllerDelegate> _delegate;
    NSOperationQueue *_operationQueue;
    CLSNetworkClient *_networkClient;
    CLSFileManager *_fileManager;
}

- (void).cxx_destruct;
- (id)APIKey;
- (id)appBundleIdentifier;
- (BOOL)cleanUpSubmittedReportAtPath:(id)arg1;
@property(nonatomic) __weak id <CLSReportsControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) CLSFileManager *fileManager; // @synthesize fileManager=_fileManager;
- (BOOL)fillInRequest:(id)arg1 forMultipartMimeDataAtPath:(id)arg2;
- (id)initWithQueue:(id)arg1 delegate:(id)arg2 client:(id)arg3 fileManager:(id)arg4;
- (id)localeIdentifier;
- (id)mutableRequestWithURL:(id)arg1 timeout:(double)arg2;
@property(readonly, nonatomic) CLSNetworkClient *networkClient; // @synthesize networkClient=_networkClient;
@property(readonly, nonatomic) NSOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
- (BOOL)packagingEnabled;
- (BOOL)prepareAndSubmitReport:(id)arg1 asUrgent:(BOOL)arg2 withProcessing:(BOOL)arg3;
- (id)reportEndpoint;
- (id)reportURL;
- (void)reportUploadAtPath:(id)arg1 completedWithError:(id)arg2;
- (id)settings;
- (BOOL)submissionEnabled;
- (BOOL)submitPackageMultipartMimeAtPath:(id)arg1 synchronously:(BOOL)arg2;
- (BOOL)uploadPackagedReportAtPath:(id)arg1 asUrgent:(BOOL)arg2;

@end

