//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CLSURLSessionDataTask.h"

#import "NSStreamDelegate.h"

@class NSOutputStream, NSString, NSURL;

@interface CLSURLSessionDownloadTask : CLSURLSessionDataTask <NSStreamDelegate>
{
    CDUnknownBlockType _downloadCompletionHandler;
    NSOutputStream *_outputStream;
    NSURL *_targetURL;
}

- (void).cxx_destruct;
- (void)cleanup;
- (void)complete;
- (void)completeForError;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)dealloc;
@property(copy, nonatomic) CDUnknownBlockType downloadCompletionHandler; // @synthesize downloadCompletionHandler=_downloadCompletionHandler;
- (id)init;
- (void)stream:(id)arg1 handleEvent:(unsigned long long)arg2;
- (id)temporaryFileURL;
- (void)writeDataToStream:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

