//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSURL;

@interface CLSUserDefaults : NSObject
{
    BOOL _synchronizeWroteToDisk;
    NSURL *_directoryURL;
    NSURL *_fileURL;
    NSDictionary *_persistedDataDictionary;
    NSMutableDictionary *_dataDictionary;
    struct dispatch_queue_s *_serialDictionaryQueue;
    struct dispatch_queue_s *_synchronizationQueue;
}

+ (id)standardUserDefaults;
- (void).cxx_destruct;
- (BOOL)boolForKey:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy, nonatomic) NSMutableDictionary *dataDictionary; // @synthesize dataDictionary=_dataDictionary;
- (id)dictionaryRepresentation;
@property(readonly, copy, nonatomic) NSURL *directoryURL; // @synthesize directoryURL=_directoryURL;
@property(readonly, copy, nonatomic) NSURL *fileURL; // @synthesize fileURL=_fileURL;
- (id)generateDirectoryURL;
- (id)generateDirectoryURLForBaseURL:(id)arg1 hostAppBundleIdentifier:(id)arg2;
- (id)getEscapedAppBundleIdentifier;
- (id)init;
- (id)loadDefaults;
- (void)migrateFromNSUserDefaults:(id)arg1;
- (id)objectForKey:(id)arg1;
- (id)objectForKeyByMigratingFromNSUserDefaults:(id)arg1;
@property(readonly, copy, nonatomic) NSDictionary *persistedDataDictionary; // @synthesize persistedDataDictionary=_persistedDataDictionary;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
@property(readonly, nonatomic) struct dispatch_queue_s *serialDictionaryQueue; // @synthesize serialDictionaryQueue=_serialDictionaryQueue;
- (void)setBool:(BOOL)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setString:(id)arg1 forKey:(id)arg2;
@property(nonatomic) BOOL synchronizeWroteToDisk; // @synthesize synchronizeWroteToDisk=_synchronizeWroteToDisk;
- (id)stringForKey:(id)arg1;
@property(readonly, nonatomic) struct dispatch_queue_s *synchronizationQueue; // @synthesize synchronizationQueue=_synchronizationQueue;
- (void)synchronize;

@end

