//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CNGridViewItem.h"

@class ActivityDayViewModel;

@interface CNCustomActivityDayViewItem : CNGridViewItem
{
    ActivityDayViewModel *_dayViewModel;
}

- (void).cxx_destruct;
- (double)border;
@property(retain, nonatomic) ActivityDayViewModel *dayViewModel; // @synthesize dayViewModel=_dayViewModel;
- (void)drawRect:(struct CGRect)arg1;

@end

