//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSString;

@interface CNGridViewItemBase : NSView
{
    BOOL _selected;
    BOOL _selectable;
    BOOL _hovered;
    NSString *_reuseIdentifier;
    long long _index;
    id _representedObject;
}

+ (struct CGSize)defaultItemSize;
- (void).cxx_destruct;
- (void)deSelectAll:(id)arg1;
- (void)dealloc;
@property(nonatomic) BOOL hovered; // @synthesize hovered=_hovered;
@property long long index; // @synthesize index=_index;
- (id)init;
- (void)initProperties;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(readonly, nonatomic) BOOL isReuseable;
- (void)prepareForReuse;
@property id representedObject; // @synthesize representedObject=_representedObject;
@property(retain) NSString *reuseIdentifier; // @synthesize reuseIdentifier=_reuseIdentifier;
- (void)selectAll:(id)arg1;
@property(nonatomic) BOOL selectable; // @synthesize selectable=_selectable;
@property(nonatomic) BOOL selected; // @synthesize selected=_selected;

@end

