//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CNGridViewItemBase.h"

@class CNGridViewItemLayout, NSButton, NSImageView;

@interface CNGridViewItem : CNGridViewItemBase
{
    BOOL _useLayout;
    CNGridViewItemLayout *_currentLayout;
    CNGridViewItemLayout *_defaultLayout;
    CNGridViewItemLayout *_hoverLayout;
    CNGridViewItemLayout *_selectionLayout;
    NSImageView *_itemImageView;
    NSButton *_deleteButton;
}

- (void).cxx_destruct;
- (void)addDeleteButton;
- (void)clearHovering;
- (void)clearSelection;
@property(retain) CNGridViewItemLayout *currentLayout; // @synthesize currentLayout=_currentLayout;
@property(retain, nonatomic) CNGridViewItemLayout *defaultLayout; // @synthesize defaultLayout=_defaultLayout;
@property(retain, nonatomic) NSButton *deleteButton; // @synthesize deleteButton=_deleteButton;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) CNGridViewItemLayout *hoverLayout; // @synthesize hoverLayout=_hoverLayout;
- (void)initDefaultContent;
- (void)initProperties;
- (id)initWithLayout:(id)arg1 reuseIdentifier:(id)arg2;
- (BOOL)isFlipped;
@property(retain) NSImageView *itemImageView; // @synthesize itemImageView=_itemImageView;
- (void)removeDeleteButton;
@property(retain, nonatomic) CNGridViewItemLayout *selectionLayout; // @synthesize selectionLayout=_selectionLayout;
- (void)setSelected:(BOOL)arg1;
@property(nonatomic) BOOL useLayout; // @synthesize useLayout=_useLayout;
- (BOOL)wantsDefaultClipping;

@end

