//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSColor, NSDictionary;

@interface CNGridViewItemLayout : NSObject
{
    int _visibleContentMask;
    NSColor *_backgroundColor;
    NSColor *_selectionRingColor;
    double _selectionRingLineWidth;
    unsigned long long _contentInset;
    unsigned long long _itemBorderRadius;
    NSDictionary *_itemTitleTextAttributes;
}

+ (id)defaultLayout;
+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) unsigned long long contentInset; // @synthesize contentInset=_contentInset;
- (id)init;
@property(nonatomic) unsigned long long itemBorderRadius; // @synthesize itemBorderRadius=_itemBorderRadius;
@property(retain) NSDictionary *itemTitleTextAttributes; // @synthesize itemTitleTextAttributes=_itemTitleTextAttributes;
@property(retain, nonatomic) NSColor *selectionRingColor; // @synthesize selectionRingColor=_selectionRingColor;
@property(nonatomic) double selectionRingLineWidth; // @synthesize selectionRingLineWidth=_selectionRingLineWidth;
@property(nonatomic) int visibleContentMask; // @synthesize visibleContentMask=_visibleContentMask;

@end

