//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CNSelectionFrameView, NSColor, NSMenu, NSMutableArray, NSMutableDictionary, NSNotificationCenter, NSString, NSTimer, NSTrackingArea;

@interface CNGridView : NSView
{
    NSMutableDictionary *keyedVisibleItems;
    NSMutableDictionary *reuseableItems;
    NSMutableDictionary *selectedItems;
    NSMutableDictionary *selectedItemsBySelectionFrame;
    CNSelectionFrameView *selectionFrameView;
    NSNotificationCenter *nc;
    NSMutableArray *clickEvents;
    NSTrackingArea *gridViewTrackingArea;
    NSTimer *clickTimer;
    long long lastHoveredIndex;
    long long lastSelectedItemIndex;
    long long numberOfItems;
    struct CGPoint selectionFrameInitialPoint;
    BOOL isInitialCall;
    BOOL mouseHasDragged;
    BOOL abortSelection;
    double _contentInset;
    struct CGPoint _lastUpdatePoint;
    BOOL _scrollElasticity;
    BOOL _allowsSelection;
    BOOL _allowsMultipleSelection;
    BOOL _allowsMultipleSelectionWithDrag;
    BOOL _useSelectionRing;
    BOOL _useHover;
    BOOL _useCenterAlignment;
    id <CNGridViewDelegate> _delegate;
    id <CNGridViewDataSource> _dataSource;
    NSString *_gridViewTitle;
    NSColor *_backgroundColor;
    NSMenu *_itemContextMenu;
    NSView *_headerView;
    struct CGSize _itemSize;
}

- (void).cxx_destruct;
- (void)_refreshInset;
- (BOOL)acceptsFirstResponder;
- (unsigned long long)allOverRowsInGridView;
@property(nonatomic) BOOL allowsMultipleSelection; // @synthesize allowsMultipleSelection=_allowsMultipleSelection;
@property(nonatomic) BOOL allowsMultipleSelectionWithDrag; // @synthesize allowsMultipleSelectionWithDrag=_allowsMultipleSelectionWithDrag;
@property(nonatomic) BOOL allowsSelection; // @synthesize allowsSelection=_allowsSelection;
- (void)arrangeGridViewItemsAnimated:(BOOL)arg1;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void)beginUpdates;
- (unsigned long long)boundIndexForItemAtLocation:(struct CGPoint)arg1;
- (BOOL)canBecomeKeyView;
- (struct CGRect)clippedRect;
- (unsigned long long)columnsInGridView;
@property(nonatomic) id <CNGridViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void)deSelectItem:(id)arg1;
@property(nonatomic) id <CNGridViewDelegate> delegate; // @synthesize delegate=_delegate;
- (id)dequeueReusableItemWithIdentifier:(id)arg1;
- (void)deselectAllItems;
- (void)didFinishUpdatingVisibleItems;
- (void)drawSelectionFrameForMousePointerAtLocation:(struct CGPoint)arg1;
- (void)endUpdates;
- (void)gridView:(id)arg1 didActivateContextMenuWithIndexes:(id)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didClickItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didDeselectItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didDoubleClickItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (id)gridView:(id)arg1 itemAtIndex:(long long)arg2 inSection:(long long)arg3;
- (unsigned long long)gridView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)gridView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (void)gridView:(id)arg1 willDeselectAllItems:(id)arg2;
- (void)gridView:(id)arg1 willDeselectItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 willHoverItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 willSelectItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 willUnhoverItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridViewDidDeselectAllItems:(id)arg1;
@property(retain, nonatomic) NSString *gridViewTitle; // @synthesize gridViewTitle=_gridViewTitle;
- (void)handleClicks:(id)arg1;
- (void)handleDoubleClickForItemAtIndex:(unsigned long long)arg1;
- (void)handleSingleClickForItemAtIndex:(unsigned long long)arg1;
@property(retain, nonatomic) NSView *headerView; // @synthesize headerView=_headerView;
- (void)hoverItemAtIndex:(long long)arg1;
- (unsigned long long)indexForItemAtLocation:(struct CGPoint)arg1;
- (id)indexesForVisibleItems;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)insertItemAtIndex:(long long)arg1 animated:(BOOL)arg2;
- (void)insertItemsAtIndexes:(id)arg1 animated:(BOOL)arg2;
- (BOOL)isFlipped;
@property(nonatomic) NSMenu *itemContextMenu; // @synthesize itemContextMenu=_itemContextMenu;
@property(nonatomic) struct CGSize itemSize; // @synthesize itemSize=_itemSize;
- (void)keyDown:(id)arg1;
- (struct CNItemPoint)locationForItemAtIndex:(unsigned long long)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseMoved:(id)arg1;
- (void)mouseUp:(id)arg1;
- (unsigned long long)numberOfSectionsInGridView:(id)arg1;
- (unsigned long long)numberOfVisibleItems;
- (struct CGRect)rectForItemAtIndex:(unsigned long long)arg1;
- (void)refreshGridViewAnimated:(BOOL)arg1 initialCall:(BOOL)arg2;
- (void)reloadData;
- (void)reloadDataAnimated:(BOOL)arg1;
- (void)reloadItemsAtIndexes:(id)arg1 animated:(BOOL)arg2;
- (void)removeItemsAtIndexes:(id)arg1 animated:(BOOL)arg2;
- (void)rightMouseDown:(id)arg1;
@property(nonatomic) BOOL scrollElasticity; // @synthesize scrollElasticity=_scrollElasticity;
- (id)sectionIndexTitlesForGridView:(id)arg1;
- (void)selectAllItems;
- (void)selectItem:(id)arg1;
- (void)selectItemAtIndex:(unsigned long long)arg1;
- (void)selectItemAtIndex:(unsigned long long)arg1 usingModifierFlags:(unsigned long long)arg2;
- (void)selectItemsCoveredBySelectionFrame:(struct CGRect)arg1 usingModifierFlags:(unsigned long long)arg2;
- (id)selectedIndexes;
- (id)selectedItems;
- (void)setFrame:(struct CGRect)arg1;
- (void)setTransparentBackground;
@property(nonatomic) BOOL useCenterAlignment; // @synthesize useCenterAlignment=_useCenterAlignment;
@property(nonatomic) BOOL useHover; // @synthesize useHover=_useHover;
@property(nonatomic) BOOL useSelectionRing; // @synthesize useSelectionRing=_useSelectionRing;
- (void)setupDefaults;
- (BOOL)shouldUpdateScrollViewItems;
- (void)unHoverItemAtIndex:(long long)arg1;
- (void)updateReuseableItems;
- (void)updateTrackingAreas;
- (void)updateVisibleItems;
- (void)updateVisibleRect;
- (id)visibleIndexes;
- (struct _NSRange)visibleItemRange;
- (struct _NSRange)visibleItemRangeForHorizontalScrolling;
- (struct _NSRange)visibleItemRangeForVerticalScrolling;
- (unsigned long long)visibleRowsInGridView;

@end

