//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearLockListViewCell.h"

#import "NearLockListViewCellProtocol.h"

@class NSString, NSView;

@interface CollapseCell : NearLockListViewCell <NearLockListViewCellProtocol>
{
    NSView *_customBackgroundView;
    NSView *_customIcon;
    NSView *_bottomSeparator;
}

+ (double)cellHeight;
+ (double)cellHeightForViewModel:(id)arg1;
+ (id)nibName;
- (void).cxx_destruct;
@property(retain, nonatomic) NSView *bottomSeparator; // @synthesize bottomSeparator=_bottomSeparator;
- (void)buttonToggled:(id)arg1;
- (id)castViewModel;
@property(retain, nonatomic) NSView *customBackgroundView; // @synthesize customBackgroundView=_customBackgroundView;
@property(retain, nonatomic) NSView *customIcon; // @synthesize customIcon=_customIcon;
- (void)toggleCollapseExpand:(id)arg1;
- (void)updateCellForCellViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

