//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor;

@interface ColorGradientView : NSView
{
    NSColor *startingColor;
    NSColor *endingColor;
    int angle;
}

- (void).cxx_destruct;
@property int angle; // @synthesize angle;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) NSColor *endingColor; // @synthesize endingColor;
- (id)initWithFrame:(struct CGRect)arg1;
@property(retain, nonatomic) NSColor *startingColor; // @synthesize startingColor;

@end

