//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CommandLine : NSObject
{
}

+ (BOOL)bluetoothCacheFileExists;
+ (long long)bluetoothCacheFileSize;
+ (void)deleteBluetoothPlistCacheFileWithCompletion:(CDUnknownBlockType)arg1;
+ (void)deleteBluetoothPlistCacheFileWithSudoPass:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (void)deleteFile:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
+ (void)deleteFile:(id)arg1 withSudoPass:(id)arg2 withCompletion:(CDUnknownBlockType)arg3;
+ (void)disableAppNap;
+ (void)disableMacSleep;
+ (void)enableMacSleep;
+ (long long)fileSize:(id)arg1;
+ (long long)fileSizeForFile:(id)arg1;
+ (BOOL)ifLidIsClosed;
+ (void)lockMacScreen;
+ (void)pushSilentNotificationToDeviceWithPushId:(id)arg1;
+ (void)pushSilentNotificationToDeviceWithPushId:(id)arg1 request:(id)arg2 deviceId:(id)arg3;
+ (void)putComputerToSleep;
+ (void)restartMac;
+ (id)screenSaverAppPath;
+ (void)sendPushNotificationWithContent:(id)arg1 pushId:(id)arg2;
+ (void)showScreensaver;
+ (void)simulatePressReturn;

@end

