//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Common : NSObject
{
}

+ (id)GetUUID;
+ (id)defaultLanguage;
+ (id)getAppVersion;
+ (int)getDefaultMetricSystem;
+ (id)getNextDataFromData:(id)arg1;
+ (BOOL)hasData:(id)arg1;
+ (BOOL)isFirstEverLaunch;
+ (BOOL)isFirstLaunchOfNewVersion;
+ (id)randomStringWithLength:(int)arg1;
+ (id)readData:(id)arg1 withRange:(id)arg2;
+ (BOOL)send:(id)arg1;
+ (id)uniqueAppIdentifier;
+ (id)uniquePushIdentifier;
+ (id)versionText;

@end

