//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class Device, DeviceUser, NSImageView, NSTextField;

@interface ConfigureViewController : BaseViewController
{
    Device *_device;
    DeviceUser *_deviceUser;
    NSTextField *_textLabel;
    NSTextField *_timeTextField;
    NSTextField *_smallTextLabel;
    NSTextField *_deviceNameLabel;
    NSTextField *_inputLoginInformationLabel;
    NSTextField *_userNameTextField;
    NSTextField *_passwordTextField;
    NSTextField *_connectTextField;
    NSTextField *_cancelTextField;
    NSImageView *_frameImageView;
}

- (void).cxx_destruct;
- (void)backToggled:(id)arg1;
@property(retain, nonatomic) NSTextField *cancelTextField; // @synthesize cancelTextField=_cancelTextField;
@property(retain, nonatomic) NSTextField *connectTextField; // @synthesize connectTextField=_connectTextField;
@property(retain, nonatomic) Device *device; // @synthesize device=_device;
@property(retain, nonatomic) NSTextField *deviceNameLabel; // @synthesize deviceNameLabel=_deviceNameLabel;
@property(retain, nonatomic) DeviceUser *deviceUser; // @synthesize deviceUser=_deviceUser;
@property(retain, nonatomic) NSImageView *frameImageView; // @synthesize frameImageView=_frameImageView;
@property(retain, nonatomic) NSTextField *inputLoginInformationLabel; // @synthesize inputLoginInformationLabel=_inputLoginInformationLabel;
- (void)loadView;
@property(retain, nonatomic) NSTextField *passwordTextField; // @synthesize passwordTextField=_passwordTextField;
@property(retain, nonatomic) NSTextField *smallTextLabel; // @synthesize smallTextLabel=_smallTextLabel;
@property(retain, nonatomic) NSTextField *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) NSTextField *timeTextField; // @synthesize timeTextField=_timeTextField;
@property(retain, nonatomic) NSTextField *userNameTextField; // @synthesize userNameTextField=_userNameTextField;
- (void)updateStrings;
- (void)updateView;

@end

