//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface ConfirmationRequestHandler : NSObject
{
    BOOL _sendLoginRequestNextTimeDeviceConnects;
    BOOL _sendRSSILoginRequestWhenEnteringRadius;
    EventTimestamp *_confirmationReqeustSentTimestamp;
}

- (void).cxx_destruct;
@property(retain, nonatomic) EventTimestamp *confirmationReqeustSentTimestamp; // @synthesize confirmationReqeustSentTimestamp=_confirmationReqeustSentTimestamp;
- (void)didExitProximityUnlockRadius;
- (void)didHidePasswordFieldOnScreen;
- (void)didSendPasswordAppearedRequest;
- (void)didSendRSSILoginRequest;
- (id)init;
- (BOOL)prioritzePasswordConfirmationOverRSSIAfterLockShown;
@property(nonatomic) BOOL sendLoginRequestNextTimeDeviceConnects; // @synthesize sendLoginRequestNextTimeDeviceConnects=_sendLoginRequestNextTimeDeviceConnects;
@property(nonatomic) BOOL sendRSSILoginRequestWhenEnteringRadius; // @synthesize sendRSSILoginRequestWhenEnteringRadius=_sendRSSILoginRequestWhenEnteringRadius;
- (BOOL)shouldSendSilenPasswordConfirmationForMobileDevice:(id)arg1;
- (BOOL)shouldSendSilentRSSIConfirmationReqeustForMobileDevice:(id)arg1;
- (BOOL)shouldSendUnlockReqeustWhenPasswordAppearedForMobileDevice:(id)arg1;
- (BOOL)shouldTemporaryDisableNearLockAfterLoginForMobileDevice:(id)arg1;
- (BOOL)shouldTryToFirstLoginWithRSSIAfterPasswordShownOnScreen;
- (void)userDidLogin;
- (void)userDidLogout;

@end

