//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface ConfigFile : NSObject
{
    NSString *_iOSVersion;
    NSString *_macVersion;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *iOSVersion; // @synthesize iOSVersion=_iOSVersion;
@property(retain, nonatomic) NSString *macVersion; // @synthesize macVersion=_macVersion;

@end

