//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface ConnectionData : NSObject
{
    NSMutableDictionary *_dictOfData;
}

- (void).cxx_destruct;
- (id)dictFromReceivedString:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *dictOfData; // @synthesize dictOfData=_dictOfData;
- (id)generateDictionaryWithReceivedDataforCharacteristic:(id)arg1 forPeripheral:(id)arg2;
- (id)generateStringWithReceivedDataforCharacteristic:(id)arg1 forPeripheral:(id)arg2;
- (id)getDataForPeripheral:(id)arg1;
- (void)resetData;

@end

