//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface ConnectionFilter : NSObject
{
    EventTimestamp *_RSSITimestamp;
}

+ (BOOL)connectionIdIsNewPairingRequestConnection:(id)arg1;
+ (BOOL)connectionIsNewPairingRequestConnection:(id)arg1;
+ (BOOL)connectionIsTrackingDevice:(id)arg1;
+ (BOOL)connectionIsTrackingDeviceWithId:(id)arg1;
+ (BOOL)isConnectedToTrackingConnection:(id)arg1;
+ (BOOL)scannerShouldIgnoreAllDiscoveredConnections:(id)arg1;
+ (BOOL)scannerShouldProceedWithConnectingTo:(id)arg1;
+ (BOOL)shouldConnectToConnection:(id)arg1;
+ (BOOL)shouldConnectToDeviceWithId:(id)arg1;
+ (BOOL)shouldConnectToMobileDevice:(id)arg1;
+ (BOOL)shouldTemporaryStopScanningForCurrentTrackingConnection:(id)arg1;
- (void).cxx_destruct;
@property(retain, nonatomic) EventTimestamp *RSSITimestamp; // @synthesize RSSITimestamp=_RSSITimestamp;
- (void)didUpdateRSSI;
- (id)init;
- (BOOL)shouldUpdateRSSIForConnection:(id)arg1;

@end

