//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ConnectionController, Message, MobileDevice, NSNumber;

@protocol ConnectionControllerDelegate <NSObject>
- (void)connectionController:(ConnectionController *)arg1 didConnectToMobileDevice:(MobileDevice *)arg2;
- (void)connectionController:(ConnectionController *)arg1 didDisconnectFromMobileDevice:(MobileDevice *)arg2;
- (void)connectionController:(ConnectionController *)arg1 didExperienceError:(int)arg2;
- (void)connectionController:(ConnectionController *)arg1 didReceiveMessage:(Message *)arg2 fromMobileDevice:(MobileDevice *)arg3;
- (void)connectionController:(ConnectionController *)arg1 didUpdateRSSI:(NSNumber *)arg2 forMobileDevice:(MobileDevice *)arg3;
@end

