//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSNumber, NSString;

@interface ConnectionInfo : NSObject <NSCoding>
{
    NSString *_serviceId;
    NSNumber *_isConnected;
}

- (void).cxx_destruct;
- (id)copyCustom;
- (void)decodeWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSNumber *isConnected; // @synthesize isConnected=_isConnected;
@property(retain, nonatomic) NSString *serviceId; // @synthesize serviceId=_serviceId;

@end

