//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearLockListViewCell.h"

#import "NearLockListViewCellProtocol.h"

@class NSImageView, NSString, NSTextField;

@interface ConnectedDevicesCell : NearLockListViewCell <NearLockListViewCellProtocol>
{
    NSTextField *_macName;
    NSTextField *_iPhoneName;
    NSImageView *_connectedImage;
}

+ (double)cellHeight;
+ (id)nibName;
- (void).cxx_destruct;
- (id)castViewModel;
@property(retain, nonatomic) NSImageView *connectedImage; // @synthesize connectedImage=_connectedImage;
@property(retain, nonatomic) NSTextField *iPhoneName; // @synthesize iPhoneName=_iPhoneName;
@property(retain, nonatomic) NSTextField *macName; // @synthesize macName=_macName;
- (void)updateCellForCellViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

