//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSImage, NSString;

@interface CustomImageRadioButton : NSButton
{
    BOOL _isSelected;
    BOOL _updateImagesOnNextRender;
    NSImage *_imageForSelectedState;
    NSImage *_imageForDeselectedState;
    NSString *_selectedImageName;
    NSString *_unselectedImageName;
}

- (void).cxx_destruct;
- (void)createImageIfNeeded;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) NSImage *imageForDeselectedState; // @synthesize imageForDeselectedState=_imageForDeselectedState;
@property(retain, nonatomic) NSImage *imageForSelectedState; // @synthesize imageForSelectedState=_imageForSelectedState;
@property(nonatomic) BOOL isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) NSString *selectedImageName; // @synthesize selectedImageName=_selectedImageName;
- (void)setSelectedImageName:(id)arg1 unselectedImageName:(id)arg2;
@property(retain, nonatomic) NSString *unselectedImageName; // @synthesize unselectedImageName=_unselectedImageName;
@property(nonatomic) BOOL updateImagesOnNextRender; // @synthesize updateImagesOnNextRender=_updateImagesOnNextRender;
- (void)updateView;
- (void)updateViewForSelectedState;

@end

