//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearLockListViewCell.h"

#import "NearLockListViewCellProtocol.h"

@class NSButton, NSImageView, NSString;

@interface CustomCheckBoxCell : NearLockListViewCell <NearLockListViewCellProtocol>
{
    NSImageView *_imageView;
    NSButton *_readMoreButton;
    NSButton *_nativeCheckBox;
}

+ (double)cellHeight;
+ (id)nibName;
- (void)checkBoxToggled:(id)arg1;
- (void)didSelectCell;
- (void)didUpdateSelection;
@property(nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
@property(nonatomic) NSButton *nativeCheckBox; // @synthesize nativeCheckBox=_nativeCheckBox;
@property(nonatomic) NSButton *readMoreButton; // @synthesize readMoreButton=_readMoreButton;
- (void)readMoreToggled:(id)arg1;
- (void)updateCellForCellViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

