//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface CustomAnimationHelper : NSObject
{
    EventTimestamp *_knockTimestamp;
}

- (void).cxx_destruct;
- (void)finishKnockAnimation:(CDUnknownBlockType)arg1;
- (id)init;
- (void)knockDetected;
@property(retain, nonatomic) EventTimestamp *knockTimestamp; // @synthesize knockTimestamp=_knockTimestamp;

@end

