//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSliderCell.h"

@interface CustomSliderCell : NSSliderCell
{
    struct CGRect _knobRect;
}

- (void)drawBarInside:(struct CGRect)arg1 flipped:(BOOL)arg2;
- (void)drawFocusRingMaskWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (void)drawKnob:(struct CGRect)arg1;
@property(nonatomic) struct CGRect knobRect; // @synthesize knobRect=_knobRect;

@end

