//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol CWEventDelegate

@optional
- (void)bssidDidChangeForWiFiInterfaceWithName:(NSString *)arg1;
- (void)clientConnectionInterrupted;
- (void)clientConnectionInvalidated;
- (void)countryCodeDidChangeForWiFiInterfaceWithName:(NSString *)arg1;
- (void)linkDidChangeForWiFiInterfaceWithName:(NSString *)arg1;
- (void)linkQualityDidChangeForWiFiInterfaceWithName:(NSString *)arg1 rssi:(long long)arg2 transmitRate:(double)arg3;
- (void)modeDidChangeForWiFiInterfaceWithName:(NSString *)arg1;
- (void)powerStateDidChangeForWiFiInterfaceWithName:(NSString *)arg1;
- (void)scanCacheUpdatedForWiFiInterfaceWithName:(NSString *)arg1;
- (void)ssidDidChangeForWiFiInterfaceWithName:(NSString *)arg1;
@end

