//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSValue;

@interface DDHotKey : NSObject
{
    unsigned short _keyCode;
    unsigned int _hotKeyID;
    id _target;
    SEL _action;
    id _object;
    CDUnknownBlockType _task;
    unsigned long long _modifierFlags;
    NSValue *_hotKeyRef;
}

+ (id)hotKeyWithKeyCode:(unsigned short)arg1 modifierFlags:(unsigned long long)arg2 task:(CDUnknownBlockType)arg3;
- (void).cxx_destruct;
@property(nonatomic, setter=_setAction:) SEL action; // @synthesize action=_action;
@property(nonatomic, setter=_setKeyCode:) unsigned short keyCode; // @synthesize keyCode=_keyCode;
@property(nonatomic, setter=_setModifierFlags:) unsigned long long modifierFlags; // @synthesize modifierFlags=_modifierFlags;
@property(retain, nonatomic, setter=_setObject:) id object; // @synthesize object=_object;
@property(nonatomic, setter=_setTarget:) id target; // @synthesize target=_target;
@property(copy, nonatomic, setter=_setTask:) CDUnknownBlockType task; // @synthesize task=_task;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
@property(nonatomic) unsigned int hotKeyID; // @synthesize hotKeyID=_hotKeyID;
@property(retain, nonatomic) NSValue *hotKeyRef; // @synthesize hotKeyRef=_hotKeyRef;
- (void)invokeWithEvent:(id)arg1;
- (BOOL)isEqual:(id)arg1;

@end

