//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface DeviceSpecificConfig : NSObject
{
}

+ (double)BLEIntializationTime;
+ (BOOL)callUpdateRSSITwiceForFasterResponse;
+ (BOOL)hasScreenOverlay;
+ (BOOL)lockOnScreenShownSystemNotificationsWork;
+ (long long)maxClipboardCharLength;
+ (BOOL)needsAccessibilityToUnlockMac;
+ (double)scanIntervalIntense;
+ (double)scanIntervalNormal;
+ (double)scanIntervalVeryIntense;
+ (BOOL)shouldAlwaysUseLongestDisconnectTimerWhenStuck;
+ (BOOL)shouldCancelNotificationsWhileDisconnected;
+ (BOOL)shouldForceTerminateOnUnknownError;
+ (BOOL)shouldForceTerminateOnUnsubscriptions;
+ (BOOL)shouldIgnoreConnectionIfNotConnectebleInAdvertisingData;
+ (BOOL)shouldIgnoreConnectionsWithEmptyAdvertisingServices;
+ (BOOL)shouldIgnoreConnectionsWithWrongManifacturerDefined;
+ (BOOL)shouldIgnoreUnconnectablePeripherals;
+ (BOOL)shouldImmedatellyNotifiyDelegateOfDisconnect;
+ (BOOL)shouldKeepSubscriptionsOnDisconnect;
+ (BOOL)shouldMarkUpdateNotificationStateErrorAsUnsolvable;
+ (BOOL)shouldRetreiveConnectedPeripheralsOnScan;
+ (BOOL)shouldScanForAllServicesForScanRation:(double)arg1;
+ (BOOL)shouldTryToConnectToLastKnownConnection;

@end

