//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface DeviceLocalSettings : NSObject
{
}

+ (id)shared;
@property(nonatomic) int actionOnLogout;
@property(nonatomic) BOOL allowCloserDistances;
@property(nonatomic) BOOL allowLoginOnApproach;
@property(nonatomic) BOOL allowLogoutOnWalkAway;
@property(nonatomic) int authRequest;
@property(nonatomic) BOOL automaticallyUpdate;
@property(retain, nonatomic) NSDate *bluetoothCacheErrorDetected;
@property(retain, nonatomic) NSDate *clearBluetoothCacheDate;
@property(nonatomic) long long clearBluetoothFileSize;
@property(nonatomic) BOOL didMigrateToApplicationData;
@property(nonatomic) BOOL didShowTutorialAtLeastOnce;
@property(nonatomic) BOOL didShowWifiUnlockAtLeastOnce;
@property(nonatomic) BOOL enableNearLockShortCutsLock;
@property(nonatomic) BOOL enableNearLockShortCutsSendClipboard;
@property(nonatomic) BOOL failedToLockMac;
@property(nonatomic) BOOL failedToUnlockMac;
- (id)init;
@property(nonatomic) long long lastActiveTimestamp;
@property(retain, nonatomic) NSDate *lastProgramaticRestartDate;
@property(retain, nonatomic) NSString *lastUsedLanguage;
@property(nonatomic) int lastUsedMetric;
@property(nonatomic) BOOL loginOnApproach;
@property(nonatomic) BOOL logoutOnDisconnect;
@property(nonatomic) int macSleepScreenUnlockConfirmLogin;
- (double)maxRssiValue;
- (double)minRssiValue;
@property(retain, nonatomic) NSDate *mostRecentNearLockRunDate;
@property(nonatomic) BOOL musicPauseOnLogout;
@property(nonatomic) BOOL newFaileLoginAttemptDetected;
- (id)numberForKey:(id)arg1;
- (id)objectForKey:(id)arg1;
@property(nonatomic) long long proximityLockDistance;
@property(nonatomic) BOOL proximityLockIsOn;
@property(retain, nonatomic) NSDate *rescanToggled;
- (void)resetDefaults;
- (void)setDefaultValues;
@property(nonatomic) BOOL showClipboardManagerOnMainScreen;
@property(nonatomic) BOOL showMacControlsOnMainScreen;
@property(nonatomic) BOOL showNearLockIconOnLockedScreen;
@property(nonatomic) BOOL showNearLockProximityOption;
@property(nonatomic) BOOL showWifiUnlockOnMainScreen;
@property(nonatomic) BOOL startNearLockOnApplicationStart;
@property(nonatomic) BOOL takePhotoAfterEachLogin;
@property(nonatomic) BOOL takePhotoOnFailedLogin;
@property(retain, nonatomic) NSDate *tempClearBluetoothCacheDate;
@property(retain, nonatomic) NSDate *userWarnedAboutBluetoothCacheError;
@property(retain, nonatomic) NSDate *veryFirstNearLockRunDate;
@property(nonatomic) BOOL warnUserOnLoginFailed;
- (void)storeNumber:(id)arg1 forKey:(id)arg2;
- (void)storeObject:(id)arg1 forKey:(id)arg2;
- (void)storeString:(id)arg1 forKey:(id)arg2;
- (id)stringForKey:(id)arg1;

@end

