//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface DSLogRecord : NSObject
{
    NSDate *_timeStamp;
    NSString *_functionName;
    NSString *_infoMsg;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *functionName; // @synthesize functionName=_functionName;
- (id)getLogRecordString;
@property(retain, nonatomic) NSString *infoMsg; // @synthesize infoMsg=_infoMsg;
- (id)initWithTimeStamp:(id)arg1 functionName:(id)arg2 info:(id)arg3;
@property(retain, nonatomic) NSDate *timeStamp; // @synthesize timeStamp=_timeStamp;
- (void)setTimeStamp:(id)arg1 functionName:(id)arg2 info:(id)arg3;

@end

