//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EmailComposer : NSObject
{
}

+ (id)getEmailBodySignature;
+ (id)mobileDeviceBody;
+ (id)newLines:(long long)arg1;
+ (id)proVersionBody;
+ (void)sendEmailWithMail:(id)arg1 Address:(id)arg2 Subject:(id)arg3 Body:(id)arg4;
+ (void)sendFeedbackEmail;
+ (void)sendSupportEmail;

@end

