//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface ErrorManager : NSObject
{
    NSMutableDictionary *_dictOfErrorTypes;
}

+ (id)shared;
- (void).cxx_destruct;
- (BOOL)array:(id)arg1 containsString:(id)arg2;
- (void)deleteAllErrors:(id)arg1;
- (void)deleteAllPreviousErrors;
@property(retain, nonatomic) NSMutableDictionary *dictOfErrorTypes; // @synthesize dictOfErrorTypes=_dictOfErrorTypes;
- (void)didExperienceError:(id)arg1;
- (id)getAllErrors:(id)arg1 withinTheLastSecons:(double)arg2;
- (id)getErrorsOfType:(id)arg1;
- (id)getErrorsOfType:(id)arg1 withinTheLastSecons:(double)arg2;
- (id)getErrorsOfTypes:(id)arg1;
- (id)getErrorsOfTypes:(id)arg1 withinTheLastSecons:(double)arg2;
- (long long)totalNumberOfAllErrors;
- (long long)totalNumberOfError:(id)arg1;
- (long long)totalNumberOfError:(id)arg1 withinTheLastSeconds:(double)arg2;
- (long long)totalNumberOfErrors:(id)arg1;
- (long long)totalNumberOfErrors:(id)arg1 withinTheLastSeconds:(double)arg2;

@end

