//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EventTimestamp : NSObject
{
    double _eventTimeSince1970;
}

@property(nonatomic) double eventTimeSince1970; // @synthesize eventTimeSince1970=_eventTimeSince1970;
- (void)eventTriggered;
- (BOOL)isSet;
- (BOOL)moreSecondsElapsedSinceLastTrigger:(double)arg1;
- (void)reset;
- (double)secondsElapsedFromLastEvent;

@end

