//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "InternetNotifierDelegate.h"

@class EventTimestamp, InternetNotifier, NSString, NSTimer;

@interface EventAutomaticTriggerer : NSObject <InternetNotifierDelegate>
{
    BOOL _shouldCheckVersionWhenPossible;
    id <EventAutomaticTriggererDelegate> _delegate;
    long long _checkIntervalInSeconds;
    long long _minimalCheckInterval;
    InternetNotifier *_internetNotifier;
    EventTimestamp *_lastUpdateCheckTimeStamp;
    NSTimer *_updateTimer;
}

- (void).cxx_destruct;
@property(nonatomic) long long checkIntervalInSeconds; // @synthesize checkIntervalInSeconds=_checkIntervalInSeconds;
- (void)checkVersionIfNeeded;
- (void)checkVersionWhenPossible;
@property(nonatomic) __weak id <EventAutomaticTriggererDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didCheckUpdateSuccessfully;
- (void)executeCheckVersion;
- (id)init;
@property(retain, nonatomic) InternetNotifier *internetNotifier; // @synthesize internetNotifier=_internetNotifier;
- (void)internetNotifier:(id)arg1 hasAccesToInternet:(BOOL)arg2;
- (void)invalidateUpdateTimer;
@property(retain, nonatomic) EventTimestamp *lastUpdateCheckTimeStamp; // @synthesize lastUpdateCheckTimeStamp=_lastUpdateCheckTimeStamp;
@property(nonatomic) long long minimalCheckInterval; // @synthesize minimalCheckInterval=_minimalCheckInterval;
- (void)restartUpdateTimer;
@property(nonatomic) BOOL shouldCheckVersionWhenPossible; // @synthesize shouldCheckVersionWhenPossible=_shouldCheckVersionWhenPossible;
@property(retain, nonatomic) NSTimer *updateTimer; // @synthesize updateTimer=_updateTimer;
- (BOOL)shouldCheckVersionForMacCurrentState;
- (void)updateTimerTriggered;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

