//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FABIcon, NSDictionary;

@interface FABAppIconUtility : NSObject
{
    FABIcon *_applicationIcon;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSDictionary *appInfoDictionary;
@property(retain, nonatomic) FABIcon *applicationIcon; // @synthesize applicationIcon=_applicationIcon;
- (id)fetchApplicationIcon;
- (id)mainAppIcon;

@end

