//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSRecursiveLock;

@interface FABAsyncOperation : NSOperation
{
    BOOL _internalExecuting;
    BOOL _internalFinished;
    CDUnknownBlockType _asyncCompletion;
    NSRecursiveLock *_lock;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType asyncCompletion; // @synthesize asyncCompletion=_asyncCompletion;
- (void)changeValueForKey:(id)arg1 inBlock:(CDUnknownBlockType)arg2;
- (BOOL)checkForCancellation;
- (void)finishWithError:(id)arg1;
- (id)init;
- (BOOL)isAsynchronous;
- (BOOL)isConcurrent;
- (BOOL)isExecuting;
- (BOOL)isFinished;
@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
- (void)lock:(CDUnknownBlockType)arg1;
- (void)markDone;
- (void)markStarted;
- (void)start;
- (void)unlockedMarkComplete;
- (void)unlockedMarkFinished;
- (void)unlockedMarkStarted;

@end

