//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FABNetworkResponseHandler : NSObject
{
}

+ (long long)cancelReasonFromURLError:(id)arg1;
+ (void)clientResponseType:(id)arg1 handler:(CDUnknownBlockType)arg2;
+ (BOOL)contentTypeForResponse:(id)arg1 matchesRequest:(id)arg2;
+ (id)errorForCode:(long long)arg1 userInfo:(id)arg2;
+ (id)errorForResponse:(id)arg1 ofType:(long long)arg2 status:(long long)arg3;
+ (void)handleCompletedResponse:(id)arg1 forOriginalRequest:(id)arg2 error:(id)arg3 block:(CDUnknownBlockType)arg4;
+ (id)headerForResponse:(id)arg1 withKey:(id)arg2;
+ (id)requestIdForResponse:(id)arg1;
+ (double)retryValueForResponse:(id)arg1;
+ (BOOL)retryableURLError:(id)arg1;

@end

