//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"
#import "NSURLSessionTaskDelegate.h"

@class FABCertificatePinner, NSString, NSURLSession;

@interface FABNetworkClient : NSObject <NSURLSessionDelegate, NSURLSessionTaskDelegate>
{
    FABCertificatePinner *_certPinner;
    NSURLSession *_session;
}

- (void).cxx_destruct;
- (void)URLSession:(id)arg1 didBecomeInvalidWithError:(id)arg2;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
@property(readonly, nonatomic) FABCertificatePinner *certPinner; // @synthesize certPinner=_certPinner;
- (double)computeDelayForResponse:(id)arg1 withRetryCount:(unsigned long long)arg2;
- (void)dealloc;
- (double)generateRandomJitter;
- (id)init;
- (id)initWithQueue:(id)arg1;
- (id)initWithQueue:(id)arg1 pinnedCertificates:(id)arg2;
- (id)initWithSessionConfiguration:(id)arg1 queue:(id)arg2 pinnedCertificates:(id)arg3;
- (void)invalidateAndCancel;
- (double)randomDoubleWithMin:(double)arg1 max:(double)arg2;
- (void)runAfterRetryValueFromResponse:(id)arg1 attempts:(unsigned long long)arg2 block:(CDUnknownBlockType)arg3;
- (void)runAfterRetryValueFromResponse:(id)arg1 attempts:(unsigned long long)arg2 onQueue:(struct dispatch_queue_s *)arg3 block:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) NSURLSession *session; // @synthesize session=_session;
- (void)startDataTaskWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)startDataTaskWithRequest:(id)arg1 retryLimit:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)startDataTaskWithRequest:(id)arg1 retryLimit:(unsigned long long)arg2 tries:(unsigned long long)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)startDownloadTaskWithRequest:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)startDownloadTaskWithRequest:(id)arg1 retryLimit:(unsigned long long)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)startDownloadTaskWithRequest:(id)arg1 retryLimit:(unsigned long long)arg2 tries:(unsigned long long)arg3 completionHandler:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

