//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FABAsyncOperation.h"

@class NSString;

@interface FABNetworkOperation : FABAsyncOperation
{
    NSString *_APIKey;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *APIKey; // @synthesize APIKey=_APIKey;
- (id)initWithAPIKey:(id)arg1;
- (id)localeIdentifier;
- (id)mutableRequestWithDefaultHTTPHeaderFieldsAndTimeoutForURL:(id)arg1;
- (id)mutableRequestWithDefaultHTTPHeadersForURL:(id)arg1 timeout:(double)arg2;
- (id)userAgentString;

@end

