//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "FABNetworkOperation.h"

@class FABApplicationIdentiferModel, FABNetworkClient, NSDictionary, NSError, NSString;

@interface FABOnboardingOperation : FABNetworkOperation
{
    BOOL _shouldCreate;
    NSError *_error;
    FABApplicationIdentiferModel *_appIdentifierModel;
    NSString *_appEndpoint;
    id <FABOnboardingOperationDelegate> _delegate;
    FABNetworkClient *_networkClient;
    NSDictionary *_kitVersionsByKitBundleIdentifier;
}

- (void).cxx_destruct;
- (id)appBuildVersion;
- (id)appBundleIdentifier;
- (id)appCreateURL;
- (id)appDisplayVersion;
@property(readonly, nonatomic) NSString *appEndpoint; // @synthesize appEndpoint=_appEndpoint;
@property(readonly, nonatomic) FABApplicationIdentiferModel *appIdentifierModel; // @synthesize appIdentifierModel=_appIdentifierModel;
- (id)appInstallSource;
- (id)appName;
- (id)appPlatform;
- (id)appUpdateURL;
- (void)beginAppConfigure;
@property(readonly, nonatomic) id <FABOnboardingOperationDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) NSError *error; // @synthesize error=_error;
- (id)errorForCode:(unsigned long long)arg1 userInfo:(id)arg2;
- (id)initWithAPIKey:(id)arg1;
- (id)initWithDelegate:(id)arg1 shouldCreate:(BOOL)arg2 APIKey:(id)arg3 kitVersionsByKitBundleIdentifier:(id)arg4 appIdentifierModel:(id)arg5 endpointString:(id)arg6 networkClient:(id)arg7;
@property(readonly, copy, nonatomic) NSDictionary *kitVersionsByKitBundleIdentifier; // @synthesize kitVersionsByKitBundleIdentifier=_kitVersionsByKitBundleIdentifier;
- (void)main;
@property(readonly, nonatomic) __weak FABNetworkClient *networkClient; // @synthesize networkClient=_networkClient;
- (id)onboardingRequestForAppCreate:(BOOL)arg1;
@property(nonatomic) BOOL shouldCreate; // @synthesize shouldCreate=_shouldCreate;

@end

