//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FABApplicationIdentiferModel, FABSettingsOnboardingManager, NSArray, NSDictionary, NSString;

@interface Fabric : NSObject
{
    BOOL _debug;
    BOOL _isFirstInstall;
    NSString *_APIKey;
    NSString *_installID;
    NSString *_executionIdentifier;
    NSString *_advertisingToken;
    NSArray *_kitClasses;
    NSDictionary *_fabricConfig;
    FABSettingsOnboardingManager *_settingsAndOnboardingManager;
    FABApplicationIdentiferModel *_applicationIdentifierModel;
    unsigned long long _installationMode;
    NSString *_firebaseGoogleAppId;
}

+ (void)autoInitialize:(id)arg1;
+ (id)configurationDictionaryForKitClass:(Class)arg1;
+ (id)convertToKitClassesIfNeeded:(id)arg1;
+ (void)disableUninitializedKitMessagingForKit:(Class)arg1;
+ (void)initializeKit:(Class)arg1;
+ (BOOL)isAutomaticDataCollectionEnabled;
+ (id)kitClassesByAddingAdMobIfFound:(id)arg1;
+ (id)kitClassesByAddingAnswersIfFound:(id)arg1;
+ (id)kitClassesByAddingDigitsIfFound:(id)arg1;
+ (id)kitClassesByEnsuringAppseeIsFirst:(id)arg1;
+ (void)load;
+ (id)sharedSDK;
+ (void)validateFABKitConformance:(id)arg1;
+ (id)with:(id)arg1;
- (void).cxx_destruct;
@property(copy, nonatomic) NSString *APIKey; // @synthesize APIKey=_APIKey;
@property(copy, nonatomic) NSString *advertisingToken; // @synthesize advertisingToken=_advertisingToken;
@property(readonly, nonatomic) FABApplicationIdentiferModel *applicationIdentifierModel; // @synthesize applicationIdentifierModel=_applicationIdentifierModel;
- (id)configurationDictionaryForKit:(id)arg1;
@property(nonatomic) BOOL debug; // @synthesize debug=_debug;
@property(readonly, copy, nonatomic) NSString *executionIdentifier; // @synthesize executionIdentifier=_executionIdentifier;
@property(copy, nonatomic) NSDictionary *fabricConfig; // @synthesize fabricConfig=_fabricConfig;
@property(copy, nonatomic) NSString *firebaseGoogleAppId; // @synthesize firebaseGoogleAppId=_firebaseGoogleAppId;
- (BOOL)firebaseMode;
- (id)generateInstallationUUID;
- (id)init;
@property(readonly, copy, nonatomic) NSString *installID; // @synthesize installID=_installID;
@property(nonatomic) unsigned long long installationMode; // @synthesize installationMode=_installationMode;
@property(readonly, nonatomic) NSString *instanceIdentifier;
@property(readonly, nonatomic) BOOL isFirstInstall; // @synthesize isFirstInstall=_isFirstInstall;
@property(copy, nonatomic) NSArray *kitClasses; // @synthesize kitClasses=_kitClasses;
- (id)kitVersionsByKitBundleIdentifier;
- (void)onboardAppAndDownloadSettings;
- (id)readInstallationUUID;
@property(retain, nonatomic) FABSettingsOnboardingManager *settingsAndOnboardingManager; // @synthesize settingsAndOnboardingManager=_settingsAndOnboardingManager;
@property(readonly, nonatomic) NSDictionary *settings;
- (BOOL)shouldAutoInitialize:(id)arg1;
- (id)validFabricConfigFromInfoPlist:(id)arg1;

@end

