//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FailedLoginFactory : NSObject
{
}

+ (void)completelyRemoveEntryFromDatabaseIfNeeded:(id)arg1;
+ (void)deleteAllFaileLoginEntries;
+ (void)deleteAllLoginEntryImages;
+ (void)deleteAllSnapshotEntries;
+ (void)deleteBaseEntry:(id)arg1;
- (void)createAndSaveFailedLoginEventTakePhoto:(BOOL)arg1;
- (void)createAndSaveManualSnapshotWithCompletion:(CDUnknownBlockType)arg1;

@end

