//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface FailedLoginHelper : NSObject
{
}

+ (id)allImageFilenames;
+ (id)allPngFilenamesInDirectory:(id)arg1;
+ (id)failedLoginImagePathForImageName:(id)arg1;
+ (id)failedLoginsImagesDirectoryPath;
+ (id)imageNameFordate:(id)arg1;
+ (id)loginsImagesDirectoryPath;
+ (id)newImageFilePathFailedLoginAttemptsForDate:(id)arg1;
+ (id)newImageFilePathLoginForDate:(id)arg1;
+ (id)newImageFilePathManualSnapshotsForDate:(id)arg1;
+ (BOOL)setupDirectoryToSaveFailedLoginImages;
+ (BOOL)setupDirectoryToSaveManualSnapShotImages;
+ (id)snpashotImagesDirectoryPath;
+ (id)stringForDateToMinutes:(id)arg1;
+ (id)stringForDateToSeconds:(id)arg1;

@end

