//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@interface FDCircleLayer : CALayer
{
    double _radius;
}

- (id)initWithRadius:(double)arg1;
@property(nonatomic) double radius; // @synthesize radius=_radius;
- (void)setRadius:(double)arg1 withDuration:(double)arg2;

@end

