//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class LoginLogoutFilterModel, NSButton, NSTextField;

@interface FilterController : NSViewController
{
    id <FilterControllerDelegate> _delegate;
    LoginLogoutFilterModel *_filterModel;
    NSButton *_startButton;
    NSButton *_loginButton;
    NSButton *_logoutButton;
    NSButton *_sessionButton;
    NSButton *_failedLoginButton;
    NSTextField *_filterLabel;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <FilterControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didUpdateFilter;
@property(retain, nonatomic) NSButton *failedLoginButton; // @synthesize failedLoginButton=_failedLoginButton;
- (void)failedLoginFilterToggled:(id)arg1;
@property(retain, nonatomic) NSTextField *filterLabel; // @synthesize filterLabel=_filterLabel;
@property(retain, nonatomic) LoginLogoutFilterModel *filterModel; // @synthesize filterModel=_filterModel;
@property(retain, nonatomic) NSButton *loginButton; // @synthesize loginButton=_loginButton;
- (void)loginFilterToggled:(id)arg1;
@property(retain, nonatomic) NSButton *logoutButton; // @synthesize logoutButton=_logoutButton;
- (void)logoutFilterToggled:(id)arg1;
@property(retain, nonatomic) NSButton *sessionButton; // @synthesize sessionButton=_sessionButton;
- (void)sessionFilterToggled:(id)arg1;
- (void)setSelected:(BOOL)arg1 view:(id)arg2;
@property(retain, nonatomic) NSButton *startButton; // @synthesize startButton=_startButton;
- (void)startFilterToggled:(id)arg1;
- (void)updateViewForFilterModel:(id)arg1;
- (void)viewDidLoad;

@end

