//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSTextField, NSView;

@interface FinishPreviewController : NSViewController
{
    NSTextField *_iPhoneNameTitle;
    NSTextField *_nearLockTitleLabel;
    NSTextField *_nearLockSwitchLabel;
    NSTextField *_distanceLabel;
    NSView *_backgroundView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSTextField *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(retain, nonatomic) NSTextField *iPhoneNameTitle; // @synthesize iPhoneNameTitle=_iPhoneNameTitle;
- (id)init;
@property(retain, nonatomic) NSTextField *nearLockSwitchLabel; // @synthesize nearLockSwitchLabel=_nearLockSwitchLabel;
@property(retain, nonatomic) NSTextField *nearLockTitleLabel; // @synthesize nearLockTitleLabel=_nearLockTitleLabel;
- (void)setUpView;
- (void)updateString;

@end

