//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImageView.h"

@class NSEvent, NSMutableArray, NSTimer;

@interface GifImageView : NSImageView
{
    int _currentImageIndex;
    int _numberOfImages;
    NSMutableArray *arrayOfImages;
    NSTimer *imageSwithchTimer;
    NSEvent *downEvent;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *arrayOfImages; // @synthesize arrayOfImages;
- (void)changeImage:(id)arg1;
- (void)changeImageOnMainThread;
@property int currentImageIndex; // @synthesize currentImageIndex=_currentImageIndex;
@property(retain, nonatomic) NSEvent *downEvent; // @synthesize downEvent;
- (int)getNextImageIndex;
@property(retain, nonatomic) NSTimer *imageSwithchTimer; // @synthesize imageSwithchTimer;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadImageView;
- (BOOL)mouseDownCanMoveWindow;
@property int numberOfImages; // @synthesize numberOfImages=_numberOfImages;
- (void)setImageWithName:(id)arg1 forSuffixStartingFrom:(int)arg2 andEndingAt:(int)arg3;
- (void)startAnimating;
- (void)stopAnimating;

@end

