//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface GifImageModel : NSObject
{
    int _currentImageIndex;
    int _curretNumberOfImages;
    NSMutableArray *_arrayOfImages;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableArray *arrayOfImages; // @synthesize arrayOfImages=_arrayOfImages;
@property int currentImageIndex; // @synthesize currentImageIndex=_currentImageIndex;
@property int curretNumberOfImages; // @synthesize curretNumberOfImages=_curretNumberOfImages;
- (id)getNextImage;
- (id)getPreviousImage;
- (int)numberOfImages;
- (void)setImageWithName:(id)arg1 startingAtIndex:(int)arg2 endingAtIndex:(int)arg3;

@end

