//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMenuItemManager.h"

@interface HelpMenuManager : BaseMenuItemManager
{
}

- (id)aboutLink;
- (id)clearBLECache;
- (id)createViewModel;
- (id)debugSection;
- (id)faqLink;
- (id)helpSection;
- (id)macWakeUnlockTutorial;
- (id)proximityUnlockTutorial;
- (id)sendEmail;
- (id)translationHelp;
- (id)troubleConnecting;
- (id)troubleInitalConnection;
- (id)tutorialSection;

@end

