//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasePagerViewController.h"

@class InfoViewController;

@interface HelpTutorialController : BasePagerViewController
{
    id <HelpDelegate> _helpDelegate;
    InfoViewController *_firstVC;
    InfoViewController *_secondVC;
    InfoViewController *_thirdVC;
    InfoViewController *_fifthVC;
    InfoViewController *_fourthVC;
    InfoViewController *_sixthVC;
}

- (void).cxx_destruct;
- (void)clearBluetoothCache;
- (id)fifth;
@property(retain, nonatomic) InfoViewController *fifthVC; // @synthesize fifthVC=_fifthVC;
- (id)first;
@property(retain, nonatomic) InfoViewController *firstVC; // @synthesize firstVC=_firstVC;
- (id)fourth;
@property(retain, nonatomic) InfoViewController *fourthVC; // @synthesize fourthVC=_fourthVC;
- (id)generalTitle;
@property(nonatomic) __weak id <HelpDelegate> helpDelegate; // @synthesize helpDelegate=_helpDelegate;
- (id)second;
@property(retain, nonatomic) InfoViewController *secondVC; // @synthesize secondVC=_secondVC;
@property(retain, nonatomic) InfoViewController *sixthVC; // @synthesize sixthVC=_sixthVC;
@property(retain, nonatomic) InfoViewController *thirdVC; // @synthesize thirdVC=_thirdVC;
- (void)start;
- (id)third;
- (id)titleDescriptionText;
- (void)viewDidAppear;
- (void)viewDidDisappear;
- (void)viewDidLoad;

@end

