//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class QTCaptureDecompressedVideoOutput, QTCaptureDeviceInput, QTCaptureSession;

@interface ImageSnap : NSObject
{
    QTCaptureSession *mCaptureSession;
    QTCaptureDeviceInput *mCaptureDeviceInput;
    QTCaptureDecompressedVideoOutput *mCaptureDecompressedVideoOutput;
    struct __CVBuffer *mCurrentImageBuffer;
}

+ (id)ciImageFromNSImage:(id)arg1;
+ (BOOL)cleanupSnap:(id)arg1 andSavePhotoWithInterval:(double)arg2 image:(id)arg3 compression:(double)arg4 path:(id)arg5 completion:(CDUnknownBlockType)arg6;
+ (id)dataFrom:(id)arg1 asType:(id)arg2;
+ (id)dataFromFile:(id)arg1;
+ (id)defaultVideoDevice;
+ (double)delayForWarmup:(id)arg1;
+ (id)deviceNamed:(id)arg1;
+ (id)enhancedImageFromImage:(id)arg1;
+ (BOOL)finishAndSavePhotoWithInterval:(double)arg1 image:(id)arg2 compression:(double)arg3 path:(id)arg4 completion:(CDUnknownBlockType)arg5;
+ (BOOL)hasVideoDevice;
+ (id)imageFromData:(id)arg1;
+ (id)imageFromFile:(id)arg1;
+ (id)nsImageFromCIImage:(id)arg1;
+ (id)oldPhoto:(id)arg1 withBrightness:(float)arg2 saturation:(float)arg3 contrast:(float)arg4;
+ (void)performDelayForWarmup:(id)arg1;
+ (BOOL)saveImage:(id)arg1 toPath:(id)arg2;
+ (id)saveImageFromCameraSessionInterval:(double)arg1 image:(id)arg2 snap:(id)arg3 compresstion:(double)arg4;
+ (BOOL)saveSingleSnapshotFrom:(id)arg1 toFile:(id)arg2;
+ (BOOL)saveSingleSnapshotFrom:(id)arg1 toFile:(id)arg2 withWarmup:(id)arg3;
+ (void)saveSingleSnapshotFrom:(id)arg1 toFile:(id)arg2 withWarmup:(id)arg3 completion:(CDUnknownBlockType)arg4;
+ (BOOL)saveSingleSnapshotFrom:(id)arg1 toFile:(id)arg2 withWarmup:(id)arg3 compression:(double)arg4;
+ (BOOL)saveSingleSnapshotFrom:(id)arg1 toFile:(id)arg2 withWarmup:(id)arg3 withTimelapse:(id)arg4;
+ (BOOL)saveSingleSnapshotFrom:(id)arg1 toFile:(id)arg2 withWarmup:(id)arg3 withTimelapse:(id)arg4 compression:(double)arg5;
+ (void)saveSingleSnapshotFrom:(id)arg1 toFile:(id)arg2 withWarmup:(id)arg3 withTimelapse:(id)arg4 compression:(double)arg5 completion:(CDUnknownBlockType)arg6;
+ (id)videoDevices;
- (void)captureOutput:(id)arg1 didOutputVideoFrame:(struct __CVBuffer *)arg2 withSampleBuffer:(id)arg3 fromConnection:(id)arg4;
- (void)dealloc;
- (id)init;
- (id)snapshot;
- (BOOL)startSession:(id)arg1;
- (void)stopSession;

@end

