//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class LOTAnimationView, NSButton, NSImageView, NSProgressIndicator, NSTextField, NSView;

@interface InfoViewController : BaseViewController
{
    BOOL _rightButtonIsLoading;
    NSImageView *_mainIcon;
    NSImageView *_mainIconSmall;
    NSTextField *_titleTextField;
    NSTextField *_textField;
    NSView *_bottomSeparatorView;
    NSButton *_backButton;
    NSButton *_nextButton;
    NSButton *_button;
    NSButton *_leftbutton;
    NSButton *_rightbutton;
    NSProgressIndicator *_rightbuttonLoader;
    CDUnknownBlockType _mainButtonAction;
    CDUnknownBlockType _leftButtonAction;
    CDUnknownBlockType _rightButtonAction;
    CDUnknownBlockType _backActionHandler;
    CDUnknownBlockType _forwardActionHandler;
    LOTAnimationView *_animation;
}

- (void).cxx_destruct;
- (double)alphaForAction:(CDUnknownBlockType)arg1 isLoading:(BOOL)arg2;
@property(retain, nonatomic) LOTAnimationView *animation; // @synthesize animation=_animation;
@property(copy, nonatomic) CDUnknownBlockType backActionHandler; // @synthesize backActionHandler=_backActionHandler;
@property(retain, nonatomic) NSButton *backButton; // @synthesize backButton=_backButton;
@property(retain, nonatomic) NSView *bottomSeparatorView; // @synthesize bottomSeparatorView=_bottomSeparatorView;
@property(retain, nonatomic) NSButton *button; // @synthesize button=_button;
- (void)buttonToggled:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType forwardActionHandler; // @synthesize forwardActionHandler=_forwardActionHandler;
@property(copy, nonatomic) CDUnknownBlockType leftButtonAction; // @synthesize leftButtonAction=_leftButtonAction;
- (void)leftButtonToggled:(id)arg1;
@property(retain, nonatomic) NSButton *leftbutton; // @synthesize leftbutton=_leftbutton;
@property(copy, nonatomic) CDUnknownBlockType mainButtonAction; // @synthesize mainButtonAction=_mainButtonAction;
@property(retain, nonatomic) NSImageView *mainIcon; // @synthesize mainIcon=_mainIcon;
@property(retain, nonatomic) NSImageView *mainIconSmall; // @synthesize mainIconSmall=_mainIconSmall;
@property(retain, nonatomic) NSButton *nextButton; // @synthesize nextButton=_nextButton;
- (void)nextButtonToggled:(id)arg1;
- (void)playGIF:(id)arg1;
- (void)previousButtonToggled:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType rightButtonAction; // @synthesize rightButtonAction=_rightButtonAction;
@property(nonatomic) BOOL rightButtonIsLoading; // @synthesize rightButtonIsLoading=_rightButtonIsLoading;
- (void)rightButtonToggled:(id)arg1;
@property(retain, nonatomic) NSButton *rightbutton; // @synthesize rightbutton=_rightbutton;
@property(retain, nonatomic) NSProgressIndicator *rightbuttonLoader; // @synthesize rightbuttonLoader=_rightbuttonLoader;
- (void)setBackAction:(CDUnknownBlockType)arg1;
- (void)setButtonTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)setForwardAction:(CDUnknownBlockType)arg1;
- (void)setLeftButtonTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
- (void)setLoading:(BOOL)arg1 loader:(id)arg2 button:(id)arg3;
- (void)setRightButtonLoading:(BOOL)arg1;
- (void)setRightButtonTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
@property(retain, nonatomic) NSTextField *textField; // @synthesize textField=_textField;
@property(retain, nonatomic) NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
- (void)showAnimation:(id)arg1 loop:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (id)titleDescriptionText;
- (void)updateStrings;
- (void)updateView;
- (void)viewDidLoad;

@end

