//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLPageViewControllerExtended.h"

#import "FinishViewControllerDelegate.h"
#import "MacSleepScreenConnectToiPhoneDelegate.h"
#import "TutorialSetUpNearLockDelegate.h"
#import "TutorialWalkAwayDelegate.h"

@class FinishViewController, MacSleepScreenConnectToiPhone, NSString, PageControl, TutorialFinished, TutorialSetUpNearLock, TutorialWalkAway;

@interface InitialTutorialController : NLPageViewControllerExtended <TutorialSetUpNearLockDelegate, TutorialWalkAwayDelegate, MacSleepScreenConnectToiPhoneDelegate, FinishViewControllerDelegate>
{
    BOOL _tutorialIsActive;
    int _tutorialState;
    id <WizzardViewControllerDelegate> _delegate;
    MacSleepScreenConnectToiPhone *_connectController;
    TutorialSetUpNearLock *_tutorialSetup;
    TutorialWalkAway *_tutorialWalkAway;
    TutorialFinished *_tutorialFinished;
    FinishViewController *_finishViewController;
    PageControl *_pageControl;
}

- (void).cxx_destruct;
@property(retain, nonatomic) MacSleepScreenConnectToiPhone *connectController; // @synthesize connectController=_connectController;
@property(nonatomic) __weak id <WizzardViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (BOOL)didShowTutorialAtLeastOnce;
- (void)didupdateBluetoothState;
- (void)endAndCleanupTutorial;
@property(retain, nonatomic) FinishViewController *finishViewController; // @synthesize finishViewController=_finishViewController;
- (void)finishViewController:(id)arg1 didSelectOption:(int)arg2;
- (void)initializePages;
- (void)macSleepScreenConnectToiPhone:(id)arg1 didSelectOption:(int)arg2;
@property(retain, nonatomic) PageControl *pageControl; // @synthesize pageControl=_pageControl;
@property(retain, nonatomic) TutorialFinished *tutorialFinished; // @synthesize tutorialFinished=_tutorialFinished;
@property(nonatomic) BOOL tutorialIsActive; // @synthesize tutorialIsActive=_tutorialIsActive;
@property(retain, nonatomic) TutorialSetUpNearLock *tutorialSetup; // @synthesize tutorialSetup=_tutorialSetup;
@property(nonatomic) int tutorialState; // @synthesize tutorialState=_tutorialState;
- (void)setTutorialState:(int)arg1 animated:(BOOL)arg2;
@property(retain, nonatomic) TutorialWalkAway *tutorialWalkAway; // @synthesize tutorialWalkAway=_tutorialWalkAway;
- (void)showFinishShareScreen;
- (void)showNearLockTutorial;
- (void)showTutorialAfterPairing;
- (void)showTutorialForReason:(int)arg1;
- (void)showTutorialIfNeeded;
- (void)showWeAreDoneScreen;
- (id)titleDescriptionText;
- (void)tutorialSelectOpenMainMenu:(id)arg1;
- (void)tutorialWalkAwayDidSelectFinishTutorial:(id)arg1;
- (void)updateStateForTutorialForMobileDevice:(id)arg1;
- (void)updateTutorialStateAfterConnectionUpdate;
- (void)updateTutorialStateAfterUpdatingTrackingInfo;
- (void)updateTutorialStateForMobileDevice:(id)arg1;
- (void)userDidLoginWithNearLockRSSI;
- (void)userDidLogoutWithNearLockRSSI;
- (void)windowClosed;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

