//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BasePagerViewController.h"

@class InfoViewController;

@interface InitialConnectionTroubleShoot : BasePagerViewController
{
    id <HelpDelegate> _helpDelegate;
    InfoViewController *_downloadAndOpen;
    InfoViewController *_bluetoothIphone;
    InfoViewController *_restartBluetooth;
    InfoViewController *_support;
    InfoViewController *_faq;
}

- (void).cxx_destruct;
@property(retain, nonatomic) InfoViewController *bluetoothIphone; // @synthesize bluetoothIphone=_bluetoothIphone;
- (id)bluetoothOnIphone;
- (id)createDownloadAndOpen;
@property(retain, nonatomic) InfoViewController *downloadAndOpen; // @synthesize downloadAndOpen=_downloadAndOpen;
@property(retain, nonatomic) InfoViewController *faq; // @synthesize faq=_faq;
- (id)generalTitle;
@property(nonatomic) __weak id <HelpDelegate> helpDelegate; // @synthesize helpDelegate=_helpDelegate;
@property(retain, nonatomic) InfoViewController *restartBluetooth; // @synthesize restartBluetooth=_restartBluetooth;
- (id)restartBluetoothOnMac;
@property(retain, nonatomic) InfoViewController *support; // @synthesize support=_support;
- (void)start;
- (id)supportOrClearCache;
- (id)titleDescriptionText;
- (void)viewDidLoad;

@end

