//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface InterNotifications : NSObject
{
    id <InterNotificationsDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <InterNotificationsDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)internalNotification:(id)arg1;
- (void)registerForInternalNotifications;
- (void)registerForNearLockDarvinNotificaions;
- (void)setObjectValue:(id)arg1 forKey:(id)arg2;

@end

