//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Reachability;

@interface InternetNotifier : NSObject
{
    BOOL _hasInet;
    id <InternetNotifierDelegate> _delegate;
    Reachability *_reachability;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <InternetNotifierDelegate> delegate; // @synthesize delegate=_delegate;
- (void)handleNetworkChange:(id)arg1;
@property(nonatomic) BOOL hasInet; // @synthesize hasInet=_hasInet;
@property(retain, nonatomic) Reachability *reachability; // @synthesize reachability=_reachability;
- (void)setUpRechability;

@end

