//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSControl.h"

@class CALayer, CATextLayer, NSColor;

@interface ITSwitch : NSControl
{
    id _target;
    SEL _action;
    BOOL _on;
    BOOL _active;
    BOOL _dragged;
    BOOL _draggingTowardsOn;
    NSColor *_tintColor;
    CALayer *_rootLayer;
    CALayer *_backgroundLayer;
    CALayer *_knobLayer;
    CATextLayer *_knobLayerLabel;
    CALayer *_knobInsideLayer;
}

- (void).cxx_destruct;
- (void)_invokeTargetAction;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (BOOL)acceptsFirstResponder;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (id)accessibilityHitTest:(struct CGPoint)arg1;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
- (BOOL)accessibilityIsIgnored;
- (void)accessibilityPerformAction:(id)arg1;
- (void)accessibilitySetValue:(id)arg1 forAttribute:(id)arg2;
- (SEL)action;
@property(readonly, nonatomic) CALayer *backgroundLayer; // @synthesize backgroundLayer=_backgroundLayer;
- (BOOL)canBecomeKeyView;
- (void)drawFocusRingMask;
- (struct CGRect)focusRingMaskBounds;
@property(nonatomic, getter=hasDragged) BOOL dragged; // @synthesize dragged=_dragged;
- (void)hideChangedStateAnimation;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic, getter=isActive) BOOL active; // @synthesize active=_active;
@property(nonatomic, getter=isDraggingTowardsOn) BOOL draggingTowardsOn; // @synthesize draggingTowardsOn=_draggingTowardsOn;
@property(nonatomic, getter=isOn) BOOL on; // @synthesize on=_on;
- (double)knobHeightForSize:(struct CGSize)arg1;
@property(readonly, nonatomic) CALayer *knobInsideLayer; // @synthesize knobInsideLayer=_knobInsideLayer;
@property(readonly, nonatomic) CALayer *knobLayer; // @synthesize knobLayer=_knobLayer;
@property(readonly, nonatomic) CATextLayer *knobLayerLabel; // @synthesize knobLayerLabel=_knobLayerLabel;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)moveLeft:(id)arg1;
- (void)moveRight:(id)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (struct CGRect)rectForKnob;
- (void)reloadLayer;
- (void)reloadLayerSize;
@property(readonly, nonatomic) CALayer *rootLayer; // @synthesize rootLayer=_rootLayer;
- (void)setAction:(SEL)arg1;
- (void)setEnabled:(BOOL)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)setTarget:(id)arg1;
@property(retain, nonatomic) NSColor *tintColor; // @synthesize tintColor=_tintColor;
- (void)setUp;
- (void)setUpLayers;
- (void)showChangedState;
- (id)target;
- (void)updateKnobLabelText;
- (BOOL)wantsDefaultClipping;

@end

