//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface KeyboardPressSimulator : NSObject
{
}

+ (void)execute:(unsigned short)arg1 flag:(unsigned long long)arg2;
+ (void)executeChar:(unsigned short)arg1;
+ (void)executeSleepCommandForHighSierraOrHigher;
+ (void)hideScreensaver;
+ (void)putComputerToSleep;
+ (void)showScreensaver;
+ (void)showScreensaverOption2;
+ (void)simulateDelete;
+ (void)simulateDeleteAll;
+ (void)simulateDeletePresses:(int)arg1;
+ (void)simulateDeletePresses:(int)arg1 withFollowingString:(id)arg2 withEnterOnEnd:(BOOL)arg3;
+ (void)simulateEnter;
+ (void)simulateEscape;
+ (void)simulateKeyStroke:(id)arg1;
+ (void)simulatePressString:(id)arg1 shouldContinueWithEntry:(CDUnknownBlockType)arg2 withCompletion:(CDUnknownBlockType)arg3;
+ (void)simulatePressString:(id)arg1 withEnterOnEnd:(BOOL)arg2;
+ (void)simulateSelectAll;
+ (void)sleepAppleScriptUsingFinder;
+ (void)turnOffDisplay;
+ (void)wakeComputerFromSleep;
+ (void)wakeComputerFromSleepMainThread;

@end

