//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol LeScannerConnectionInternalDelegate <NSObject>
- (void)scannerConnection:(id <LEScannerConnectionInternal>)arg1 didGetStuckInState:(int)arg2;
- (void)scannerConnection:(id <LEScannerConnectionInternal>)arg1 didUpdateState:(int)arg2;
- (void)scannerConnection:(id <LEScannerConnectionInternal>)arg1 performCommand:(int)arg2;
- (BOOL)scannerConnection:(id <LEScannerConnectionInternal>)arg1 shouldAcceptServiceWithUUID:(NSString *)arg2;
- (void)scannerConnectionDidDetectInappropriateServices:(id <LEScannerConnectionInternal>)arg1;
- (void)scannerConnectionExperiencedCorruptedBluetoothCache:(id <LEScannerConnectionInternal>)arg1;
- (void)scannerConnectionExperiencedUnsolvableError:(id <LEScannerConnectionInternal>)arg1;
- (NSArray *)scannerConnectionGetArrayOfServices:(id <LEScannerConnectionInternal>)arg1;
- (void)scannerConnectionIsNotAnAppropriateConnection:(id <LEScannerConnectionInternal>)arg1;
- (BOOL)scannerConnectionShouldAcceptAllServices:(id <LEScannerConnectionInternal>)arg1;
- (BOOL)scannerShouldScanForServicesAfterConnection:(id <LEScannerConnectionInternal>)arg1;
@end

