//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "LEScannerConnection.h"
#import "NSObject.h"

@class CBPeripheral, NSError, NSNumber;

@protocol LEScannerConnectionInternal <NSObject, LEScannerConnection>
- (void)connectionEstablished;
- (void)connectionLost;
- (void)didAttemptConnection;
- (void)handleGeneralBleutoothError:(NSError *)arg1;
- (id)initWithPeripheral:(CBPeripheral *)arg1 withDelegate:(id <LeScannerConnectionInternalDelegate>)arg2;
- (void)notifyDelegateOfConnect;
- (void)notifyDelegateOfDisconnect;
- (CBPeripheral *)peripheral;
- (void)recovered;
- (BOOL)requireHandshake;
- (void)setInternalDelegate:(id <LeScannerConnectionInternalDelegate>)arg1;
- (void)setRSSI:(NSNumber *)arg1;
- (void)updateConnectionWithPeripheral:(CBPeripheral *)arg1;
@end

