//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@protocol LEScannerConnectionDelegate <NSObject>
- (void)connection:(id <LEScannerConnection>)arg1 didReceiveString:(NSString *)arg2;
- (void)connection:(id <LEScannerConnection>)arg1 didUpdateRSSI:(NSNumber *)arg2;
- (void)connectionDidConnect:(id <LEScannerConnection>)arg1;
- (void)connectionDidDisconnect:(id <LEScannerConnection>)arg1;
@end

