//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@protocol LEScannerDelegate <NSObject>
- (void)scanner:(id <LEScanner>)arg1 didDetect:(id <LEScannerConnection>)arg2 withRSSI:(NSNumber *)arg3;
- (void)scanner:(id <LEScanner>)arg1 didDiscover:(id <LEScannerConnection>)arg2 withRSSI:(NSNumber *)arg3;
- (void)scanner:(id <LEScanner>)arg1 didExperienceError:(int)arg2 forConnection:(id <LEScannerConnection>)arg3;
- (void)scannerIsOnAndReady;
- (BOOL)scannerShouldIgnoreAllDiscoveredConnections:(id <LEScanner>)arg1;
- (BOOL)scannerShouldProceedWithConnectingTo:(id <LEScannerConnection>)arg1;
@end

