//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSNumber, NSString;

@interface LEScannerIgnorePeripheral : NSObject <NSCoding>
{
    NSString *_uuid;
    NSNumber *_ignoreReasonNumber;
    NSNumber *_numberOfTimesIgnoredNumber;
}

- (void).cxx_destruct;
- (void)decodeWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
@property(readonly, nonatomic) int ignoreReason;
@property(nonatomic) NSNumber *ignoreReasonNumber; // @synthesize ignoreReasonNumber=_ignoreReasonNumber;
- (id)initWithCoder:(id)arg1;
- (id)initWithUUID:(id)arg1 ignoreReason:(int)arg2;
@property(nonatomic) long long numberOfTimesIgnored;
@property(nonatomic) NSNumber *numberOfTimesIgnoredNumber; // @synthesize numberOfTimesIgnoredNumber=_numberOfTimesIgnoredNumber;
- (void)setIgnoreReason:(int)arg1;
@property(retain, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
- (void)updateIgnoreReasonIfNeeded:(int)arg1;

@end

