//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CBCentralManagerDelegate.h"
#import "CBPeripheralDelegate.h"
#import "LEScanner.h"
#import "LeScannerConnectionInternalDelegate.h"

@class CBCentralManager, EventTimestamp, LEScannerCachedConnections, LEScannerIgnoreManager, LeDataManager, NSMutableArray, NSMutableDictionary, NSString;

@interface LEScannerController : NSObject <CBCentralManagerDelegate, CBPeripheralDelegate, LeScannerConnectionInternalDelegate, LEScanner>
{
    NSString *uniqueStaticPeripheralId;
    CBCentralManager *centralManager;
    long long mainErrorCount;
    LEScannerIgnoreManager *ignoreManager;
    LEScannerCachedConnections *cachedConnections;
    LeDataManager *persistantData;
    NSMutableArray *myFoundPeripherals;
    NSMutableArray *serviceUUIDToAcceptConnection;
    NSMutableDictionary *myFoundConnections;
    NSMutableDictionary *myConnectedConnections;
    NSMutableDictionary *pendingConnectPeripherals;
    BOOL isScanning;
    BOOL shouldAceptNotDefinedUUIDs;
    long long numberOfTimesScannedForSpecificServices;
    long long numberOfTimesScannedForAllServices;
    EventTimestamp *restartScanningEvent;
    EventTimestamp *clearIgnoreListEvent;
    EventTimestamp *lastConnectionAttemptTimestamp;
    EventTimestamp *mainConnectionDisconnectAttempt;
    EventTimestamp *peripheralRecoveredTimestamp;
    EventTimestamp *recoverServicesTimestamp;
    EventTimestamp *longSleepWakeUp;
    EventTimestamp *applicationDidWake;
    BOOL shouldRetreiveConnectedPeripherals;
    id <LEScannerDelegate> _delegate;
}

- (void).cxx_destruct;
- (void)acceptUUIDServiceString:(id)arg1;
- (void)applicationDidWake;
- (void)applicationDidWakeAfterLongSleep;
- (void)cachePeripheralWithUUID:(id)arg1;
- (void)centralManager:(id)arg1 didConnectPeripheral:(id)arg2;
- (void)centralManager:(id)arg1 didDisconnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didDiscoverPeripheral:(id)arg2 advertisementData:(id)arg3 RSSI:(id)arg4;
- (void)centralManager:(id)arg1 didFailToConnectPeripheral:(id)arg2 error:(id)arg3;
- (void)centralManager:(id)arg1 didRetrieveConnectedPeripherals:(id)arg2;
- (void)centralManager:(id)arg1 didRetrievePeripheral:(id)arg2;
- (void)centralManager:(id)arg1 didRetrievePeripherals:(id)arg2;
- (void)centralManager:(id)arg1 willRestoreState:(id)arg2;
- (void)centralManagerDidUpdateState:(id)arg1;
- (void)checkAfterDelayIfAnyPeripheralInConnectQueue;
- (void)cleanPeripheralsForIgnoreReason:(int)arg1;
- (void)cleanupAllConnections;
- (void)clearAcceptUUIDServiceList;
- (void)clearDevicesForced:(BOOL)arg1;
- (void)clearPeripheralIgnoreList;
- (void)connectCustomPeripheral:(id)arg1;
- (id)connectedConnections;
- (void)connectionDidAttemptToConnect:(id)arg1;
- (id)connectionForPeripheral:(id)arg1;
- (id)connectionForUnID:(id)arg1;
- (BOOL)connectionIsInDisconnectProccess:(id)arg1;
- (void)connectionIsTryingToConnectForALongPeriodOfTime:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <LEScannerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didRecoverPeripheral:(id)arg1;
- (void)disconnect:(id)arg1;
- (void)disconnectPeripheral:(id)arg1;
- (void)discoveredConnectedConneciton:(id)arg1 withRSSI:(id)arg2;
- (void)discoveredInterestingPeripheral:(id)arg1 RSSI:(id)arg2;
- (void)executeScanForServices:(id)arg1;
- (void)executeSingleScan;
- (id)foundPeripherals;
- (id)getArrayOfCBUUIDFromServices;
- (id)getOptionsForServices:(id)arg1 includeSolicitedServicesKey:(BOOL)arg2;
- (void)handlePeripheralForMainConneciton:(id)arg1;
- (void)handleRecoveredPeripherals:(id)arg1;
- (void)ignorePeripheralWithUUID:(id)arg1 forReason:(int)arg2;
- (id)initWithDelegate:(id)arg1;
- (void)initializeCentralManager;
- (BOOL)isAnyPeripheralConnecting;
- (BOOL)isScanning;
- (void)markConnectionAsUnsuitable:(id)arg1;
- (void)notifyDelegatesOfDisconnect;
- (void)performBLETurnedOnAndReadyNotification;
- (BOOL)peripheralIsAlreadyConnecting:(id)arg1;
- (void)prepareAndScanForServices:(id)arg1;
- (void)putConnectionToConnectQueueAndTryToConnectLater:(id)arg1;
- (void)recreateConnectionAndConnectPeripheral:(id)arg1;
- (void)recreateConnectionForPeripheral:(id)arg1;
- (void)removeAllCachedConnections;
- (void)removeAndIgnoreAllPeripheralsExceptPeripheralWithUUID:(id)arg1;
- (void)removeCachedPeripheralWithUUID:(id)arg1;
- (void)removeConnectionFromConnectQueue:(id)arg1;
- (void)removePeripheralFromIgnoreList:(id)arg1;
- (void)resetScanProperties;
- (void)restartScan:(id)arg1;
- (void)retreiveConnectedPeripheralsAndScan;
- (void)retrievePeripheralsOnNextScanIfNeeded;
- (void)scanForServicesDependingOnOperatingSystem:(id)arg1 options:(id)arg2;
- (void)scannerConnection:(id)arg1 didGetStuckInState:(int)arg2;
- (void)scannerConnection:(id)arg1 didUpdateState:(int)arg2;
- (void)scannerConnection:(id)arg1 performCommand:(int)arg2;
- (BOOL)scannerConnection:(id)arg1 shouldAcceptServiceWithUUID:(id)arg2;
- (void)scannerConnectionDidDetectInappropriateServices:(id)arg1;
- (void)scannerConnectionExperiencedCorruptedBluetoothCache:(id)arg1;
- (void)scannerConnectionExperiencedUnsolvableError:(id)arg1;
- (id)scannerConnectionGetArrayOfServices:(id)arg1;
- (void)scannerConnectionIsNotAnAppropriateConnection:(id)arg1;
- (BOOL)scannerConnectionShouldAcceptAllServices:(id)arg1;
- (BOOL)scannerShouldScanForServicesAfterConnection:(id)arg1;
- (void)setServiceUUIDToSearchFor:(id)arg1;
- (void)setServiceUUIDsToSearchFor:(id)arg1;
- (BOOL)shouldForceDisconnectConnection:(id)arg1;
- (BOOL)shouldIgnorePeripheral:(id)arg1 withAdvertismentData:(id)arg2;
- (BOOL)shouldScanForAllServices;
- (double)specificSierraScanRatio;
- (void)stopScanning;
- (void)tryToConnectToPeripheral:(id)arg1 RSSI:(id)arg2;
- (void)tryToReconnectToMainConnection;
- (void)tryToTurnBluetoothOn;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

