//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface LEScannerIgnoreManager : NSObject
{
    NSMutableDictionary *_peripheralsToIgnore;
    NSMutableDictionary *_peripheralsToBeAddedOnIgnoreList;
}

- (void).cxx_destruct;
- (void)ignorePeripheralWithUUID:(id)arg1 forReason:(int)arg2 afterCount:(long long)arg3;
- (id)init;
- (BOOL)peripheralIsOnTheIgnoreList:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *peripheralsToBeAddedOnIgnoreList; // @synthesize peripheralsToBeAddedOnIgnoreList=_peripheralsToBeAddedOnIgnoreList;
@property(retain, nonatomic) NSMutableDictionary *peripheralsToIgnore; // @synthesize peripheralsToIgnore=_peripheralsToIgnore;
- (void)permamentlyIgnorePeripheralWithUUID:(id)arg1 forReason:(int)arg2;
- (void)removeAllPeripheralsFromTheIgnoreList;
- (void)removeIgnorePeripheralsForReason:(int)arg1;
- (void)removeIgnorePeripheralsForReason:(int)arg1 fromDictionary:(id)arg2;
- (void)removePeripheralFromIgnoreList:(id)arg1;
- (void)retreiveSavedPeripheralsToIgnore;
- (void)savePeripheralsToIgnore;

@end

