//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LEScannerStateHelper : NSObject
{
}

+ (BOOL)scannerStateIsConnecting:(int)arg1;
+ (id)scannerStateToString:(int)arg1 forPeripheral:(id)arg2;

@end

