//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@protocol LEScanner <NSObject>
- (void)acceptUUIDServiceString:(NSString *)arg1;
- (void)cachePeripheralWithUUID:(NSString *)arg1;
- (void)cleanPeripheralsForIgnoreReason:(int)arg1;
- (void)cleanupAllConnections;
- (void)clearDevicesForced:(BOOL)arg1;
- (void)clearPeripheralIgnoreList;
- (id <LEScannerConnection>)connectionForUnID:(NSString *)arg1;
- (void)executeSingleScan;
- (void)ignorePeripheralWithUUID:(NSString *)arg1 forReason:(int)arg2;
- (id)initWithDelegate:(id <LEScannerDelegate>)arg1;
- (BOOL)isScanning;
- (void)performBLETurnedOnAndReadyNotification;
- (void)removeAllCachedConnections;
- (void)removeCachedPeripheralWithUUID:(NSString *)arg1;
- (void)removePeripheralFromIgnoreList:(NSString *)arg1;
- (void)setServiceUUIDToSearchFor:(NSString *)arg1;
- (void)setServiceUUIDsToSearchFor:(NSArray *)arg1;
- (void)stopScanning;
@end

