//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ButtonViewModel, NSColor, NSString;

@interface ListCellViewModel : NSObject
{
    BOOL _isCollapsed;
    BOOL _isOn;
    BOOL _isDisabled;
    NSString *_identifier;
    Class _viewClass;
    NSString *_rowId;
    NSString *_title;
    NSString *_descriptionText;
    NSString *_iconName;
    NSString *_secondaryIconName;
    NSColor *_customColor;
    ButtonViewModel *_primaryButtonVM;
    NSString *_primaryActionText;
    CDUnknownBlockType _primaryActionHandler;
    NSString *_secondaryActionText;
    CDUnknownBlockType _secondaryActionHandler;
    double _customRowHeight;
    NSString *_additionalText;
    NSString *_valueText;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *additionalText; // @synthesize additionalText=_additionalText;
@property(retain, nonatomic) NSColor *customColor; // @synthesize customColor=_customColor;
@property(nonatomic) double customRowHeight; // @synthesize customRowHeight=_customRowHeight;
@property(retain, nonatomic) NSString *descriptionText; // @synthesize descriptionText=_descriptionText;
- (id)descriptionText:(id)arg1;
@property(retain, nonatomic) NSString *iconName; // @synthesize iconName=_iconName;
- (id)iconName:(id)arg1;
@property(retain, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
@property(nonatomic) BOOL isCollapsed; // @synthesize isCollapsed=_isCollapsed;
@property(nonatomic) BOOL isDisabled; // @synthesize isDisabled=_isDisabled;
@property(nonatomic) BOOL isOn; // @synthesize isOn=_isOn;
@property(copy) CDUnknownBlockType primaryActionHandler; // @synthesize primaryActionHandler=_primaryActionHandler;
- (id)primaryActionHandler:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSString *primaryActionText; // @synthesize primaryActionText=_primaryActionText;
@property(retain, nonatomic) ButtonViewModel *primaryButtonVM; // @synthesize primaryButtonVM=_primaryButtonVM;
@property(retain, nonatomic) NSString *rowId; // @synthesize rowId=_rowId;
@property(copy) CDUnknownBlockType secondaryActionHandler; // @synthesize secondaryActionHandler=_secondaryActionHandler;
- (id)secondaryActionHandler:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) NSString *secondaryActionText; // @synthesize secondaryActionText=_secondaryActionText;
@property(retain, nonatomic) NSString *secondaryIconName; // @synthesize secondaryIconName=_secondaryIconName;
- (id)secondaryIconName:(id)arg1;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *valueText; // @synthesize valueText=_valueText;
@property(nonatomic) Class viewClass; // @synthesize viewClass=_viewClass;
- (id)title:(id)arg1;

@end

