//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class ListViewModelMapper, NSArray, NearLockListView;

@interface ListViewModelController : BaseViewController
{
    NearLockListView *_listView;
    NSArray *_listViewModel;
    ListViewModelMapper *_listViewModelMapper;
}

- (void).cxx_destruct;
- (long long)indexForRowId:(id)arg1;
- (id)initWithListViewModel:(id)arg1;
@property(retain, nonatomic) NearLockListView *listView; // @synthesize listView=_listView;
@property(retain, nonatomic) NSArray *listViewModel; // @synthesize listViewModel=_listViewModel;
@property(retain, nonatomic) ListViewModelMapper *listViewModelMapper; // @synthesize listViewModelMapper=_listViewModelMapper;
- (void)reloadListView;
- (void)selectRowId:(id)arg1 animated:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)selectRowId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)selectViewModel:(id)arg1;
- (void)setUpListView;
- (void)viewDidLoad;

@end

