//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ListViewModelFactory : NSObject
{
}

+ (id)buttonCellWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)buttonCellWithTitle:(id)arg1 button:(id)arg2 action:(CDUnknownBlockType)arg3;
+ (id)buttonCellWithTitle:(id)arg1 color:(id)arg2 action:(CDUnknownBlockType)arg3;
+ (id)checkBoxWithIcon:(id)arg1 title:(id)arg2 description:(id)arg3 isOn:(BOOL)arg4 action:(CDUnknownBlockType)arg5 readMoreButton:(id)arg6 readMoreAction:(CDUnknownBlockType)arg7;
+ (id)collapsableCellWithTitle:(id)arg1 description:(id)arg2 collapsed:(BOOL)arg3 actionTitle:(id)arg4 action:(CDUnknownBlockType)arg5 collapseAction:(CDUnknownBlockType)arg6;
+ (id)collapsableCellWithTitle:(id)arg1 type:(int)arg2 description:(id)arg3 collapsed:(BOOL)arg4 actionTitle:(id)arg5 action:(CDUnknownBlockType)arg6 collapseAction:(CDUnknownBlockType)arg7;
+ (id)customCheckBoxWithIcon:(id)arg1 title:(id)arg2 description:(id)arg3 isOn:(BOOL)arg4 action:(CDUnknownBlockType)arg5;
+ (id)descriptionCellCenteredWithText:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)devicesCellWithMacImage:(id)arg1 macName:(id)arg2 mobileImage:(id)arg3 mobileName:(id)arg4 connected:(BOOL)arg5 distance:(id)arg6;
+ (id)doubleButtonCellWithButton1:(id)arg1 action1:(CDUnknownBlockType)arg2 button2:(id)arg3 action2:(CDUnknownBlockType)arg4;
+ (id)emptyCellWithAction:(CDUnknownBlockType)arg1;
+ (id)emptyCellWithHeight:(double)arg1 action:(CDUnknownBlockType)arg2;
+ (id)gifImageCellWithImage:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)iconTitleDescriptionCellWithIcon:(id)arg1 title:(id)arg2 description:(id)arg3 action:(CDUnknownBlockType)arg4;
+ (id)iconTitleDescriptionCellWithIcon:(id)arg1 title:(id)arg2 description:(id)arg3 buttonTitle:(id)arg4 action:(CDUnknownBlockType)arg5;
+ (id)iconTitleDescriptionCellWithIcon:(id)arg1 title:(id)arg2 description:(id)arg3 buttonVM:(id)arg4;
+ (id)imageCellWithImage:(id)arg1 height:(double)arg2 action:(CDUnknownBlockType)arg3;
+ (id)largeIconTitleDescriptionCell:(id)arg1 title:(id)arg2 description:(id)arg3;
+ (id)largeIconTitleDescriptionCell:(id)arg1 title:(id)arg2 description:(id)arg3 action:(CDUnknownBlockType)arg4;
+ (id)loadingCellWithTitle:(id)arg1 description:(id)arg2 action:(CDUnknownBlockType)arg3;
+ (id)readMoreButtonCellWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)regularCellWithIcon:(id)arg1 title:(id)arg2 action:(CDUnknownBlockType)arg3;
+ (id)separatorCell;
+ (id)separatorCellWithTitle:(id)arg1;
+ (id)simpleCheckBoxWithIcon:(id)arg1 title:(id)arg2 isOn:(BOOL)arg3 action:(CDUnknownBlockType)arg4;
+ (id)simpleImageCellWithImage:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)sliderWithMax:(int)arg1 min:(int)arg2 value:(int)arg3 textValue:(CDUnknownBlockType)arg4 description:(id)arg5 action:(CDUnknownBlockType)arg6;
+ (id)titleCell:(id)arg1 action:(CDUnknownBlockType)arg2 buttonTitle:(id)arg3 buttonAction:(CDUnknownBlockType)arg4;
+ (id)titleCellCenteredWithTitle:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)titleDescriptionCellCenteredWithTitle:(id)arg1 description:(id)arg2 action:(CDUnknownBlockType)arg3;
+ (id)titleDescriptionCellWithTitle:(id)arg1 description:(id)arg2 action:(CDUnknownBlockType)arg3;
+ (id)titleDescriptionCellWithTitle:(id)arg1 description:(id)arg2 action:(CDUnknownBlockType)arg3 buttonTitle:(id)arg4 buttonAction:(CDUnknownBlockType)arg5;
+ (id)titleValueCell:(id)arg1 value:(id)arg2 action:(CDUnknownBlockType)arg3 buttonTitle:(id)arg4 buttonAction:(CDUnknownBlockType)arg5;

@end

