//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PXListViewDelegate.h"

@class NSArray, NSString, NearLockListView;

@interface ListViewModelMapper : NSObject <PXListViewDelegate>
{
    NearLockListView *_listView;
    NSArray *_listViewModel;
}

- (void).cxx_destruct;
- (Class)classForCellViewModel:(id)arg1;
- (id)initWithListView:(id)arg1;
@property(retain, nonatomic) NearLockListView *listView; // @synthesize listView=_listView;
- (id)listView:(id)arg1 cellForRow:(unsigned long long)arg2;
- (id)listView:(id)arg1 cellForViewModel:(id)arg2;
- (double)listView:(id)arg1 heightForViewModel:(id)arg2;
- (double)listView:(id)arg1 heightOfRow:(unsigned long long)arg2;
@property(retain, nonatomic) NSArray *listViewModel; // @synthesize listViewModel=_listViewModel;
- (void)listViewSelectionDidChange:(id)arg1;
- (unsigned long long)numberOfRowsInListView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

