//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class LOTAnimationView, NSTextField, NSView;

@interface LoadingViewController : BaseViewController
{
    NSView *_animationContainer;
    NSTextField *_mainTextField;
    NSView *_bottomSeparatorView;
    LOTAnimationView *_animation;
}

- (void).cxx_destruct;
@property(retain, nonatomic) LOTAnimationView *animation; // @synthesize animation=_animation;
@property(retain, nonatomic) NSView *animationContainer; // @synthesize animationContainer=_animationContainer;
@property(retain, nonatomic) NSView *bottomSeparatorView; // @synthesize bottomSeparatorView=_bottomSeparatorView;
- (void)hideAnimationWithCompletion:(CDUnknownBlockType)arg1;
- (void)hideLoader;
@property(retain, nonatomic) NSTextField *mainTextField; // @synthesize mainTextField=_mainTextField;
- (void)setCompletionAnimation:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setTitleText:(id)arg1;
- (void)showAnimation:(id)arg1 loop:(BOOL)arg2 completion:(CDUnknownBlockType)arg3;
- (void)viewDidAppear;
- (void)viewDidDisappear;
- (void)viewDidLoad;

@end

