//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LockMacController : NSObject
{
}

+ (void)launchAndQuitSecurityPreferences;
+ (void)lockScreen;
+ (void)lockScreenCommand;
+ (void)lockScreenFromKeychain;
+ (void)lockScreenOld;
+ (void)lockScreenPrivateCommand;
+ (void)manuallySetAskForPasswordAndNoScreensaverDelay;
+ (int)readAskForPasswordOld;
+ (int)readIntArgumentFromScreensaverDefaultsWithKey:(id)arg1;
+ (int)readScreensaveDelay;
+ (void)screenSaverTest;
+ (void)setAskForPassword:(int)arg1;
+ (void)setInt:(int)arg1 forArgumentInScreensaverDefaultsListWithKey:(id)arg2;
+ (void)setScreensaverDelay:(int)arg1;
+ (void)touchSecurityPreferences;
+ (void)turnDisplayOff;

@end

