//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MobileDevice;

@interface LoginLogoutCommand : NSObject
{
    int _command;
    int _actionOnLogout;
    int _commandReason;
    MobileDevice *_mobileDeviceResponsible;
}

- (void).cxx_destruct;
@property int actionOnLogout; // @synthesize actionOnLogout=_actionOnLogout;
@property int command; // @synthesize command=_command;
@property int commandReason; // @synthesize commandReason=_commandReason;
- (id)initLoginCommandWithDevice:(id)arg1;
- (id)initLogoutCommandWithDevice:(id)arg1 withLogoutAction:(int)arg2;
@property(retain) MobileDevice *mobileDeviceResponsible; // @synthesize mobileDeviceResponsible=_mobileDeviceResponsible;

@end

