//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseEntry.h"

#import "NSCoding.h"

@class NSNumber;

@interface LoginLogoutEntry : BaseEntry <NSCoding>
{
    NSNumber *_event;
    NSNumber *_responsible;
}

- (void).cxx_destruct;
- (void)decodeWithCoder:(id)arg1;
- (id)descriptionForTrackEvent;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSNumber *event; // @synthesize event=_event;
- (id)initWithCoder:(id)arg1;
- (id)initWithEvent:(int)arg1 date:(id)arg2 reason:(int)arg3;
- (BOOL)isSessionEndingEntry;
- (BOOL)isSessionStartingEntry;
@property(retain, nonatomic) NSNumber *responsible; // @synthesize responsible=_responsible;
- (id)unlockDescription;
- (id)unlockIconImageName;

@end

