//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSImageView, NSTextField;

@interface LoginPhotosView : BaseViewController
{
    id <LoginPhotosViewDelegate> _delegate;
    NSTextField *_titleLabel;
    NSTextField *_descriptionLabel;
    NSImageView *_secondIcon;
    NSTextField *_secondDescriptionLabel;
    NSImageView *_thirdIcon;
    NSTextField *_thirdDescriptionLabel;
    NSImageView *_fourthIcon;
    NSTextField *_fourthDescriptionLabel;
    NSImageView *_fifthIcon;
    NSTextField *_fifthDescriptionLabel;
    NSButton *_showButton;
    NSTextField *_footNoteLabel;
}

- (void).cxx_destruct;
- (void)backToggled:(id)arg1;
@property(nonatomic) __weak id <LoginPhotosViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) NSTextField *fifthDescriptionLabel; // @synthesize fifthDescriptionLabel=_fifthDescriptionLabel;
@property(retain, nonatomic) NSImageView *fifthIcon; // @synthesize fifthIcon=_fifthIcon;
@property(retain, nonatomic) NSTextField *footNoteLabel; // @synthesize footNoteLabel=_footNoteLabel;
@property(retain, nonatomic) NSTextField *fourthDescriptionLabel; // @synthesize fourthDescriptionLabel=_fourthDescriptionLabel;
@property(retain, nonatomic) NSImageView *fourthIcon; // @synthesize fourthIcon=_fourthIcon;
@property(retain, nonatomic) NSTextField *secondDescriptionLabel; // @synthesize secondDescriptionLabel=_secondDescriptionLabel;
@property(retain, nonatomic) NSImageView *secondIcon; // @synthesize secondIcon=_secondIcon;
@property(retain, nonatomic) NSButton *showButton; // @synthesize showButton=_showButton;
@property(retain, nonatomic) NSTextField *thirdDescriptionLabel; // @synthesize thirdDescriptionLabel=_thirdDescriptionLabel;
@property(retain, nonatomic) NSImageView *thirdIcon; // @synthesize thirdIcon=_thirdIcon;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)showToggled:(id)arg1;
- (void)updateStrings;
- (void)viewDidLoad;

@end

