//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LoginLogoutFilterModel : NSObject
{
    BOOL _startFilterOn;
    BOOL _loginFilterOn;
    BOOL _logoutFilterOn;
    BOOL _failedLoginFilterOn;
    BOOL _sessionDurationFilterOn;
}

+ (id)sessionDurationFilter;
@property(nonatomic) BOOL failedLoginFilterOn; // @synthesize failedLoginFilterOn=_failedLoginFilterOn;
@property(nonatomic) BOOL loginFilterOn; // @synthesize loginFilterOn=_loginFilterOn;
@property(nonatomic) BOOL logoutFilterOn; // @synthesize logoutFilterOn=_logoutFilterOn;
@property(nonatomic) BOOL sessionDurationFilterOn; // @synthesize sessionDurationFilterOn=_sessionDurationFilterOn;
@property(nonatomic) BOOL startFilterOn; // @synthesize startFilterOn=_startFilterOn;

@end

