//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LoginLogoutController, MobileDevice;

@protocol LoginLogoutControllerDelegate <NSObject>
- (void)loginLogoutController:(LoginLogoutController *)arg1 canNotLoginWithGivenPasswordForMobileDevice:(MobileDevice *)arg2;
- (void)loginLogoutController:(LoginLogoutController *)arg1 didLoginbyMobileDevice:(MobileDevice *)arg2 commandReason:(int)arg3;
- (void)loginLogoutController:(LoginLogoutController *)arg1 didLogoutbyMobileDevice:(MobileDevice *)arg2 commandReason:(int)arg3;
- (void)loginLogoutControllerDidFailToLogin:(LoginLogoutController *)arg1;
- (void)loginLogoutControllerDidLoginManualyByUser:(LoginLogoutController *)arg1;
- (void)loginLogoutControllerDidLogoutManualyByUser:(LoginLogoutController *)arg1;
- (void)loginLogoutControllerDisplayOnButUserNotLoggedIn:(LoginLogoutController *)arg1;
- (void)loginLogoutControllerUnableToLockMac:(LoginLogoutController *)arg1;
- (void)loginLogoutControllerUnableToUnlockMac:(LoginLogoutController *)arg1;
@end

