//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp, NSString, NSTimer, _TtC11NearLockOSX13MacLockUnlock;

@interface LoginLogoutExecution : NSObject
{
    BOOL _shouldWakeDevice;
    int _previousDisplayState;
    int _currentDisplayState;
    id <LoginLogoutCommandsDelegate> _delegate;
    NSString *_password;
    NSTimer *_screenChangedTimer;
    EventTimestamp *_passwordInsertionExecutionTimestamp;
    _TtC11NearLockOSX13MacLockUnlock *_lockUnlock;
}

- (void).cxx_destruct;
@property(nonatomic) int currentDisplayState; // @synthesize currentDisplayState=_currentDisplayState;
- (void)dealloc;
@property(nonatomic) __weak id <LoginLogoutCommandsDelegate> delegate; // @synthesize delegate=_delegate;
- (void)executeSleepCommand;
- (id)init;
@property(retain, nonatomic) _TtC11NearLockOSX13MacLockUnlock *lockUnlock; // @synthesize lockUnlock=_lockUnlock;
- (void)loginIfEverythingReady;
- (void)loginIfLockOnScreenShownAndDeviceLocked;
@property(retain, nonatomic) NSString *password; // @synthesize password=_password;
@property(retain, nonatomic) EventTimestamp *passwordInsertionExecutionTimestamp; // @synthesize passwordInsertionExecutionTimestamp=_passwordInsertionExecutionTimestamp;
@property(nonatomic) int previousDisplayState; // @synthesize previousDisplayState=_previousDisplayState;
- (void)registerForSleepAndWakeServices;
@property(retain, nonatomic) NSTimer *screenChangedTimer; // @synthesize screenChangedTimer=_screenChangedTimer;
- (void)screenStateUpdated;
@property BOOL shouldWakeDevice; // @synthesize shouldWakeDevice=_shouldWakeDevice;
- (void)showScreenSaver;
- (void)test;
- (void)turnOfDisplay;
- (void)wakeComputerForCurrentUserWithPassword:(id)arg1;
- (void)wakeComputerFromSleepToShowLockScreen;
- (void)wakeUpComuterFromSleep;

@end

