//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FailedLoginEntry, LoginLogoutEntry, LoginLogoutHistoryWindow;

@protocol LoginLogoutHistoryWindowDelegate <NSObject>
- (void)loginLogoutHistoryWindow:(LoginLogoutHistoryWindow *)arg1 didSelectFailedLoginEntry:(FailedLoginEntry *)arg2;
- (void)loginLogoutHistoryWindow:(LoginLogoutHistoryWindow *)arg1 didSelectLoginLogoutEntry:(LoginLogoutEntry *)arg2;
- (void)loginLogoutHistoryWindowDidSelectInfo:(LoginLogoutHistoryWindow *)arg1;
@end

