//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LoginLogoutCommandsDelegate.h"

@class EventTimestamp, LoginLogoutCommand, LoginLogoutExecution, NSString, NSTimer;

@interface LoginLogoutController : NSObject <LoginLogoutCommandsDelegate>
{
    id <LoginLogoutControllerDelegate> _delegate;
    LoginLogoutCommand *_commandInExecution;
    LoginLogoutCommand *_commandInQueue;
    LoginLogoutExecution *_loginLogoutCommands;
    EventTimestamp *_commandTimestamp;
    EventTimestamp *_insertedPasswordTimestamp;
    NSTimer *_safetyExecutionTimer;
    NSTimer *_logoutSafetyTimer;
    NSTimer *_loginSafetyTimer;
    NSTimer *_timerToCheckIfLoginSucceded;
}

- (void).cxx_destruct;
- (BOOL)allConditionsForCommandExecutionMet:(id)arg1;
- (void)checkIfLoginFailedAttempt;
@property(retain, nonatomic) LoginLogoutCommand *commandInExecution; // @synthesize commandInExecution=_commandInExecution;
@property(retain, nonatomic) LoginLogoutCommand *commandInQueue; // @synthesize commandInQueue=_commandInQueue;
@property(retain, nonatomic) EventTimestamp *commandTimestamp; // @synthesize commandTimestamp=_commandTimestamp;
- (void)dealloc;
@property(nonatomic) __weak id <LoginLogoutControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didExecuteCommand;
- (void)displayTurnedOnAndUserNotLoggedIn;
- (void)executeCommand:(id)arg1;
- (void)executeCommandIfNeeded:(id)arg1;
- (void)executeCommandInQueueIfAny;
- (void)executeLoginCommand:(id)arg1;
- (void)executeLogotCommand:(id)arg1;
- (id)init;
@property(retain, nonatomic) EventTimestamp *insertedPasswordTimestamp; // @synthesize insertedPasswordTimestamp=_insertedPasswordTimestamp;
- (void)invalidateLoginSafetyTimer;
- (void)invalidateLogoutSafetyTimer;
- (void)invalidateSafetyExecutionTimer;
- (BOOL)isAnyCommandInExecution;
- (BOOL)isExecutingLoginCommand;
- (BOOL)isExecutingLogoutCommand;
- (void)lockScreenFromMobileDevice:(id)arg1 action:(int)arg2 commandReason:(int)arg3;
- (void)lockShownOnScreen;
- (void)loginByMobileDevice:(id)arg1 withCommandReason:(int)arg2;
@property(retain, nonatomic) LoginLogoutExecution *loginLogoutCommands; // @synthesize loginLogoutCommands=_loginLogoutCommands;
- (void)loginLogoutCommands:(id)arg1 canNotLoginWithPassword:(id)arg2;
- (void)loginLogoutCommands:(id)arg1 didUpdateState:(int)arg2;
- (void)loginLogoutCommandsCommandFailed:(id)arg1;
- (void)loginLogoutCommandsDidInsertPassword:(id)arg1;
@property(retain, nonatomic) NSTimer *loginSafetyTimer; // @synthesize loginSafetyTimer=_loginSafetyTimer;
- (void)loginSafetyTimerTriggered;
@property(retain, nonatomic) NSTimer *logoutSafetyTimer; // @synthesize logoutSafetyTimer=_logoutSafetyTimer;
- (void)logoutSafetyTimerTriggered;
- (void)registerForNotifications;
@property(retain, nonatomic) NSTimer *safetyExecutionTimer; // @synthesize safetyExecutionTimer=_safetyExecutionTimer;
- (void)safetyExecutionTimerTriggered:(id)arg1;
- (void)setCommandToWaitInQueue:(id)arg1;
@property(retain, nonatomic) NSTimer *timerToCheckIfLoginSucceded; // @synthesize timerToCheckIfLoginSucceded=_timerToCheckIfLoginSucceded;
- (BOOL)shouldExecuteCommand:(id)arg1;
- (BOOL)shouldExecuteCommandimmediatelly;
- (void)startLoginCheckTimer;
- (void)startLoginSafetyTimer;
- (void)startLogoutSafetyTimer;
- (void)startSafetyExecututionTimer;
- (void)userHasLoggedIn;
- (void)userHasLoggedInByRemoteMobileDevice;
- (void)userHasLoggedInByTypingPassword;
- (void)userHasLoggedOut;
- (void)userHasLoggedOutByRemoteMobileDevice;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

