//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LoginItemsManager : NSObject
{
    BOOL _lastKnownIsLauncOnStartup;
}

+ (id)shared;
- (void)addAppToLoginItems;
- (void)didAddAppToLoginItems:(BOOL)arg1;
- (id)init;
- (BOOL)isLaunchAtStartup;
- (struct OpaqueLSSharedFileListItemRef *)itemRefInLoginItems;
@property(nonatomic) BOOL lastKnownIsLauncOnStartup; // @synthesize lastKnownIsLauncOnStartup=_lastKnownIsLauncOnStartup;
- (void)loginItemsChanged;
- (void)refreshLaunchAtStartup;
- (void)removeAppFromLoginItems;
- (void)setLaunchOnStartupOnVeryFirstLaunch;
- (void)setup;
- (void)startTrackingLoginItems;
- (void)stopTrackingLoginItems;
- (void)toggleLaunchAtStartup;
- (void)toggleLaunchAtStartupWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateLastKnownState;

@end

