//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp, NSMutableDictionary;

@interface LoginConfirmer : NSObject
{
    EventTimestamp *_checkEvent;
    NSMutableDictionary *_dictOfLoginCounts;
}

- (void).cxx_destruct;
- (void)addIdentifierIfItDoesntExist:(id)arg1;
@property(retain, nonatomic) EventTimestamp *checkEvent; // @synthesize checkEvent=_checkEvent;
@property(retain, nonatomic) NSMutableDictionary *dictOfLoginCounts; // @synthesize dictOfLoginCounts=_dictOfLoginCounts;
- (id)init;
- (BOOL)isCommandCheckerActiveForIdentifier:(id)arg1;
- (long long)numberOfChecksNeeded;
- (void)resetExecuteCommandCheckerForAllIdentifiers;
- (void)resetExecuteCommandCheckerForIdentifier:(id)arg1;
- (double)secondsPassesSinceLastCheck;
- (BOOL)shouldExecuteCommandAfterEventForIdentifier:(id)arg1;

@end

