//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface LogoutOnDIsconnectManager : NSObject
{
    id <LogoutOnDIsconnectManagerDelegate> _delegate;
    NSTimer *_logoutOnDisconnectTimer;
}

- (void).cxx_destruct;
- (void)cancelLogoutOnDisconnectProces;
@property(nonatomic) __weak id <LogoutOnDIsconnectManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTimer *logoutOnDisconnectTimer; // @synthesize logoutOnDisconnectTimer=_logoutOnDisconnectTimer;
- (void)logoutOnDisconnectTimerTriggered:(id)arg1;
- (void)startLogoutOnDisconnectProcess;

@end

