//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface LogoutExecution : NSObject
{
    EventTimestamp *_logoutTimestamp;
}

+ (id)shared;
- (void).cxx_destruct;
- (void)executeSleep;
- (id)init;
@property(retain, nonatomic) EventTimestamp *logoutTimestamp; // @synthesize logoutTimestamp=_logoutTimestamp;
- (double)secondsSinceLastSleepCommandExecution;

@end

