//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MacClipboardManager : NSObject
{
}

+ (BOOL)clipboardHasString;
+ (id)copyFromClipboard;
+ (BOOL)pasteToClipboard:(id)arg1;
- (void)clipboardUpdated;
- (void)dealloc;
- (void)registerForClipboardUpdates;

@end

