//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface MacDisplayControl : NSObject
{
    BOOL _allScreensTurnedOff;
    BOOL _didLockAtLeastOnce;
    BOOL _lockOnScreenShownAtLeastOnce;
    BOOL _lockOnScreenShownNotificationState;
    BOOL _lockOnScreenShownScreensaverState;
    BOOL _screensaverIsShown;
    BOOL _externalMonitorPluggedIn;
    BOOL _macIsCurrentlySleeping;
    NSNumber *_mainScreenID;
}

+ (id)shared;
- (void).cxx_destruct;
@property(nonatomic) BOOL allScreensTurnedOff; // @synthesize allScreensTurnedOff=_allScreensTurnedOff;
- (void)checkIfDeviceLockedAndLockOnScreenShown;
- (void)checkIfMainScreenChanged;
- (void)checkIfUserLoggedInAndActive;
- (void)checkLockOnScreenShownOverScreensaver;
- (void)dealloc;
@property(nonatomic) BOOL didLockAtLeastOnce; // @synthesize didLockAtLeastOnce=_didLockAtLeastOnce;
- (BOOL)didNotShowLockScreenAfterLocking;
@property(nonatomic) BOOL externalMonitorPluggedIn; // @synthesize externalMonitorPluggedIn=_externalMonitorPluggedIn;
- (id)focusScreen;
- (id)focusScreenNumber;
- (BOOL)hasBuiltInDisplay;
- (BOOL)hasExternalDisplay;
- (BOOL)hasExternalScreen;
- (BOOL)ifAllScreensTurnedOff;
- (BOOL)ifLockOnScreenShown;
- (BOOL)ifLockOnScreenShownAndDeviceLocked;
- (BOOL)ifScreenIsLockedOrScreensaverShown;
- (BOOL)ifScreenSaverPresent;
- (BOOL)ifUserLoggedInAndActive;
- (id)init;
- (BOOL)laptopLidIsDownAndNoExternalMonitor;
@property(nonatomic) BOOL lockOnScreenShownAtLeastOnce; // @synthesize lockOnScreenShownAtLeastOnce=_lockOnScreenShownAtLeastOnce;
@property(nonatomic) BOOL lockOnScreenShownNotificationState; // @synthesize lockOnScreenShownNotificationState=_lockOnScreenShownNotificationState;
- (BOOL)lockOnScreenShownOverScreensaver;
@property(nonatomic) BOOL lockOnScreenShownScreensaverState; // @synthesize lockOnScreenShownScreensaverState=_lockOnScreenShownScreensaverState;
- (void)lockUIIsHidden;
- (void)lockUIIsHiddenAfterDelay;
- (void)lockUIIsShown;
- (void)lockUIIsShownAfterDelay;
@property(nonatomic) BOOL macIsCurrentlySleeping; // @synthesize macIsCurrentlySleeping=_macIsCurrentlySleeping;
- (BOOL)macIsSleeping;
- (id)mainNumber:(id)arg1;
@property(retain, nonatomic) NSNumber *mainScreenID; // @synthesize mainScreenID=_mainScreenID;
- (id)mainScreenNumber;
- (long long)numberOfScreensAttached;
- (void)resetDidShowLockOnScreenAfterLogout;
- (void)screenHasLocked;
- (void)screenHasLockedAfterDelay;
- (void)screenHasUnlocked;
- (void)screenHasUnlockedAfterDelay;
- (void)screenNumberChanged;
- (void)screenSaverLaunched;
- (void)screenSaverLaunchedAfterDelay;
- (void)screenSaverStarted;
- (void)screenSaverStartedAfterDelay;
- (void)screenSaverStoped;
- (void)screenSaverStopedAfterDelay;
- (void)screenTurnedOff;
- (void)screenTurnedOffAfterDelay;
- (void)screenTurnedOn;
- (void)screenTurnedOnAfterDelay;
@property(nonatomic) BOOL screensaverIsShown; // @synthesize screensaverIsShown=_screensaverIsShown;
- (void)setMacIsCurrentlyNotSleeping;
- (void)setMacIsCurrentlySleeping;
- (void)startMonitoringExternalDisplays;
- (void)startTrackingDisplayChanges;
- (void)stopTrackingDisplayChanges;

@end

