//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "InfoViewController.h"

@class NSImageView;

@interface MacPhoneDeviceViewController : InfoViewController
{
    NSImageView *_secondaryImage;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSImageView *secondaryImage; // @synthesize secondaryImage=_secondaryImage;
- (void)viewDidLoad;

@end

