//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSTextField;

@interface MacSleepScreenTutorialStepViewController : BaseViewController
{
    id <MacSleepScreenTutorialStepViewControllerDelegate> _delegate;
    NSTextField *_titleLabel;
    NSTextField *_topLabel;
    NSTextField *_topLabel2;
    NSTextField *_labelYesNo;
    NSTextField *_labelTouchId;
    NSTextField *_labelKnock;
    NSTextField *_bottomLabel;
    NSTextField *_footerLabel;
    NSTextField *_doubleKnockDescriptionLabel;
    NSTextField *_proVersionFooter;
    NSButton *_radioYesNo;
    NSButton *_radioTouchId;
    NSButton *_radioKnockKnock;
    NSButton *_sleepButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTextField *bottomLabel; // @synthesize bottomLabel=_bottomLabel;
@property(nonatomic) __weak id <MacSleepScreenTutorialStepViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTextField *doubleKnockDescriptionLabel; // @synthesize doubleKnockDescriptionLabel=_doubleKnockDescriptionLabel;
@property(retain, nonatomic) NSTextField *footerLabel; // @synthesize footerLabel=_footerLabel;
@property(retain, nonatomic) NSTextField *labelKnock; // @synthesize labelKnock=_labelKnock;
@property(retain, nonatomic) NSTextField *labelTouchId; // @synthesize labelTouchId=_labelTouchId;
@property(retain, nonatomic) NSTextField *labelYesNo; // @synthesize labelYesNo=_labelYesNo;
@property(retain, nonatomic) NSTextField *proVersionFooter; // @synthesize proVersionFooter=_proVersionFooter;
- (void)radioButtonToggled:(id)arg1;
@property(retain, nonatomic) NSButton *radioKnockKnock; // @synthesize radioKnockKnock=_radioKnockKnock;
@property(retain, nonatomic) NSButton *radioTouchId; // @synthesize radioTouchId=_radioTouchId;
@property(retain, nonatomic) NSButton *radioYesNo; // @synthesize radioYesNo=_radioYesNo;
@property(retain, nonatomic) NSButton *sleepButton; // @synthesize sleepButton=_sleepButton;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSTextField *topLabel2; // @synthesize topLabel2=_topLabel2;
@property(retain, nonatomic) NSTextField *topLabel; // @synthesize topLabel=_topLabel;
- (void)sleepMacToggled:(id)arg1;
- (void)updateStrings;
- (void)updateViewForNewSettings;
- (void)viewDidLoad;

@end

