//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSImageView, NSTextField, NSView;

@interface MacSleepScreenConnectToiPhone : BaseViewController
{
    int _connectTutorialType;
    id <MacSleepScreenConnectToiPhoneDelegate> _delegate;
    NSTextField *_titleLabel;
    NSTextField *_connectLabel;
    NSImageView *_mainImage;
    NSButton *_button;
    NSView *_bottomSeparatorView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSView *bottomSeparatorView; // @synthesize bottomSeparatorView=_bottomSeparatorView;
@property(nonatomic) __weak NSButton *button; // @synthesize button=_button;
- (void)buttonToggled:(id)arg1;
@property(nonatomic) __weak NSTextField *connectLabel; // @synthesize connectLabel=_connectLabel;
@property(nonatomic) int connectTutorialType; // @synthesize connectTutorialType=_connectTutorialType;
@property(nonatomic) __weak id <MacSleepScreenConnectToiPhoneDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSImageView *mainImage; // @synthesize mainImage=_mainImage;
@property(nonatomic) __weak NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)updateStrings;
- (void)updateViewForNewBluetoothState;
- (void)viewDidLoad;

@end

