//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSTextField;

@interface MacSleepScreenTurnNearLockOff : BaseViewController
{
    id <MacSleepScreenTurnNearLockOffDelegate> _delegate;
    NSTextField *_titleLabel;
    NSTextField *_topLabel;
    NSTextField *_nearLockLabel;
    NSTextField *_safeWifilabel;
    NSTextField *_footerLabel;
    NSButton *_nearLockButton;
    NSButton *_safeWifiButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <MacSleepScreenTurnNearLockOffDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTextField *footerLabel; // @synthesize footerLabel=_footerLabel;
@property(retain, nonatomic) NSButton *nearLockButton; // @synthesize nearLockButton=_nearLockButton;
@property(retain, nonatomic) NSTextField *nearLockLabel; // @synthesize nearLockLabel=_nearLockLabel;
- (void)nearLockOffToggled:(id)arg1;
@property(retain, nonatomic) NSButton *safeWifiButton; // @synthesize safeWifiButton=_safeWifiButton;
- (void)safeWifiOffToggled:(id)arg1;
@property(retain, nonatomic) NSTextField *safeWifilabel; // @synthesize safeWifilabel=_safeWifilabel;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) NSTextField *topLabel; // @synthesize topLabel=_topLabel;
- (void)updateStrings;
- (void)updateViewForNewSettings;
- (void)viewDidLoad;

@end

