//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSTextField;

@interface MacSleepScreenFirstViewController : BaseViewController
{
    id <MacSleepScreenFirstViewControllerDelegate> _delegate;
    NSButton *_nextButton;
    NSTextField *_titleLabel;
    NSTextField *_firstLabel;
    NSTextField *_secondLabel;
    NSTextField *_notificationText;
    NSTextField *_notificationUnlock;
}

- (void).cxx_destruct;
- (void)buttonToggled:(id)arg1;
@property(nonatomic) __weak id <MacSleepScreenFirstViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTextField *firstLabel; // @synthesize firstLabel=_firstLabel;
@property(retain, nonatomic) NSButton *nextButton; // @synthesize nextButton=_nextButton;
@property(retain, nonatomic) NSTextField *notificationText; // @synthesize notificationText=_notificationText;
@property(retain, nonatomic) NSTextField *notificationUnlock; // @synthesize notificationUnlock=_notificationUnlock;
@property(retain, nonatomic) NSTextField *secondLabel; // @synthesize secondLabel=_secondLabel;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)updateStrings;
- (void)viewDidLoad;

@end

