//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MainMenuBarController, MobileDevice;

@protocol MainMenuBarControllerDelegate <NSObject>
- (void)mainMenuBarController:(MainMenuBarController *)arg1 didSelectOption:(int)arg2 forMobileDevice:(MobileDevice *)arg3;
@end

