//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, SettingsDetailViewController, SettingsMasterViewController, WAYSourceListWindow;

@interface MasterDetailNavigationManager : NSObject
{
    WAYSourceListWindow *_splitWindow;
    SettingsMasterViewController *_master;
    SettingsDetailViewController *_detail;
    NSMutableArray *_viewModelStack;
}

- (void).cxx_destruct;
- (void)addContentViewForDetailView:(id)arg1 source:(int)arg2;
- (void)addContentViewForDetailView:(id)arg1 source:(int)arg2 popToRoot:(BOOL)arg3;
- (int)animationDirectionForList:(id)arg1;
- (int)animationDirectionForSource:(int)arg1;
- (void)backToggled;
- (BOOL)containsDetailView:(id)arg1;
@property(retain, nonatomic) SettingsDetailViewController *detail; // @synthesize detail=_detail;
@property(retain, nonatomic) SettingsMasterViewController *master; // @synthesize master=_master;
- (void)pop;
- (void)popToRootAnimated:(BOOL)arg1;
- (void)popToRootView;
- (void)popViewModel;
- (void)popViewModelAnimated:(BOOL)arg1;
- (void)presentViewModel:(id)arg1 animationDirection:(int)arg2;
- (void)pushAndPopIfNeeded:(id)arg1 animted:(BOOL)arg2;
- (void)pushViewModel:(id)arg1;
- (void)pushViewModel:(id)arg1 animated:(BOOL)arg2;
- (void)replaceTopViewModel:(id)arg1;
- (void)selectRowId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setFooterText:(id)arg1;
- (void)setInitialListViewModel:(id)arg1;
@property(retain, nonatomic) WAYSourceListWindow *splitWindow; // @synthesize splitWindow=_splitWindow;
@property(retain, nonatomic) NSMutableArray *viewModelStack; // @synthesize viewModelStack=_viewModelStack;
- (void)setup:(id)arg1;
- (void)showDetailController:(id)arg1 source:(int)arg2;
- (void)showDetailList:(id)arg1 source:(int)arg2;
- (void)showDetailListBase:(id)arg1 source:(int)arg2;
- (void)showRootViewModel:(id)arg1;
- (BOOL)stackHasOnlyRootController;
- (void)updateBackButton;
- (void)updateTitle:(id)arg1;

@end

