//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AdvancedMenuManager, AllCellsMenuManager, ClipboardMenuManager, DevicesMenuManager, HelpMenuManager, MusicMenuManager, PhotosAndHistoryManager, ProVersionMenuManager, SetupMenuManager, ShareMenuManager, TranslationHelpMenuManager, UpdatesMenuManager;

@interface MenuManagerFactory : NSObject
{
    PhotosAndHistoryManager *_photosAndHistoryManager;
    HelpMenuManager *_helpMenuManager;
    AdvancedMenuManager *_advancedMenuManager;
    MusicMenuManager *_musicMenuManager;
    SetupMenuManager *_setupMenuManager;
    ClipboardMenuManager *_clipboardManager;
    UpdatesMenuManager *_updatesMenuManager;
    ShareMenuManager *_shareMenuManager;
    AllCellsMenuManager *_allCellsMenuManager;
    ProVersionMenuManager *_proMenuManager;
    DevicesMenuManager *_devicesMenuManager;
    TranslationHelpMenuManager *_translationMenuManager;
    id <NavigationDelegate> _delegate;
}

- (void).cxx_destruct;
- (id)advancedMenu;
@property(retain, nonatomic) AdvancedMenuManager *advancedMenuManager; // @synthesize advancedMenuManager=_advancedMenuManager;
@property(retain, nonatomic) AllCellsMenuManager *allCellsMenuManager; // @synthesize allCellsMenuManager=_allCellsMenuManager;
@property(retain, nonatomic) ClipboardMenuManager *clipboardManager; // @synthesize clipboardManager=_clipboardManager;
- (id)clipboardMenu;
@property(nonatomic) __weak id <NavigationDelegate> delegate; // @synthesize delegate=_delegate;
- (id)devicesMenuCell;
@property(retain, nonatomic) DevicesMenuManager *devicesMenuManager; // @synthesize devicesMenuManager=_devicesMenuManager;
- (id)generateListModel;
- (id)helpMenu;
@property(retain, nonatomic) HelpMenuManager *helpMenuManager; // @synthesize helpMenuManager=_helpMenuManager;
- (id)initWithDelegate:(id)arg1;
- (id)musicMenu;
@property(retain, nonatomic) MusicMenuManager *musicMenuManager; // @synthesize musicMenuManager=_musicMenuManager;
@property(retain, nonatomic) PhotosAndHistoryManager *photosAndHistoryManager; // @synthesize photosAndHistoryManager=_photosAndHistoryManager;
- (id)photosAndHistoryMenu;
@property(retain, nonatomic) ProVersionMenuManager *proMenuManager; // @synthesize proMenuManager=_proMenuManager;
@property(retain, nonatomic) SetupMenuManager *setupMenuManager; // @synthesize setupMenuManager=_setupMenuManager;
@property(retain, nonatomic) ShareMenuManager *shareMenuManager; // @synthesize shareMenuManager=_shareMenuManager;
@property(retain, nonatomic) TranslationHelpMenuManager *translationMenuManager; // @synthesize translationMenuManager=_translationMenuManager;
@property(retain, nonatomic) UpdatesMenuManager *updatesMenuManager; // @synthesize updatesMenuManager=_updatesMenuManager;
- (id)setupMenCell;
- (id)shareMenu;
- (void)showDetailList:(id)arg1 source:(int)arg2;
- (void)showWifiUnlockOptionForSource:(int)arg1;
- (id)updatesMenu;
- (id)wifiUnlockMenu;

@end

