//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class StatusItemController;

@protocol MenubarControllerDelegate <NSObject>
- (void)menubarControllerDidToggleMenuItem:(StatusItemController *)arg1;
- (void)menubarControllerDidToggleMenuItemWithRightClick:(StatusItemController *)arg1;
@end

