//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface Message : NSObject
{
    NSString *requestType;
    NSNumber *request;
    id payload;
}

- (void).cxx_destruct;
- (id)initWithRequest:(int)arg1;
@property(retain, nonatomic) id payload; // @synthesize payload;
@property(retain, nonatomic) NSNumber *request; // @synthesize request;
@property(retain, nonatomic) NSString *requestType; // @synthesize requestType;

@end

