//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MessageEncoderDecoder : NSObject
{
    NSString *_separator;
}

+ (id)decodeObject:(id)arg1 forClass:(Class)arg2;
+ (id)encodeObject:(id)arg1;
- (void).cxx_destruct;
- (id)decodeMessage:(id)arg1;
- (id)encodeMessage:(id)arg1;
- (id)init;
- (id)payloadObjectForString:(id)arg1 forRequest:(int)arg2;
@property(retain, nonatomic) NSString *separator; // @synthesize separator=_separator;

@end

