//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LoginTrackerFactory;

@interface MigrationManager : NSObject
{
    LoginTrackerFactory *_trackFactory;
}

- (void).cxx_destruct;
- (id)init;
- (void)migrateIfNeeded;
- (void)migrateTrackingFileIfNeeded;
- (void)parseTrackingFileToApplicationData;
@property(retain, nonatomic) LoginTrackerFactory *trackFactory; // @synthesize trackFactory=_trackFactory;
- (BOOL)shouldParseLogFileToApplicationData;

@end

