//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class DeviceUser, MobileDeviceTrackInfo, NSNumber, NSString, OSXPreferences, PairingInfo, iOSPreferences;

@interface MobileSettings : NSObject <NSCoding>
{
    NSString *_unId;
    DeviceUser *_registeredDeviceUser;
    MobileDeviceTrackInfo *_mobileDeviceTrackInfo;
    PairingInfo *_pairingInfo;
    NSNumber *_distanceFromDevice;
    OSXPreferences *_OSXSettings;
    iOSPreferences *_iOSSettings;
}

- (void).cxx_destruct;
@property(retain, nonatomic) OSXPreferences *OSXSettings; // @synthesize OSXSettings=_OSXSettings;
- (id)calculate:(int)arg1;
- (int)currentBatteryLevel;
- (long long)currentBatteryPercent;
- (id)currentDistanceString;
- (id)customCopy;
- (void)decodeWithCoder:(id)arg1;
- (id)distanceDescriptionString;
@property(retain, nonatomic) NSNumber *distanceFromDevice; // @synthesize distanceFromDevice=_distanceFromDevice;
- (id)distanceToLockString;
- (void)encodeWithCoder:(id)arg1;
@property(retain, nonatomic) iOSPreferences *iOSSettings; // @synthesize iOSSettings=_iOSSettings;
- (id)initWithCoder:(id)arg1;
- (id)initWithUnId:(id)arg1;
- (id)initWithUnId:(id)arg1 andDeviceUser:(id)arg2;
- (BOOL)isInsideNearLockRadius;
- (BOOL)isInsideNearLockRadiusWithTreshold;
- (BOOL)isOutsideNearLockRadius;
- (BOOL)isOutsideNearLockRadiusWithTreshold;
- (BOOL)isPendingAnyLoginConfirmation;
- (BOOL)isPendingPasswordShownLoginConfirmation;
- (BOOL)isPendingRSSILoginConfirmation;
- (BOOL)isProVersionOrInForeground;
- (double)lockUnlockDistance;
- (float)loginLogoutTreshold;
@property(retain, nonatomic) MobileDeviceTrackInfo *mobileDeviceTrackInfo; // @synthesize mobileDeviceTrackInfo=_mobileDeviceTrackInfo;
- (int)osXSystemVersion;
@property(retain, nonatomic) PairingInfo *pairingInfo; // @synthesize pairingInfo=_pairingInfo;
@property(retain, nonatomic) DeviceUser *registeredDeviceUser; // @synthesize registeredDeviceUser=_registeredDeviceUser;
- (id)rssiPrettyPrint;
- (void)setDefaultValues;
@property(retain, nonatomic) NSString *unId; // @synthesize unId=_unId;
- (BOOL)shouldConstantlyTrackDeviceDistance;
- (BOOL)shouldKnockToLogin;
- (BOOL)shouldShowBatteryWarning;
- (BOOL)shouldShowLockOnScreen;
- (BOOL)shouldTrackMobileDeviceOrTrackingTemporarilyDisabled;
- (BOOL)shouldUpdateRemoteRssiForCurrentApplicationState;
- (void)updateLastConnectionTimestamp;
- (void)updateMobileSettingsWithLocalSettings;
- (void)updateModelUpdateForNewVersion;
- (void)updateNearLock:(BOOL)arg1 responsibleDevice:(int)arg2;

@end

