//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class EventTimestamp, NSNumber;

@interface MobileSettingsLocal : NSObject <NSCoding>
{
    NSNumber *_nearLockLocationNumber;
    NSNumber *_disconnectTimestampNumber;
    NSNumber *_lastDoubleCheckTimestampNumber;
    EventTimestamp *_disconnectTimestamp;
    EventTimestamp *_lastDoubleCheckTimestamp;
}

- (void).cxx_destruct;
- (void)decodeWithCoder:(id)arg1;
- (void)deviceDidDisconnect;
- (void)deviceIsDoubleChecking;
@property(retain, nonatomic) EventTimestamp *disconnectTimestamp; // @synthesize disconnectTimestamp=_disconnectTimestamp;
@property(retain, nonatomic) NSNumber *disconnectTimestampNumber; // @synthesize disconnectTimestampNumber=_disconnectTimestampNumber;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) EventTimestamp *lastDoubleCheckTimestamp; // @synthesize lastDoubleCheckTimestamp=_lastDoubleCheckTimestamp;
@property(retain, nonatomic) NSNumber *lastDoubleCheckTimestampNumber; // @synthesize lastDoubleCheckTimestampNumber=_lastDoubleCheckTimestampNumber;
@property(nonatomic) int nearLockConfirmedLocation;
@property(retain, nonatomic) NSNumber *nearLockLocationNumber; // @synthesize nearLockLocationNumber=_nearLockLocationNumber;
- (double)secondSinceLastDisconnect;
- (double)secondSinceLastDoubleCheck;

@end

