//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class MobileDeviceConnectionInfo, MobileDeviceInfo, NSString;


@interface MobileDevice : NSObject <NSCoding>
{
    NSString *unId;
    MobileDeviceInfo *mobileDeviceInfo;
    MobileDeviceConnectionInfo *mobileDeviceConnectionInfo;
}

- (void).cxx_destruct;
- (void)decodeWithCoder:(id)arg1;
- (id)distanceStringWithUserActiveIndication:(BOOL)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithUnId:(id)arg1;
@property(retain, nonatomic) MobileDeviceConnectionInfo *mobileDeviceConnectionInfo; // @synthesize mobileDeviceConnectionInfo;
@property(retain, nonatomic) MobileDeviceInfo *mobileDeviceInfo; // @synthesize mobileDeviceInfo;
@property(retain, nonatomic) NSString *unId; // @synthesize unId;
- (BOOL)shouldConfirmLoginOnMobileDeviceWhenEnteredForeground;
- (BOOL)shouldShowUserActiveIndication;
- (id)userActiveIndicationString;

@end

