//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSNumber;

@interface MobileDeviceTrackInfo : NSObject <NSCoding>
{
    NSNumber *_shouldTrackMobileDevice;
    NSNumber *_proxLockTemporaryDisabledBecauseLogout;
    NSNumber *_proxLockTemporaryDisabledBecauseLogin;
    NSNumber *_distanceToLogin;
    NSNumber *_deviceResponsibleForLastChange;
}

- (void).cxx_destruct;
- (id)copyCustom;
- (void)decodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSNumber *deviceResponsibleForLastChange; // @synthesize deviceResponsibleForLastChange=_deviceResponsibleForLastChange;
@property(retain, nonatomic) NSNumber *distanceToLogin; // @synthesize distanceToLogin=_distanceToLogin;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDefaultSettings;
- (BOOL)isSameAs:(id)arg1;
- (BOOL)isTemporaryDisabled;
@property(retain, nonatomic) NSNumber *proxLockTemporaryDisabledBecauseLogin; // @synthesize proxLockTemporaryDisabledBecauseLogin=_proxLockTemporaryDisabledBecauseLogin;
@property(retain, nonatomic) NSNumber *proxLockTemporaryDisabledBecauseLogout; // @synthesize proxLockTemporaryDisabledBecauseLogout=_proxLockTemporaryDisabledBecauseLogout;
- (void)resetTemporaryDisabledFlags;
- (void)setDefaultSettings;
@property(retain, nonatomic) NSNumber *shouldTrackMobileDevice; // @synthesize shouldTrackMobileDevice=_shouldTrackMobileDevice;

@end

