//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface MotionTracking : NSObject
{
    EventTimestamp *_eventTimestamp;
}

+ (id)shared;
- (void).cxx_destruct;
@property(retain, nonatomic) EventTimestamp *eventTimestamp; // @synthesize eventTimestamp=_eventTimestamp;
- (id)init;
- (void)motionDetected;
- (double)secondsPassesSinceLastMotion;

@end

