//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearLockListViewCell.h"

@class BaseEntry, NSImageView;

@interface MyListViewCell : NearLockListViewCell
{
    id <MyListViewCellDelegate> _delegate;
    BaseEntry *_failedLoginEntry;
    NSImageView *_imageView;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <MyListViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteToggled:(id)arg1;
@property(retain, nonatomic) BaseEntry *failedLoginEntry; // @synthesize failedLoginEntry=_failedLoginEntry;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
- (void)prepareForReuse;
- (void)shareToggled:(id)arg1;
- (void)updateView;

@end

