//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScrollView.h"

@interface MyScrollView : NSScrollView
{
    struct CGPoint _lastPoint;
}

@property(nonatomic) struct CGPoint lastPoint; // @synthesize lastPoint=_lastPoint;
- (void)scrollToPoint:(struct CGPoint)arg1 animated:(BOOL)arg2;
- (void)scrollWheel:(id)arg1;

@end

