//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PXListView.h"

@interface NearLockListView : PXListView
{
    BOOL _didInitalizeView;
    unsigned long long _previousSelection;
}

@property(nonatomic) BOOL didInitalizeView; // @synthesize didInitalizeView=_didInitalizeView;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (void)initalize;
@property(nonatomic) unsigned long long previousSelection; // @synthesize previousSelection=_previousSelection;
- (void)selectRowIndexes:(id)arg1 byExtendingSelection:(BOOL)arg2;
- (BOOL)selectionChangeDirectionisUpward;
- (void)setupDefaultProperties;

@end

