//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface NearLockEvent : NSObject
{
    EventTimestamp *_nearLockLoginTimestamp;
    EventTimestamp *_nearLockLogoutTimestamp;
}

+ (id)shared;
- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) EventTimestamp *nearLockLoginTimestamp; // @synthesize nearLockLoginTimestamp=_nearLockLoginTimestamp;
- (void)nearLockLoginTrigered;
@property(retain, nonatomic) EventTimestamp *nearLockLogoutTimestamp; // @synthesize nearLockLogoutTimestamp=_nearLockLogoutTimestamp;
- (void)nearLockLogoutTrigered;
- (double)timeSinceAnyEvent;
- (double)timeSinceLastLogin;
- (double)timeSinceLastLogout;

@end

