//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLWindowController.h"

#import "CNGridViewDataSource.h"
#import "CNGridViewDelegate.h"
#import "NSSharingServiceDelegate.h"
#import "NSSharingServicePickerDelegate.h"
#import "PopoverManagerDelegate.h"

@class BaseEntry, CNGridView, CNGridViewItemLayout, NSArray, NSButton, NSImageView, NSString, NSTextField, PopoverManager;

@interface NearLockCollectionWindow : NLWindowController <CNGridViewDataSource, CNGridViewDelegate, NSSharingServicePickerDelegate, NSSharingServiceDelegate, PopoverManagerDelegate>
{
    BOOL _showManualSnapshots;
    BOOL _showLoginEntries;
    BOOL _showFailedLoginAttemptEntries;
    BOOL _selectFirstItemAfterReloadFinished;
    BOOL _gridDidLoadAtLeastOnce;
    id <NearLockCollectionWindowDelegate> _delegate;
    CNGridView *_gridView;
    CNGridViewItemLayout *_defaultLayout;
    CNGridViewItemLayout *_hoverLayout;
    CNGridViewItemLayout *_selectionLayout;
    NSArray *_listViewArray;
    long long _selectedIndexPath;
    NSButton *_trashButton;
    NSButton *_shareButton;
    NSButton *_downloadButton;
    NSButton *_deleteAllButton;
    NSButton *_notificationButton;
    NSTextField *_notificationLable;
    NSTextField *_infoLabel;
    NSImageView *_infoImageView;
    NSImageView *_mainImageView;
    NSImageView *_fullScreenImage;
    BaseEntry *_failedLoginEntryToSelect;
    BaseEntry *_selectedEntry;
    PopoverManager *_popoverManager;
}

- (void).cxx_destruct;
@property(retain, nonatomic) CNGridViewItemLayout *defaultLayout; // @synthesize defaultLayout=_defaultLayout;
@property(nonatomic) __weak id <NearLockCollectionWindowDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSButton *deleteAllButton; // @synthesize deleteAllButton=_deleteAllButton;
- (void)deleteAllShownEntries;
- (void)deleteAllToggled:(id)arg1;
- (void)deleteSelectedIndexPath;
- (void)deleteToggled:(id)arg1;
@property(retain, nonatomic) NSButton *downloadButton; // @synthesize downloadButton=_downloadButton;
- (id)entriesWithMugShots:(id)arg1;
@property(retain, nonatomic) BaseEntry *failedLoginEntryToSelect; // @synthesize failedLoginEntryToSelect=_failedLoginEntryToSelect;
@property(retain, nonatomic) NSImageView *fullScreenImage; // @synthesize fullScreenImage=_fullScreenImage;
- (id)generateMughshotForEntry:(id)arg1;
@property(nonatomic) BOOL gridDidLoadAtLeastOnce; // @synthesize gridDidLoadAtLeastOnce=_gridDidLoadAtLeastOnce;
@property(retain, nonatomic) CNGridView *gridView; // @synthesize gridView=_gridView;
- (void)gridView:(id)arg1 didActivateContextMenuWithIndexes:(id)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didClickItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didDeselectItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didDoubleClickItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (void)gridView:(id)arg1 didSelectItemAtIndex:(unsigned long long)arg2 inSection:(unsigned long long)arg3;
- (id)gridView:(id)arg1 itemAtIndex:(long long)arg2 inSection:(long long)arg3;
- (unsigned long long)gridView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)gridViewDidFinishReloadingVisibleItems:(id)arg1;
- (void)hideGrid:(BOOL)arg1;
@property(retain, nonatomic) CNGridViewItemLayout *hoverLayout; // @synthesize hoverLayout=_hoverLayout;
- (id)imageForNoPicture;
- (long long)indexForFailedLoginEntry:(id)arg1;
@property(retain, nonatomic) NSImageView *infoImageView; // @synthesize infoImageView=_infoImageView;
@property(retain, nonatomic) NSTextField *infoLabel; // @synthesize infoLabel=_infoLabel;
- (void)initalizePopoverModel;
@property(retain, nonatomic) NSArray *listViewArray; // @synthesize listViewArray=_listViewArray;
- (void)loadLayout;
- (id)localizedNoPictureText;
@property(retain, nonatomic) NSImageView *mainImageView; // @synthesize mainImageView=_mainImageView;
- (id)nonExistingImagePathInDocuments;
@property(retain, nonatomic) NSButton *notificationButton; // @synthesize notificationButton=_notificationButton;
@property(retain, nonatomic) NSTextField *notificationLable; // @synthesize notificationLable=_notificationLable;
- (void)notificationToggled:(id)arg1;
@property(retain, nonatomic) PopoverManager *popoverManager; // @synthesize popoverManager=_popoverManager;
- (void)popoverManager:(id)arg1 didSelectOption:(int)arg2;
- (void)reloadData;
- (void)reloadDatasourceAndView;
- (void)reloadDatasourceAndViewAndSelectItem;
- (void)reloadDatsourceWithCompletion:(CDUnknownBlockType)arg1;
- (void)saveToDocumentsToggled:(id)arg1;
- (void)selectFailedEntry;
@property(nonatomic) BOOL selectFirstItemAfterReloadFinished; // @synthesize selectFirstItemAfterReloadFinished=_selectFirstItemAfterReloadFinished;
- (void)selectLastSelectedItem;
@property(retain, nonatomic) BaseEntry *selectedEntry; // @synthesize selectedEntry=_selectedEntry;
@property(nonatomic) long long selectedIndexPath; // @synthesize selectedIndexPath=_selectedIndexPath;
@property(retain, nonatomic) CNGridViewItemLayout *selectionLayout; // @synthesize selectionLayout=_selectionLayout;
@property(retain, nonatomic) NSButton *shareButton; // @synthesize shareButton=_shareButton;
@property(nonatomic) BOOL showFailedLoginAttemptEntries; // @synthesize showFailedLoginAttemptEntries=_showFailedLoginAttemptEntries;
@property(nonatomic) BOOL showLoginEntries; // @synthesize showLoginEntries=_showLoginEntries;
@property(nonatomic) BOOL showManualSnapshots; // @synthesize showManualSnapshots=_showManualSnapshots;
@property(retain, nonatomic) NSButton *trashButton; // @synthesize trashButton=_trashButton;
- (void)setupGridViewLayout;
- (void)shareToggled:(id)arg1;
- (id)sharingService:(id)arg1 sourceWindowForShareItems:(id)arg2 sharingContentScope:(long long *)arg3;
- (id)sharingServicePicker:(id)arg1 delegateForSharingService:(id)arg2;
- (void)showNoItemsInGridView;
- (void)showWindowWithEntry:(id)arg1;
- (void)updatePopoverView;
- (void)updateViewForCurrentPopoverModel;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

