//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface NearLockIdleManager : NSObject
{
    EventTimestamp *_userDidNotLogoutBecauseUserActive;
}

+ (id)shared;
- (void).cxx_destruct;
- (id)init;
- (void)nearLockRefusedToLoginBecauseUserActive;
- (BOOL)nearLockRefusedToLoginRecentlyBecauseUserWasActive;
@property(retain, nonatomic) EventTimestamp *userDidNotLogoutBecauseUserActive; // @synthesize userDidNotLogoutBecauseUserActive=_userDidNotLogoutBecauseUserActive;
- (BOOL)userWasActiveInTheLastSeconds:(double)arg1;
- (BOOL)userWasRecentlyActive;
- (BOOL)userWasVeryRecentlyActive;

@end

