//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NearLockNotificationManager : NSObject
{
}

+ (id)createAndShowNativeNotificationWithText:(id)arg1 identifier:(id)arg2;
+ (void)hideNativeNotificationWithIdentifier:(id)arg1;
+ (void)hideNotification:(id)arg1;
+ (void)showNativeNotificationWithText:(id)arg1 identifier:(id)arg2 hideAfterDelay:(long long)arg3;
+ (void)showPersistantNativeNotificationWithText:(id)arg1 identifier:(id)arg2;

@end

