//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMenuItemManager.h"

@interface NearLockBaseItemManager : BaseMenuItemManager
{
    BOOL _notConnectedExpanded;
    BOOL _noPairedDevicesExpanded;
}

@property(nonatomic) BOOL noPairedDevicesExpanded; // @synthesize noPairedDevicesExpanded=_noPairedDevicesExpanded;
- (id)notConnected;
@property(nonatomic) BOOL notConnectedExpanded; // @synthesize notConnectedExpanded=_notConnectedExpanded;
- (id)notPairedDevices;

@end

