//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PXListViewCell.h"

@class ListCellViewModel, NSButton, NSImageView, NSTextField;

@interface NearLockListViewCell : PXListViewCell
{
    BOOL _isSelectionEnabled;
    BOOL _didLayoutSubviewsAtLeastOnce;
    NSImageView *_backgroundImage;
    NSImageView *_icon;
    NSImageView *_secondaryIcon;
    NSTextField *_titleLabel;
    NSTextField *_descriptionLabel;
    NSButton *_button1;
    NSButton *_button2;
    ListCellViewModel *_viewModel;
    CDUnknownBlockType _customActionProperty;
    CDUnknownBlockType _action2Property;
}

+ (Class)cellClass;
+ (double)cellHeight;
+ (id)nibName;
- (void).cxx_destruct;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsAttributeSettable:(id)arg1;
@property(copy) CDUnknownBlockType action2Property; // @synthesize action2Property=_action2Property;
@property(retain, nonatomic) NSImageView *backgroundImage; // @synthesize backgroundImage=_backgroundImage;
@property(retain, nonatomic) NSButton *button1; // @synthesize button1=_button1;
@property(retain, nonatomic) NSButton *button2; // @synthesize button2=_button2;
@property(copy) CDUnknownBlockType customActionProperty; // @synthesize customActionProperty=_customActionProperty;
@property(retain, nonatomic) NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(nonatomic) BOOL didLayoutSubviewsAtLeastOnce; // @synthesize didLayoutSubviewsAtLeastOnce=_didLayoutSubviewsAtLeastOnce;
- (void)didUpdateSelection;
- (void)drawRect:(struct CGRect)arg1;
@property(retain, nonatomic) NSImageView *icon; // @synthesize icon=_icon;
- (id)initWithReusableIdentifier:(id)arg1;
@property(nonatomic) BOOL isSelectionEnabled; // @synthesize isSelectionEnabled=_isSelectionEnabled;
- (void)layout;
- (void)layoutSubviews;
- (void)prepareForReuse;
@property(retain, nonatomic) NSImageView *secondaryIcon; // @synthesize secondaryIcon=_secondaryIcon;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) ListCellViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void)updateCellForCellViewModel:(id)arg1;
- (void)updateSelectionColor;

@end

