//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLWindowController.h"

@class NSButton, NSTextField, NSView, NearLockListView;

@interface NearLockListViewWindow : NLWindowController
{
    NearLockListView *_listView;
    NSTextField *_title;
    NSTextField *_bottomInfoTextField;
    NSButton *_bottomRightButton;
    NSButton *_bottomCenterButton;
    NSButton *_infoButton;
    NSView *_listViewBackgroundView;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSButton *bottomCenterButton; // @synthesize bottomCenterButton=_bottomCenterButton;
@property(retain, nonatomic) NSTextField *bottomInfoTextField; // @synthesize bottomInfoTextField=_bottomInfoTextField;
@property(nonatomic) __weak NSButton *bottomRightButton; // @synthesize bottomRightButton=_bottomRightButton;
- (void)didToggleButtonCenterButton:(id)arg1;
- (void)didToggleButtonRightButton:(id)arg1;
@property(nonatomic) __weak NSButton *infoButton; // @synthesize infoButton=_infoButton;
- (void)infoButtonToggled:(id)arg1;
@property(retain, nonatomic) NearLockListView *listView; // @synthesize listView=_listView;
@property(nonatomic) __weak NSView *listViewBackgroundView; // @synthesize listViewBackgroundView=_listViewBackgroundView;
- (id)nibName;
- (void)reloadDatasourceAndView:(CDUnknownBlockType)arg1;
- (void)reloadDatsourceWithCompletion:(CDUnknownBlockType)arg1;
- (void)setBottomCenterButtonTitle:(id)arg1;
- (void)setBottomRightButtonTitle:(id)arg1;
@property(retain, nonatomic) NSTextField *title; // @synthesize title=_title;
- (void)setTitle:(id)arg1 forButton:(id)arg2;
- (void)setUpListView;
- (void)showInfoButton:(BOOL)arg1;
- (void)windowDidLoad;

@end

