//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MasterDetailNavigationManager.h"

@interface NearLockMasterDetailNavManager : MasterDetailNavigationManager
{
}

- (void)pushDetailController:(id)arg1;
- (void)pushDetailList:(id)arg1;
- (void)showDetailController:(id)arg1 source:(int)arg2;
- (void)showDetailController:(id)arg1 title:(id)arg2 source:(int)arg3;
- (void)showDetailController:(id)arg1 title:(id)arg2 source:(int)arg3 popToRoot:(BOOL)arg4;
- (void)showDetailList:(id)arg1 source:(int)arg2;
- (void)showDetailList:(id)arg1 title:(id)arg2 source:(int)arg3;
- (void)showDetailList:(id)arg1 title:(id)arg2 source:(int)arg3 popToRoot:(BOOL)arg4;

@end

