//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SUUpdaterDelegate.h"

@class NSInvocation, NSString;

@interface NearLockUpdater : NSObject <SUUpdaterDelegate>
{
    BOOL _shouldAutomaticallyCheckForUpdates;
    BOOL _installAfterDownload;
    BOOL _checkingInForeground;
    int _updaterState;
    NSInvocation *_relaunchInvocation;
}

+ (id)shared;
- (void).cxx_destruct;
- (void)checkForUpdates:(id)arg1;
- (void)checkForUpdatesInBackground;
@property(nonatomic) BOOL checkingInForeground; // @synthesize checkingInForeground=_checkingInForeground;
- (id)init;
@property(nonatomic) BOOL installAfterDownload; // @synthesize installAfterDownload=_installAfterDownload;
- (void)relaunch:(id)arg1;
- (BOOL)relaunchIfPossible;
@property(retain, nonatomic) NSInvocation *relaunchInvocation; // @synthesize relaunchInvocation=_relaunchInvocation;
@property(nonatomic) BOOL shouldAutomaticallyCheckForUpdates; // @synthesize shouldAutomaticallyCheckForUpdates=_shouldAutomaticallyCheckForUpdates;
- (void)setUpFeedUrlString:(id)arg1;
@property(nonatomic) int updaterState; // @synthesize updaterState=_updaterState;
- (BOOL)updateInProgress;
- (void)updater:(id)arg1 didAbortWithError:(id)arg2;
- (void)updater:(id)arg1 didCancelInstallUpdateOnQuit:(id)arg2;
- (void)updater:(id)arg1 didFindValidUpdate:(id)arg2;
- (BOOL)updater:(id)arg1 shouldPostponeRelaunchForUpdate:(id)arg2 untilInvoking:(id)arg3;
- (void)updater:(id)arg1 willInstallUpdate:(id)arg2;
- (void)updater:(id)arg1 willInstallUpdateOnQuit:(id)arg2 immediateInstallationInvocation:(id)arg3;
- (void)updaterDidNotFindUpdate:(id)arg1;
- (BOOL)updaterMayCheckForUpdates:(id)arg1;
- (BOOL)updaterShouldRelaunchApplication:(id)arg1;
- (void)updaterWillRelaunchApplication:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

