//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@class NSColor;

@interface NLButton3 : NSButton
{
    BOOL _alwaysUseNibWidth;
    BOOL _didSetupView;
    double _initialWidth;
    double _edgeInsets;
    double _customCornerRadius;
    NSColor *_customTextColor;
    NSColor *_customBackgroundColor;
    double _nibWidth;
    struct CGPoint _nibCenter;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL alwaysUseNibWidth; // @synthesize alwaysUseNibWidth=_alwaysUseNibWidth;
- (void)awakeFromNib;
@property(retain, nonatomic) NSColor *customBackgroundColor; // @synthesize customBackgroundColor=_customBackgroundColor;
@property(nonatomic) double customCornerRadius; // @synthesize customCornerRadius=_customCornerRadius;
@property(retain, nonatomic) NSColor *customTextColor; // @synthesize customTextColor=_customTextColor;
@property(nonatomic) BOOL didSetupView; // @synthesize didSetupView=_didSetupView;
- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) double edgeInsets; // @synthesize edgeInsets=_edgeInsets;
- (void)executeSizeUpdate;
@property(nonatomic) double initialWidth; // @synthesize initialWidth=_initialWidth;
@property(nonatomic) struct CGPoint nibCenter; // @synthesize nibCenter=_nibCenter;
@property(nonatomic) double nibWidth; // @synthesize nibWidth=_nibWidth;
- (void)setDefaultProperties;
- (void)setDefaultValues;
- (void)setStringValue:(id)arg1;
- (void)setTitle:(id)arg1;
- (void)updateSizeDependingOnText;
- (void)updateTextColor;

@end

