//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLButton3.h"

@interface NLButtonNibWidth : NLButton3
{
}

- (void)drawRect:(struct CGRect)arg1;

@end

