//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLButton3.h"

@interface NLButtonIcon : NLButton3
{
    BOOL _didSetupButtonView;
}

- (void)awakeFromNib;
@property(nonatomic) BOOL didSetupButtonView; // @synthesize didSetupButtonView=_didSetupButtonView;
- (void)drawRect:(struct CGRect)arg1;
- (void)executeSizeUpdate;
- (void)setTitle:(id)arg1 withIcon:(id)arg2;

@end

