//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSButton.h"

@interface NLCustomCheckBox : NSButton
{
    BOOL _didLayoutViewsOnce;
}

@property(nonatomic) BOOL didLayoutViewsOnce; // @synthesize didLayoutViewsOnce=_didLayoutViewsOnce;
- (void)drawRect:(struct CGRect)arg1;
- (void)layout;
- (void)setState:(long long)arg1;

@end

