//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLWindowController.h"

@class MyScrollView, NSMutableDictionary, NSView;

@interface NLPageViewController : NLWindowController
{
    MyScrollView *_scrollView;
    NSView *_pageContentView;
    long long _numberOfPages;
    long long _pageIndex;
    NSMutableDictionary *_addedControllers;
}

- (void).cxx_destruct;
- (void)addController:(id)arg1 asPageAtIndex:(long long)arg2;
@property(retain, nonatomic) NSMutableDictionary *addedControllers; // @synthesize addedControllers=_addedControllers;
- (id)addedViewControllers;
- (id)createPageViewWithNumberOfPages:(long long)arg1;
- (void)didFinishShowingPageAtIndex:(long long)arg1;
- (id)init;
- (void)initializePageView;
@property(nonatomic) long long numberOfPages; // @synthesize numberOfPages=_numberOfPages;
@property(retain, nonatomic) NSView *pageContentView; // @synthesize pageContentView=_pageContentView;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
- (void)removeControllerAtPageIndex:(long long)arg1;
@property(retain, nonatomic) MyScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)setupPageView;
- (void)showPageAtIndex:(long long)arg1 animated:(BOOL)arg2;
- (void)updateContentView;
- (void)windowDidLoad;

@end

