//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NLSpecificNotificationManager : NSObject
{
}

+ (void)clipboardIsTooBig;
+ (void)deviceNotConnected;
+ (void)didCopyToIosClipboard;
+ (void)didCopyToMacClipboard;
+ (void)didNotCopyToIosClipboard;
+ (void)didNotCopyToMacClipboard;
+ (void)didUnlockUsingNearLock;
+ (void)didUnlockUsingWiFiUnlock;
+ (void)onlySupportedInProVersion;
+ (void)showAutoHideNotificationWithText:(id)arg1;
+ (void)showAutoHideNotificationWithText:(id)arg1 identifier:(id)arg2;
+ (void)showClipboardIsEmpty;
+ (void)showDidConnectNotificationWithText:(id)arg1;
+ (void)showFailedToLoginDetected;
+ (void)showPersistantNativeNotificationWithText:(id)arg1;
+ (void)showPersistantNativeNotificationWithText:(id)arg1 identifier:(id)arg2;
+ (void)updateNearLockVersionOnIphoneToUseFeature;

@end

