//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NLUrlManager : NSObject
{
}

+ (id)feedUrlCustomConfig;
+ (id)feedUrlSparkleString;
+ (void)openAppInAppStore;
+ (void)openArabic;
+ (void)openChinese;
+ (void)openDutch;
+ (void)openEnglish;
+ (void)openFAQLink;
+ (void)openFbShareLink;
+ (void)openFrench;
+ (void)openGerman;
+ (void)openItalian;
+ (void)openJapanese;
+ (void)openKorean;
+ (void)openLanguageLink:(id)arg1;
+ (void)openLink:(id)arg1;
+ (void)openNearLockHomescreen;
+ (void)openNearLockOfficialWebsite;
+ (void)openNearLockSettings;
+ (void)openNearLockUpdateWebsite;
+ (void)openPortuguese;
+ (void)openRatingPage;
+ (void)openRussian;
+ (void)openSpanish;
+ (void)openTwitterShareLink;
+ (void)openiOSAppInAppStore;

@end

