//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NLViewControllerFactory : NSObject
{
}

+ (id)authOptionsVC;
+ (id)basePager;
+ (id)bleJammed:(id)arg1 next:(CDUnknownBlockType)arg2;
+ (id)bluetoothIsOnIphone:(id)arg1 next:(CDUnknownBlockType)arg2;
+ (id)cacheRestartMac;
+ (id)clearCacheAction:(CDUnknownBlockType)arg1;
+ (id)createAcceptViewControllerAccept:(CDUnknownBlockType)arg1 deny:(CDUnknownBlockType)arg2;
+ (id)distanceEstimationVC;
+ (id)downloadAndOpenNearLock:(id)arg1 next:(CDUnknownBlockType)arg2;
+ (id)downloadAndOpenNearLockRescan:(CDUnknownBlockType)arg1 troubleshoot:(CDUnknownBlockType)arg2;
+ (id)faqOrEmailWithTitle:(id)arg1;
+ (id)howToGetProVersionVC;
+ (id)infoControllerWithIcon:(id)arg1 description:(id)arg2;
+ (id)loadingViewWithTitle:(id)arg1;
+ (id)macOSXNotiicationsVC;
+ (id)macSleepScreenOverlayVC;
+ (id)makeSureBleOn:(id)arg1 next:(CDUnknownBlockType)arg2;
+ (id)manualPhotosVC;
+ (id)openSpaceInfoVC;
+ (id)proximityLockDisabledBecauseWifiVC;
+ (id)proximityLockDisabledManualLoginVC;
+ (id)rateOnAppStore:(CDUnknownBlockType)arg1;
+ (id)restartBluetooth:(id)arg1 restart:(CDUnknownBlockType)arg2;
+ (id)restartiPhoneApp:(id)arg1 next:(CDUnknownBlockType)arg2;
+ (id)supportOrClearCache:(id)arg1 faq:(CDUnknownBlockType)arg2 clearBLE:(CDUnknownBlockType)arg3;
+ (id)turnBluetoothOff:(id)arg1 action:(CDUnknownBlockType)arg2;
+ (id)updateNearLockOnYourPhoneDone:(CDUnknownBlockType)arg1;

@end

