//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class MyButton, NSView;

@interface NLWindowController : NSWindowController
{
    BOOL _windowIsShown;
    id <NLWindowControllerDelegate> _windowDelegate;
    MyButton *_closeButton;
    NSView *_contentView;
}

- (void).cxx_destruct;
- (void)bringCloseButtonToFront;
- (void)centerFrame;
@property(retain, nonatomic) MyButton *closeButton; // @synthesize closeButton=_closeButton;
- (void)closeButtonPressed;
- (void)closeWindow;
@property(retain, nonatomic) NSView *contentView; // @synthesize contentView=_contentView;
- (void)createCloseButton;
- (double)defaultPositioningRatioForScreenHeight:(double)arg1;
- (id)existingUserDefinedOrFallbackNibName;
- (id)init;
- (void)initialize;
- (id)mainView;
- (id)nibName;
- (BOOL)performCustomActionOnBackButtonToggled;
- (void)setBackgroundImage:(id)arg1;
@property(nonatomic) __weak id <NLWindowControllerDelegate> windowDelegate; // @synthesize windowDelegate=_windowDelegate;
@property(nonatomic) BOOL windowIsShown; // @synthesize windowIsShown=_windowIsShown;
- (void)showCloseButton:(BOOL)arg1;
- (void)showWindow;
- (void)showWindowInFront;
- (id)titleDescriptionText;
- (void)updateWindowView;
- (void)windowDidLoad;
- (void)windowWillClose:(id)arg1;

@end

