//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NMShortStringCoder : NSObject
{
}

+ (id)getAllFirstLeverProperties:(id)arg1;
+ (id)getArrayOfValuesObject:(id)arg1;
+ (id)getDictionaryOfPropertyDescriptionsForObject:(id)arg1;
+ (id)getPropertyWithName:(id)arg1 withProperty:(id)arg2 forObject:(id)arg3;
+ (id)getStringKeyForNum:(int)arg1;
+ (id)getStringValueForProperty:(id)arg1 forObject:(id)arg2;
+ (id)propertyTypeStringOfProperty:(struct objc_property *)arg1;
+ (void)setProperty:(id)arg1 toPropertyWithName:(id)arg2 forObject:(id)arg3;
+ (void)setValue:(id)arg1 toPropertyWithName:(id)arg2 forObject:(id)arg3;
+ (id)shortStringDecode:(id)arg1 forClass:(Class)arg2;
+ (id)shortStringDecodeToArray2:(id)arg1 forClass:(Class)arg2;
+ (id)shortStringEncodeForObject:(id)arg1;

@end

