//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSButton, NSImageView, NSString, NSTextField, NSTimer;

@interface NotificationViewController : NSViewController
{
    int _state;
    int _currentTimerValue;
    id <NotificationViewControllerDelegate> _delegate;
    NSString *_mobileDeviceName;
    NSTimer *_timer;
    NSTextField *_topLabel;
    NSTextField *_centeredNotificationTextBig;
    NSImageView *_mainImageView;
    NSButton *_mainButton;
    NSButton *_infoButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTextField *centeredNotificationTextBig; // @synthesize centeredNotificationTextBig=_centeredNotificationTextBig;
@property(nonatomic) int currentTimerValue; // @synthesize currentTimerValue=_currentTimerValue;
@property(nonatomic) __weak id <NotificationViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didToggleInfoButton:(id)arg1;
- (void)didToggleMainButton:(id)arg1;
- (double)heightForTextField:(id)arg1 setText:(id)arg2;
@property(retain, nonatomic) NSButton *infoButton; // @synthesize infoButton=_infoButton;
- (id)init;
@property(retain, nonatomic) NSButton *mainButton; // @synthesize mainButton=_mainButton;
@property(retain, nonatomic) NSImageView *mainImageView; // @synthesize mainImageView=_mainImageView;
@property(retain, nonatomic) NSString *mobileDeviceName; // @synthesize mobileDeviceName=_mobileDeviceName;
@property(nonatomic) int state; // @synthesize state=_state;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSTextField *topLabel; // @synthesize topLabel=_topLabel;
- (void)updateLabelFrame:(id)arg1 withHorizontalOffset:(double)arg2;
- (void)updateLabelFrames;
- (void)updateSubviewLayout;
- (void)viewDidAppear;
- (void)viewDidLayout;

@end

