//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSTextField;

@interface NotSupportedViewController : BaseViewController
{
    int _notSupportedReason;
    id <NotSupportedViewControllerDelegate> _delegate;
    NSTextField *_mainTextLabel;
    NSButton *_mainButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <NotSupportedViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)initialize;
@property(retain, nonatomic) NSButton *mainButton; // @synthesize mainButton=_mainButton;
@property(retain, nonatomic) NSTextField *mainTextLabel; // @synthesize mainTextLabel=_mainTextLabel;
@property(nonatomic) int notSupportedReason; // @synthesize notSupportedReason=_notSupportedReason;
- (void)quitToggled:(id)arg1;
- (void)updateStrings;

@end

