//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSBundle.h"

@interface NSBundle (Language)
+ (id)allTranlationsForLocalizableKey:(id)arg1;
+ (id)currentlyPrefferedLanguage;
+ (id)currentlyUsedLanguageLangKey;
+ (id)languageToBeUsedFromSupportedLanguages;
+ (id)prefferedLanguages;
+ (void)resetPrefferedLanguagesToDefault;
+ (void)setLocalizableLanguage:(id)arg1;
+ (void)setPrefferedLanguage:(id)arg1;
+ (BOOL)shouldUpdateLocalizableLanguage;
+ (id)supprotedLanguages;
@end

