//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (CustomColor)
+ (id)custom1;
+ (id)custom2;
+ (id)custom3;
+ (id)customLightGray;
+ (id)nearLockGreen;
+ (id)redButtonColor;
+ (id)redErrorBackgroundColor;
+ (id)redTextColor;
+ (id)separatorColor;
+ (id)separatorColorLight;
+ (id)warningYellow;
@end

