//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSColor.h"

@interface NSColor (CNGridViewPalette)
+ (id)itemBackgroundColor;
+ (id)itemBackgroundHoverColor;
+ (id)itemBackgroundSelectionColor;
+ (id)itemSelectionRingColor;
+ (id)itemTitleColor;
+ (id)itemTitleShadowColor;
+ (id)selectionFrameColor;
@end

