//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (Calculations)
+ (id)dateFromDay:(long long)arg1 andMonth:(long long)arg2 andYear:(long long)arg3;
+ (long long)daysBetweenDate:(id)arg1 andDate:(id)arg2;
+ (id)earlierDateOf:(id)arg1 andDate:(id)arg2;
+ (id)laterDateOf:(id)arg1 andDate:(id)arg2;
+ (long long)midnightsBetweenDate:(id)arg1 andDate:(id)arg2;
+ (long long)minutesBetweenDates:(id)arg1 andDate:(id)arg2;
+ (long long)oneBasedWeekday:(long long)arg1;
+ (int)secondsSinceDate:(id)arg1;
- (id)dateWithHour:(long long)arg1;
- (id)dateWithHour:(long long)arg1 andMinuten:(long long)arg2;
- (id)dateWithMinute:(long long)arg1;
- (id)dateWithWeekDay:(long long)arg1;
- (id)endOfDay;
- (id)findMondayOfCurrentWeek;
- (long long)getDay;
- (id)getDayWithOffset:(long long)arg1;
- (long long)getHour;
- (id)getHourWithOffset:(long long)arg1;
- (long long)getMinute;
- (id)getMinuteWithOffset:(long long)arg1;
- (long long)getMonth;
- (id)getMonthWithOffset:(long long)arg1;
- (id)getNextMonth;
- (id)getPreviousMonth;
- (long long)getTime:(int)arg1;
- (id)getTomorrow;
- (long long)getTotalMintesInDay;
- (id)getWeekWithOffset:(long long)arg1;
- (long long)getWeekday;
- (long long)getYear;
- (id)getYearWithOffset:(long long)arg1;
- (id)getYesterday;
- (BOOL)isAfterDate:(id)arg1;
- (BOOL)isBeforeDate:(id)arg1;
- (BOOL)isBetween:(id)arg1 andDate:(id)arg2;
- (BOOL)isEndOfDay;
- (BOOL)isSameDayAs:(id)arg1;
- (BOOL)isSameMonthAs:(id)arg1;
- (BOOL)isSameYearAs:(id)arg1;
- (BOOL)isStartOfDay;
- (BOOL)isToday;
- (BOOL)isTodayInWeekWithStart:(long long)arg1 andMonth:(long long)arg2 andYear:(long long)arg3;
- (long long)numberOfDaysInMonth;
- (long long)oneBasedWeekday;
- (id)setDayOfMonth:(long long)arg1;
- (id)setMonth:(long long)arg1;
- (id)startOfDay;
- (id)startOfMonth;
- (id)startOfYear;
@end

