//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Addition)
+ (BOOL)isEmptyString:(id)arg1;
+ (BOOL)isInt:(id)arg1;
+ (BOOL)isNumber:(id)arg1;
+ (id)labelTextDoubleNewLine;
+ (id)labelTextNewLine;
+ (id)newLine;
+ (id)numberForString:(id)arg1;
- (BOOL)containsIgnoreSensitiveString:(id)arg1;
- (BOOL)containsOnlyEmptySpaces;
- (BOOL)isInteger;
- (BOOL)isPartOfOrContains:(id)arg1;
- (BOOL)isPartOfString:(id)arg1;
- (id)removeNumberFromStringInBrackets;
- (BOOL)stringContainsAnySubstringFromArrayOfStrings:(id)arg1;
- (id)stringWithMaxLength:(unsigned long long)arg1;
@end

