//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@interface NSView (NLAdditions)
- (struct CGRect)frameDown;
- (struct CGRect)frameLeft;
- (struct CGRect)frameRight;
- (struct CGRect)frameUp;
- (struct CGRect)incomingFrameForAnimationDirection:(int)arg1;
- (struct CGRect)outgoingFrameForAnimationDirection:(int)arg1;
- (void)setBackgroundImage:(id)arg1;
- (void)setClipsToBounds:(BOOL)arg1;
- (void)setViewDisabled;
- (void)setViewEnabled;
@end

