//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSNumber, NSString;

@interface OSXPreferences : NSObject <NSCoding>
{
    NSString *_OSXVersion;
    NSString *_OSXSystemVersion;
    NSNumber *_isWaitingForConfirmation;
    NSNumber *_allowLogin;
    NSNumber *_allowLogout;
    NSNumber *_wakeScreenOnApproach;
    NSNumber *_allowCloserDistances;
    NSNumber *_lastConnectionTimestamp;
    NSNumber *_installAuthMethod;
    NSNumber *_passwordScreenAuthMethod;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *OSXSystemVersion; // @synthesize OSXSystemVersion=_OSXSystemVersion;
@property(retain, nonatomic) NSString *OSXVersion; // @synthesize OSXVersion=_OSXVersion;
@property(retain, nonatomic) NSNumber *allowCloserDistances; // @synthesize allowCloserDistances=_allowCloserDistances;
@property(retain, nonatomic) NSNumber *allowLogin; // @synthesize allowLogin=_allowLogin;
@property(retain, nonatomic) NSNumber *allowLogout; // @synthesize allowLogout=_allowLogout;
- (id)customCopy;
- (void)decodeWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)init;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSNumber *installAuthMethod; // @synthesize installAuthMethod=_installAuthMethod;
@property(retain, nonatomic) NSNumber *isWaitingForConfirmation; // @synthesize isWaitingForConfirmation=_isWaitingForConfirmation;
@property(retain, nonatomic) NSNumber *lastConnectionTimestamp; // @synthesize lastConnectionTimestamp=_lastConnectionTimestamp;
@property(retain, nonatomic) NSNumber *passwordScreenAuthMethod; // @synthesize passwordScreenAuthMethod=_passwordScreenAuthMethod;
- (void)setDefaultValues;
@property(retain, nonatomic) NSNumber *wakeScreenOnApproach; // @synthesize wakeScreenOnApproach=_wakeScreenOnApproach;
- (void)updateModelUpdateForNewVersion;

@end

