//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImageView, NSMutableArray;

@interface PageControl : NSView
{
    int _numberOfDots;
    int _indexSelected;
    int _distanceBetweenDots;
    NSImageView *_activePageIndicator;
    NSMutableArray *_pageIndicatorArray;
}

- (void).cxx_destruct;
@property(retain) NSImageView *activePageIndicator; // @synthesize activePageIndicator=_activePageIndicator;
- (id)createPageIndicatorAtIndex:(int)arg1;
@property int distanceBetweenDots; // @synthesize distanceBetweenDots=_distanceBetweenDots;
- (void)drawRect:(struct CGRect)arg1;
@property int indexSelected; // @synthesize indexSelected=_indexSelected;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)initialize;
@property(nonatomic) int numberOfDots; // @synthesize numberOfDots=_numberOfDots;
@property(retain) NSMutableArray *pageIndicatorArray; // @synthesize pageIndicatorArray=_pageIndicatorArray;
- (id)pageIndicatorForIndex:(int)arg1;
- (void)removeAllDots;
- (void)setDotActiveAtIndex:(int)arg1 animated:(BOOL)arg2;
- (void)updateView;

@end

