//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

#import "MenuBarSettingsDelegate.h"
#import "NSWindowDelegate.h"
#import "NotificationViewControllerDelegate.h"

@class BackgroundView, ClipboardView, EventTimestamp, MenuBarSettings, NSButton, NSImageView, NSString, NSTextField, NSTimer, NSView, NSWindow, NearLockSettingsView, NotificationViewController, Panel, SingleMobileDeviceView, WifiUnlockView;

@interface PanelController : NSWindowController <NotificationViewControllerDelegate, MenuBarSettingsDelegate, NSWindowDelegate>
{
    BOOL _hasActivePanel;
    BackgroundView *_backgroundView;
    id <PanelControllerDelegate> _delegate;
    NSTextField *_textField;
    BOOL _notificationActive;
    BOOL _isEditMode;
    id <NavigationDelegate> _navigationDelegate;
    NSTimer *_notificationTimer;
    NSWindow *_currentPanel;
    NotificationViewController *_notificationView;
    EventTimestamp *_rssiUpdateTimestamp;
    Panel *_view;
    NSTextField *_titleLabel;
    NSImageView *_horizontalLine1;
    NSButton *_nearLockInfoButton;
    NSButton *_wifiInfoButton;
    NSImageView *_backgroundImageView;
    NSButton *_sleepButton;
    NSButton *_settingsButton;
    MenuBarSettings *_settingsController;
    NearLockSettingsView *_nearLockSettingsView;
    SingleMobileDeviceView *_mobileDeviceView;
    WifiUnlockView *_wifiUnlockView;
    ClipboardView *_clipboardView;
    NSView *_bootomView;
    NSButton *_editButton;
    NSButton *_openButton;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(retain, nonatomic) NSImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(nonatomic) BackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) NSView *bootomView; // @synthesize bootomView=_bootomView;
- (struct CGRect)bottomViewRect;
- (void)cancelNotificationIfActive;
- (void)cancelOperation:(id)arg1;
- (void)clearBluetoothCache:(id)arg1;
- (void)clipboardCheckBox:(id)arg1;
- (void)clipboardInfoButtonToggled:(id)arg1;
- (struct CGRect)clipboardRect;
@property(retain, nonatomic) ClipboardView *clipboardView; // @synthesize clipboardView=_clipboardView;
- (void)closePanel;
- (int)currentNotification;
@property(retain, nonatomic) NSWindow *currentPanel; // @synthesize currentPanel=_currentPanel;
- (void)dealloc;
@property(readonly, nonatomic) id <PanelControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)didChangeSwitch:(id)arg1;
- (void)didUnlinkFromMobileDevice:(id)arg1;
- (void)distanceSliderDidChange:(id)arg1;
@property(retain, nonatomic) NSButton *editButton; // @synthesize editButton=_editButton;
- (void)editToggled:(id)arg1;
- (struct CGRect)getPanelRect;
@property(nonatomic) BOOL hasActivePanel;
- (void)helpToggled:(id)arg1;
@property(retain, nonatomic) NSImageView *horizontalLine1; // @synthesize horizontalLine1=_horizontalLine1;
- (id)imageForSettingsIcon;
- (id)initWithDelegate:(id)arg1;
- (void)iosVersionNotUpToDate:(id)arg1;
@property(nonatomic) BOOL isEditMode; // @synthesize isEditMode=_isEditMode;
- (void)loadWindowForFastFirstOpening;
- (void)menuBarSettings:(id)arg1 didSelectOption:(int)arg2;
@property(retain, nonatomic) SingleMobileDeviceView *mobileDeviceView; // @synthesize mobileDeviceView=_mobileDeviceView;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
@property(nonatomic) __weak id <NavigationDelegate> navigationDelegate; // @synthesize navigationDelegate=_navigationDelegate;
@property(retain, nonatomic) NSButton *nearLockInfoButton; // @synthesize nearLockInfoButton=_nearLockInfoButton;
- (void)nearLockInfoButtonToggled:(id)arg1;
@property(retain, nonatomic) NearLockSettingsView *nearLockSettingsView; // @synthesize nearLockSettingsView=_nearLockSettingsView;
@property(nonatomic) BOOL notificationActive; // @synthesize notificationActive=_notificationActive;
- (void)notificationButtonToggled:(id)arg1;
@property(retain, nonatomic) NSTimer *notificationTimer; // @synthesize notificationTimer=_notificationTimer;
@property(retain, nonatomic) NotificationViewController *notificationView; // @synthesize notificationView=_notificationView;
- (void)notificationViewControllerDidToggleInfoButton:(id)arg1;
- (void)notificationViewControllerDidToggleMainButton:(id)arg1;
@property(retain, nonatomic) NSButton *openButton; // @synthesize openButton=_openButton;
- (void)openNearLockToggled:(id)arg1;
- (void)openPanel;
- (void)osxVersionNotUpToDate;
- (void)panelDidClose;
- (void)pingToggled:(id)arg1;
- (void)prepareFullScreenUserNotification;
- (void)proximityCheckBox:(id)arg1;
- (void)removeNotificationFromView;
- (void)rescanToggled:(id)arg1;
@property(retain, nonatomic) EventTimestamp *rssiUpdateTimestamp; // @synthesize rssiUpdateTimestamp=_rssiUpdateTimestamp;
- (void)sendClipboardToIosToggled:(id)arg1;
- (void)setMainActionDelegate:(id)arg1;
- (void)setRescanButtonMouseoverEffect;
@property(retain, nonatomic) NSButton *settingsButton; // @synthesize settingsButton=_settingsButton;
@property(retain, nonatomic) MenuBarSettings *settingsController; // @synthesize settingsController=_settingsController;
@property(retain, nonatomic) NSButton *sleepButton; // @synthesize sleepButton=_sleepButton;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) Panel *view; // @synthesize view=_view;
@property(retain, nonatomic) NSButton *wifiInfoButton; // @synthesize wifiInfoButton=_wifiInfoButton;
@property(retain, nonatomic) WifiUnlockView *wifiUnlockView; // @synthesize wifiUnlockView=_wifiUnlockView;
- (void)settingsButtonToggled:(id)arg1;
- (BOOL)shouldHideAllOptions;
- (BOOL)shouldShowClipboard;
- (BOOL)shouldShowHelpButton;
- (BOOL)shouldShowNearLockOptions;
- (BOOL)shouldShowPingButton;
- (BOOL)shouldShowProximityOptions;
- (BOOL)shouldShowWiFiUnlock;
- (void)showBluetoothOffIfNeccesary;
- (void)showClearBluetoothCache;
- (void)showHelpButtonIfNeeded;
- (void)showLoadingIndicator;
- (void)showMainView:(id)arg1;
- (void)showNearLockTemporaryDisabled;
- (void)showNotification:(int)arg1 withObject:(id)arg2;
- (void)showUnableToLockMac;
- (void)showUnableToUnlockMac;
- (void)showUnsolvableErrorNotification;
- (void)sleepToggled:(id)arg1;
- (struct CGRect)statusRectForWindow:(id)arg1;
- (void)stopNotificationTimer;
- (void)temporaryDisabledToggled:(id)arg1;
- (void)troublePairingDevicesTutorial:(id)arg1;
- (void)updateBackgroundImage;
- (void)updateDistanceLabelForMobileDevice:(id)arg1;
- (void)updateNotificationButton;
- (void)updatePanel;
- (void)updatePanelForTrackingDeviceAnimated:(BOOL)arg1;
- (void)updatePingButton;
- (void)updateSettingsIcon;
- (void)wifiInfoButtonToggled:(id)arg1;
- (void)wifiUnlockCheckBox:(id)arg1;
- (struct CGRect)wifiUnlockRect;
- (void)wifiUnlockToggled:(id)arg1;
- (void)windowDidResignKey:(id)arg1;
- (void)windowDidResize:(id)arg1;
- (void)windowDidUpdate:(id)arg1;
- (void)windowWillClose:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

