//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface PeriodicNotifierController : NSObject
{
    id <PeriodicNotifierControllerDelegate> _delegate;
    NSTimer *_periodicTimer;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <PeriodicNotifierControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTimer *periodicTimer; // @synthesize periodicTimer=_periodicTimer;
- (void)startPeriodicTimerWithIntervalInSeconds:(long long)arg1;
- (void)stopPeriodicTimer;
- (void)triggerPeriodicNotifier:(id)arg1;

@end

