//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PeriodicNotifierController;

@protocol PeriodicNotifierControllerDelegate <NSObject>
- (void)periodicNotifierControllerDidTrigger:(PeriodicNotifierController *)arg1;
@end

