//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PeripheralConnectionFilter : NSObject
{
}

+ (BOOL)canConnectToPeripheralWithAdvertismentData:(id)arg1;
+ (BOOL)isAppleTVForAdvertismentData:(id)arg1;
+ (BOOL)isNearLockService:(id)arg1;
+ (BOOL)isUnknownService:(id)arg1;
+ (BOOL)peripheralHasAppropriateServicesInAdvertismentData:(id)arg1 serviceUUIDs:(id)arg2;

@end

