//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PhotoManager : NSObject
{
}

- (long long)numberOfBaseEntriesWithPhotos:(id)arg1;
- (long long)numberOfFailedLoginEntriesWithPhotos;
- (long long)numberOfLoginEntriesWithPhotos;
- (long long)numberOfSnapshotEntriesWithPhotos;
- (BOOL)shouldTakeManualSnapshot;
- (BOOL)shouldTakePhotoAfterLoginLogin;
- (BOOL)shouldTakePhotoOnFailedLogin;

@end

