//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSButton, NSImageView, NSTextField;

@interface PhotosView : NSView
{
    NSImageView *_clipboardSeparator;
    NSButton *_infoButton;
    NSButton *_failedLoginAttemptsPhotoButton;
    NSTextField *_failedLoginAttemptsPhotoLabel;
    NSButton *_loginPhotosButton;
    NSTextField *_loginPhotosLabel;
    NSButton *_photosViewInfoButton;
    NSTextField *_photosViewInfoLabel;
    NSButton *_checkBox;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSButton *checkBox; // @synthesize checkBox=_checkBox;
@property(retain, nonatomic) NSImageView *clipboardSeparator; // @synthesize clipboardSeparator=_clipboardSeparator;
@property(retain, nonatomic) NSButton *failedLoginAttemptsPhotoButton; // @synthesize failedLoginAttemptsPhotoButton=_failedLoginAttemptsPhotoButton;
@property(retain, nonatomic) NSTextField *failedLoginAttemptsPhotoLabel; // @synthesize failedLoginAttemptsPhotoLabel=_failedLoginAttemptsPhotoLabel;
@property(retain, nonatomic) NSButton *infoButton; // @synthesize infoButton=_infoButton;
@property(retain, nonatomic) NSButton *loginPhotosButton; // @synthesize loginPhotosButton=_loginPhotosButton;
@property(retain, nonatomic) NSTextField *loginPhotosLabel; // @synthesize loginPhotosLabel=_loginPhotosLabel;
@property(retain, nonatomic) NSButton *photosViewInfoButton; // @synthesize photosViewInfoButton=_photosViewInfoButton;
@property(retain, nonatomic) NSTextField *photosViewInfoLabel; // @synthesize photosViewInfoLabel=_photosViewInfoLabel;
- (void)updateStrings;

@end

