//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PopoverModelFactory : NSObject
{
    id <PopoverModelFactoryDelegate> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <PopoverModelFactoryDelegate> delegate; // @synthesize delegate=_delegate;
- (id)popoverModelForType:(int)arg1;
- (void)setLearnMoreForFailedLoginAttemptsPhotos:(id)arg1;
- (void)setLearnMoreForLoginPhotos:(id)arg1;
- (void)setOkForFirstButton:(id)arg1;

@end

