//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSPopoverDelegate.h"
#import "PopoverModelFactoryDelegate.h"

@class NSPopover, NSString, PopoverModel, PopoverModelFactory;

@interface PopoverManager : NSObject <NSPopoverDelegate, PopoverModelFactoryDelegate>
{
    id <PopoverManagerDelegate> _delegate;
    PopoverModel *_currentPopoverModel;
    NSPopover *_popover;
    PopoverModelFactory *_popoverModelFactory;
}

- (void).cxx_destruct;
@property(retain, nonatomic) PopoverModel *currentPopoverModel; // @synthesize currentPopoverModel=_currentPopoverModel;
@property(nonatomic) __weak id <PopoverManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)hidePopover;
- (id)init;
@property(retain, nonatomic) NSPopover *popover; // @synthesize popover=_popover;
@property(retain, nonatomic) PopoverModelFactory *popoverModelFactory; // @synthesize popoverModelFactory=_popoverModelFactory;
- (void)popoverModelFactory:(id)arg1 didSelectOption:(int)arg2;
- (int)popoverTypeForFailedLoginAttempts:(BOOL)arg1;
- (void)popoverWillShow:(id)arg1;
- (void)showPopoverFromView:(id)arg1;
- (void)updatePopoverModelForFailedLoginAttempts:(BOOL)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

