//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PopoverModel : NSObject
{
    NSString *_popoverDescriptionShort;
    NSString *_popoverDescriptionLong;
    CDUnknownBlockType _button1Action;
    NSString *_button1Title;
    CDUnknownBlockType _button2Action;
    NSString *_button2Title;
}

- (void).cxx_destruct;
@property(copy, nonatomic) CDUnknownBlockType button1Action; // @synthesize button1Action=_button1Action;
@property(retain, nonatomic) NSString *button1Title; // @synthesize button1Title=_button1Title;
@property(copy, nonatomic) CDUnknownBlockType button2Action; // @synthesize button2Action=_button2Action;
@property(retain, nonatomic) NSString *button2Title; // @synthesize button2Title=_button2Title;
@property(retain, nonatomic) NSString *popoverDescriptionLong; // @synthesize popoverDescriptionLong=_popoverDescriptionLong;
@property(retain, nonatomic) NSString *popoverDescriptionShort; // @synthesize popoverDescriptionShort=_popoverDescriptionShort;

@end

