//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class NSButton, NSTextField, PopoverModel;

@interface PpopverContentInfoController : NSViewController
{
    PopoverModel *_popoverModel;
    NSTextField *_label;
    NSButton *_button1;
    NSButton *_button2;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSButton *button1; // @synthesize button1=_button1;
@property(retain, nonatomic) NSButton *button2; // @synthesize button2=_button2;
@property(retain, nonatomic) NSTextField *label; // @synthesize label=_label;
- (void)leftButtonToggled:(id)arg1;
@property(retain, nonatomic) PopoverModel *popoverModel; // @synthesize popoverModel=_popoverModel;
- (void)rigthButtonToggled:(id)arg1;
- (void)updateButton;
- (void)updateStrings;

@end

