//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PresentationEntry.h"

@class FailedLoginEntry;

@interface PresentationEntryFailedLogin : PresentationEntry
{
    FailedLoginEntry *_failedLoginEntry;
}

- (void).cxx_destruct;
@property(retain, nonatomic) FailedLoginEntry *failedLoginEntry; // @synthesize failedLoginEntry=_failedLoginEntry;

@end

