//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface PresentationEntry : NSObject
{
    int _presentationEvent;
    NSString *_presentationText;
    NSString *_presentationIconName;
    NSDate *_date;
}

- (void).cxx_destruct;
- (long long)compare:(id)arg1;
@property(retain, nonatomic) NSDate *date; // @synthesize date=_date;
- (id)iconNameForPresentationEvent;
@property(nonatomic) int presentationEvent; // @synthesize presentationEvent=_presentationEvent;
@property(retain, nonatomic) NSString *presentationIconName; // @synthesize presentationIconName=_presentationIconName;
@property(retain, nonatomic) NSString *presentationText; // @synthesize presentationText=_presentationText;

@end

