//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PropertyDescription : NSObject
{
    NSString *propertyName;
    NSString *propertyType;
}

- (void).cxx_destruct;
- (long long)compare:(id)arg1;
@property(retain, nonatomic) NSString *propertyName; // @synthesize propertyName;
@property(retain, nonatomic) NSString *propertyType; // @synthesize propertyType;

@end

