//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class PXListView;

@interface PXListDocumentView : NSView
{
    PXListView *_listView;
    unsigned long long _dropHighlight;
}

- (void)drawRect:(struct CGRect)arg1;
@property(nonatomic) unsigned long long dropHighlight; // @synthesize dropHighlight=_dropHighlight;
- (BOOL)isFlipped;
@property(nonatomic) PXListView *listView; // @synthesize listView=_listView;
- (void)mouseDown:(id)arg1;

@end

