//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AbstractMusicController.h"

@class QuickTimeDocument;

@interface QuickTimeMusicController : AbstractMusicController
{
    QuickTimeDocument *_stoppedDocument;
}

- (void).cxx_destruct;
- (id)appName;
- (BOOL)isRunningAndPlaying;
- (BOOL)pauseIfPlaying;
- (BOOL)playIfRunningAndNotPlaying;
@property(retain, nonatomic) QuickTimeDocument *stoppedDocument; // @synthesize stoppedDocument=_stoppedDocument;
- (int)type;

@end

