//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface Reachability : NSObject
{
    BOOL reachableOnWWAN;
    struct __SCNetworkReachability *reachabilityRef;
    NSObject<OS_dispatch_queue> *reachabilitySerialQueue;
    CDUnknownBlockType reachableBlock;
    CDUnknownBlockType unreachableBlock;
    id reachabilityObject;
}

+ (id)reachabilityForInternetConnection;
+ (id)reachabilityForLocalWiFi;
+ (id)reachabilityWithAddress:(const struct sockaddr_in *)arg1;
+ (id)reachabilityWithHostname:(id)arg1;
- (void).cxx_destruct;
- (BOOL)connectionRequired;
- (id)currentReachabilityFlags;
- (int)currentReachabilityStatus;
- (id)currentReachabilityString;
- (void)dealloc;
- (id)description;
- (id)initWithReachabilityRef:(struct __SCNetworkReachability *)arg1;
- (BOOL)isConnectionOnDemand;
- (BOOL)isConnectionRequired;
- (BOOL)isInterventionRequired;
- (BOOL)isReachable;
- (BOOL)isReachableViaWWAN;
- (BOOL)isReachableViaWiFi;
- (BOOL)isReachableWithFlags:(unsigned int)arg1;
- (void)reachabilityChanged:(unsigned int)arg1;
- (unsigned int)reachabilityFlags;
@property(retain, nonatomic) id reachabilityObject; // @synthesize reachabilityObject;
@property(nonatomic) struct __SCNetworkReachability *reachabilityRef; // @synthesize reachabilityRef;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *reachabilitySerialQueue; // @synthesize reachabilitySerialQueue;
@property(copy, nonatomic) CDUnknownBlockType reachableBlock; // @synthesize reachableBlock;
@property(nonatomic) BOOL reachableOnWWAN; // @synthesize reachableOnWWAN;
@property(copy, nonatomic) CDUnknownBlockType unreachableBlock; // @synthesize unreachableBlock;
- (BOOL)startNotifier;
- (void)stopNotifier;

@end

