//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RecoveryManager : NSObject
{
    BOOL _isRecovery;
}

+ (id)shared;
- (id)init;
- (BOOL)isInRecoveryMode;
@property(nonatomic) BOOL isRecovery; // @synthesize isRecovery=_isRecovery;
- (void)notifyOfNewState;
- (void)startRecoveryMode;
- (void)stopRecoveryMode;

@end

