//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface RemotePairedDevices : NSObject
{
    NSString *_objectId;
    NSString *_macId;
    NSString *_iPhoneId;
    double _lastUpdateTimestamp;
}

+ (id)currentTimestampString;
- (void).cxx_destruct;
@property(retain, nonatomic) NSString *iPhoneId; // @synthesize iPhoneId=_iPhoneId;
- (id)initWithPFObject:(id)arg1;
@property(nonatomic) double lastUpdateTimestamp; // @synthesize lastUpdateTimestamp=_lastUpdateTimestamp;
@property(retain, nonatomic) NSString *macId; // @synthesize macId=_macId;
@property(retain, nonatomic) NSString *objectId; // @synthesize objectId=_objectId;
- (id)pfObject;

@end

