//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ConnectionControllerDelegate.h"

@class ConnectionController, NSString;

@interface RequestController : NSObject <ConnectionControllerDelegate>
{
    ConnectionController *connectionController;
    id <RequestControllerDelegate> delegate;
}

- (void).cxx_destruct;
- (void)cancelLoginConfirmationForMobileDevice:(id)arg1;
- (void)cancelLoginConfirmationForMobileDevice:(id)arg1 forReason:(id)arg2;
- (void)cancelLoginConfirmationPasswordFieldShownForMobileDevice:(id)arg1;
- (void)checkRSSIForMobileDeviceAndNotifyDelegate:(id)arg1;
- (void)cleanTheIgnoreList;
- (void)clearTheIgnoreListOfBadConnections;
- (void)confirmLoginForMobileDevice:(id)arg1 forReason:(id)arg2;
- (void)confirmLoginForMobileDevice:(id)arg1 silent:(BOOL)arg2;
- (void)confirmLoginForMobileDeviceBecausePasswordFieldShown:(id)arg1 silent:(BOOL)arg2;
- (void)connectionController:(id)arg1 didConnectToMobileDevice:(id)arg2;
- (void)connectionController:(id)arg1 didDisconnectFromMobileDevice:(id)arg2;
- (void)connectionController:(id)arg1 didExperienceError:(int)arg2;
- (void)connectionController:(id)arg1 didReceiveMessage:(id)arg2 fromMobileDevice:(id)arg3;
- (void)connectionController:(id)arg1 didUpdateRSSI:(id)arg2 forMobileDevice:(id)arg3;
@property(nonatomic) __weak id <RequestControllerDelegate> delegate; // @synthesize delegate;
- (void)didCopyClipboard:(BOOL)arg1 toMac:(id)arg2;
- (void)didEstablishConnectionAndFinishedSynWithDevice:(id)arg1;
- (void)didUpdateSessionInforForCurrentDevice:(id)arg1;
- (void)didUpdateTrackInfoForMobileDevice:(id)arg1;
- (void)disconnectFromAllDevicesImmediatelly:(BOOL)arg1;
- (void)forgetAllDevices;
- (void)getMobileDeviceInformationIfNeeded:(id)arg1;
- (void)handleRejectedConnectionForMobileDevice:(id)arg1;
- (id)init;
- (void)mobileDevice:(id)arg1 connectionAccepted:(BOOL)arg2;
- (void)mobileDeviceDidPair:(id)arg1;
- (void)mobileDeviceDidUpdateRSSI:(id)arg1;
- (BOOL)mobileDeviceIsCurrentlyPairing:(id)arg1;
- (void)notifyDeviceForNewStatusForMobilDevice:(id)arg1;
- (void)procesRequest:(id)arg1 fromMobileDevice:(id)arg2;
- (void)removeDeviceFromIgnoreList:(id)arg1;
- (void)sendDeviceData:(id)arg1 toMobileDevice:(id)arg2;
- (void)sendNotification:(int)arg1 toMobileDevice:(id)arg2 usePushNotificationIfNeeded:(BOOL)arg3;
- (void)sendPairingRequestToMobileDevice:(id)arg1;
- (void)sendSettingsFromDevice:(id)arg1;
- (void)showNextPairingDevice;
- (void)startIntenseScanning;
- (void)syncAllDeviceSettingsForMobileDevice:(id)arg1;
- (void)updateClipboardForMobileDevice:(id)arg1 clipboardText:(id)arg2;
- (void)updateCurrentConnectionStatusTo:(int)arg1 forMobilDevice:(id)arg2 sendRemoteNotificationIfNeeded:(BOOL)arg3;
- (void)updatePairingForMobileDevice:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

