//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MobileDevice, MobileDeviceTrackInfo, NSNumber, NSString, RequestController;

@protocol RequestControllerDelegate <NSObject>
- (void)requestController:(RequestController *)arg1 didChangeSettings:(MobileDeviceTrackInfo *)arg2 forMobileDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didChangeTrackingDistance:(int)arg2 forMobileDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didConfirmAuthRequest:(NSString *)arg2 forDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didConfirmLogin:(NSNumber *)arg2 fromMobileDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didDisconnectFromMobileDevice:(MobileDevice *)arg2;
- (void)requestController:(RequestController *)arg1 didReceiveLoginCommandFromMobileDevice:(MobileDevice *)arg2;
- (void)requestController:(RequestController *)arg1 didReceiveLogoutCommandFromMobileDevice:(MobileDevice *)arg2;
- (void)requestController:(RequestController *)arg1 didReceiveMobileNotification:(int)arg2;
- (void)requestController:(RequestController *)arg1 didReceiveRequestToConnectToMobileDevice:(MobileDevice *)arg2;
- (void)requestController:(RequestController *)arg1 didStartSyncingWithMobileDevice:(MobileDevice *)arg2;
- (void)requestController:(RequestController *)arg1 didSuccessfullyPair:(BOOL)arg2 withMobileDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didUpdateApplicationStateFromMobileDevice:(MobileDevice *)arg2 withState:(NSNumber *)arg3;
- (void)requestController:(RequestController *)arg1 didUpdateClipboardText:(NSString *)arg2 forDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didUpdateConnectionStatus:(NSNumber *)arg2 fromMobileDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didUpdateIosClipboard:(BOOL)arg2 forDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didUpdateMobileDeviceSettings:(MobileDevice *)arg2;
- (void)requestController:(RequestController *)arg1 didUpdateRSSI:(NSNumber *)arg2 fromMobileDevice:(MobileDevice *)arg3;
- (void)requestController:(RequestController *)arg1 didUpdateSessionInfoForDevice:(MobileDevice *)arg2;
- (void)requestControllerDidExperienceCorruptedBluetoothCache:(RequestController *)arg1;
- (void)requestControllerDidExperienceFatalError:(RequestController *)arg1;
@end

