//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class CALayer, CIFilter, NSColor, NSNumber;

@interface RMBlurredView : NSView
{
    CIFilter *_blurFilter;
    CIFilter *_saturationFilter;
    CALayer *_hostedLayer;
    float _saturationFactor;
    float _blurRadius;
    NSColor *_tintColor;
    NSNumber *_saturationFactorNumber;
    NSNumber *_blurRadiusNumber;
}

- (void).cxx_destruct;
@property(nonatomic) float blurRadius; // @synthesize blurRadius=_blurRadius;
@property(retain, nonatomic) NSNumber *blurRadiusNumber; // @synthesize blurRadiusNumber=_blurRadiusNumber;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)resetFilters;
@property(nonatomic) float saturationFactor; // @synthesize saturationFactor=_saturationFactor;
@property(retain, nonatomic) NSNumber *saturationFactorNumber; // @synthesize saturationFactorNumber=_saturationFactorNumber;
@property(retain, nonatomic) NSColor *tintColor; // @synthesize tintColor=_tintColor;
- (void)setUp;

@end

