//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface RSSISmoothener : NSObject
{
}

+ (void)smoothenRSSI:(id)arg1 forMobileDevice:(id)arg2;
+ (id)smootherRssi:(id)arg1 oldRSSI:(id)arg2;

@end

