//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class SafeWifiViewModel;

@interface SafeWifiWizzardPage : BaseViewController
{
    SafeWifiViewModel *_viewModel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SafeWifiViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void)updateViewForViewModel;
- (void)viewDidLoad;

@end

