//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SafeWifiWizzardPage.h"

@class NSButton, NSImageView, NSTextField, SafeWifiFinishViewModel;

@interface SafeWifiFinishController : SafeWifiWizzardPage
{
    id <SafeWifiFinishControllerDelegate> _delegate;
    NSImageView *_mainImage;
    NSTextField *_titleLabel;
    NSTextField *_descriptionLabel;
    NSButton *_finishButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <SafeWifiFinishControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(nonatomic) __weak NSButton *finishButton; // @synthesize finishButton=_finishButton;
- (void)finishToggled:(id)arg1;
@property(nonatomic) __weak NSImageView *mainImage; // @synthesize mainImage=_mainImage;
@property(nonatomic) __weak NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)updateStrings;
- (void)updateViewForViewModel;

// Remaining properties
@property(retain, nonatomic) SafeWifiFinishViewModel *viewModel; // @dynamic viewModel;

@end

