//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SafeWifiWizzardPage.h"

#import "PXListViewDelegate.h"
#import "SafeWifiCellDelegate.h"

@class NSButton, NSString, NSTextField, NSView, NearLockListView, SafeWifiManager;

@interface SafeWifiEditController : SafeWifiWizzardPage <PXListViewDelegate, SafeWifiCellDelegate>
{
    id <SafeWifiEditControllerDelegate> _delegate;
    NearLockListView *_listView;
    NSView *_listViewBackgroundView;
    NSTextField *_titleLabel;
    NSTextField *_descriptionLabel;
    NSTextField *_wifiListWifiName;
    NSTextField *_wifiListDelete;
    SafeWifiManager *_wifiManager;
    NSButton *_wifiUnlockCheckox;
    NSTextField *_wifiUnlockCheckoxText;
    NSTextField *_wifiUnlockCheckoxTextDescription;
    NSButton *_addNewButton;
}

- (void).cxx_destruct;
@property(nonatomic) NSButton *addNewButton; // @synthesize addNewButton=_addNewButton;
- (void)addNewWifi:(id)arg1;
- (void)awakeFromNib;
- (void)checkBoxToggled:(id)arg1;
- (void)dealloc;
@property(nonatomic) __weak id <SafeWifiEditControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) NearLockListView *listView; // @synthesize listView=_listView;
- (id)listView:(id)arg1 cellForRow:(unsigned long long)arg2;
- (double)listView:(id)arg1 heightOfRow:(unsigned long long)arg2;
@property(retain, nonatomic) NSView *listViewBackgroundView; // @synthesize listViewBackgroundView=_listViewBackgroundView;
- (unsigned long long)numberOfRowsInListView:(id)arg1;
- (void)reloadView;
- (void)safeWifiCellDidSelectDelete:(id)arg1;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)setUpListView;
@property(retain, nonatomic) NSTextField *wifiListDelete; // @synthesize wifiListDelete=_wifiListDelete;
@property(retain, nonatomic) NSTextField *wifiListWifiName; // @synthesize wifiListWifiName=_wifiListWifiName;
@property(retain, nonatomic) SafeWifiManager *wifiManager; // @synthesize wifiManager=_wifiManager;
@property(nonatomic) NSButton *wifiUnlockCheckox; // @synthesize wifiUnlockCheckox=_wifiUnlockCheckox;
@property(retain, nonatomic) NSTextField *wifiUnlockCheckoxText; // @synthesize wifiUnlockCheckoxText=_wifiUnlockCheckoxText;
@property(retain, nonatomic) NSTextField *wifiUnlockCheckoxTextDescription; // @synthesize wifiUnlockCheckoxTextDescription=_wifiUnlockCheckoxTextDescription;
- (void)updateStrings;
- (void)updateViewForViewModel;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

