//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SafeWifiViewModel : NSObject
{
    BOOL _isAddingNewWifi;
    BOOL _isConnectedToWiFi;
    BOOL _wifiAlreadyAdded;
    NSString *_trackingIphoneName;
    NSString *_wifiName;
}

- (void).cxx_destruct;
@property(nonatomic) BOOL isAddingNewWifi; // @synthesize isAddingNewWifi=_isAddingNewWifi;
@property(nonatomic) BOOL isConnectedToWiFi; // @synthesize isConnectedToWiFi=_isConnectedToWiFi;
@property(retain, nonatomic) NSString *trackingIphoneName; // @synthesize trackingIphoneName=_trackingIphoneName;
@property(nonatomic) BOOL wifiAlreadyAdded; // @synthesize wifiAlreadyAdded=_wifiAlreadyAdded;
@property(retain, nonatomic) NSString *wifiName; // @synthesize wifiName=_wifiName;

@end

