//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SafeWifiWizzardPage.h"

@class NSButton, NSImageView, NSTextField, SafeWifiNewViewModel;

@interface SafeWifiAddNewWifiController : SafeWifiWizzardPage
{
    id <SafeWifiAddNewWifiControllerDelegate> _delegate;
    NSImageView *_mainImage;
    NSTextField *_titleLabel;
    NSTextField *_descriptionLabel2;
    NSButton *_leftButton;
    NSButton *_rightButton;
    NSButton *_centerButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSButton *centerButton; // @synthesize centerButton=_centerButton;
- (void)centerButton:(id)arg1;
@property(nonatomic) __weak id <SafeWifiAddNewWifiControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSTextField *descriptionLabel2; // @synthesize descriptionLabel2=_descriptionLabel2;
@property(nonatomic) __weak NSButton *leftButton; // @synthesize leftButton=_leftButton;
- (void)leftButton:(id)arg1;
@property(nonatomic) __weak NSImageView *mainImage; // @synthesize mainImage=_mainImage;
@property(nonatomic) __weak NSButton *rightButton; // @synthesize rightButton=_rightButton;
- (void)rightButton:(id)arg1;
@property(nonatomic) __weak NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)showConnectedWifi;
- (void)showNoConnectedWifi;
- (void)updateStrings;
- (void)updateViewForViewModel;

// Remaining properties
@property(retain, nonatomic) SafeWifiNewViewModel *viewModel; // @dynamic viewModel;

@end

