//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SafeWifiEditController, SafeWifiEntry;

@protocol SafeWifiEditControllerDelegate <NSObject>
- (void)safeWifiEditController:(SafeWifiEditController *)arg1 didSelectDeleteWifi:(SafeWifiEntry *)arg2;
- (void)safeWifiEditController:(SafeWifiEditController *)arg1 didSelectOption:(int)arg2;
@end

