//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MobileDevice, SafeWifiEntry;

@interface SafeWifiWizzardContext : NSObject
{
    int _currentEntryProcess;
    SafeWifiEntry *_currentEntry;
    MobileDevice *_trackingMobileDevice;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SafeWifiEntry *currentEntry; // @synthesize currentEntry=_currentEntry;
@property(nonatomic) int currentEntryProcess; // @synthesize currentEntryProcess=_currentEntryProcess;
@property(retain, nonatomic) MobileDevice *trackingMobileDevice; // @synthesize trackingMobileDevice=_trackingMobileDevice;

@end

