//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "WifiHelperDelegate.h"

@class NSString, WifiHelper;

@interface SafeWifiManager : NSObject <WifiHelperDelegate>
{
    WifiHelper *_wifiHelper;
}

+ (id)shared;
- (void).cxx_destruct;
- (BOOL)addSafeWifiEntry:(id)arg1;
- (id)currentlyConnectedApplicationdataSafeWifiEntry;
- (id)generateCurrentConnectedWifiEntry;
- (id)init;
- (BOOL)isConectedToSafeWifi;
- (BOOL)removeSafeWifiEntry:(id)arg1;
- (id)safeWifiEntries;
@property(nonatomic) BOOL safeWifiTurnedOn;
- (void)saveWifiEntries;
@property(retain, nonatomic) WifiHelper *wifiHelper; // @synthesize wifiHelper=_wifiHelper;
- (BOOL)shouldShowWifiOption;
- (BOOL)shouldUnlockForSafeWifi;
- (void)wifiHelperDidUpdateWifiState:(id)arg1;
- (int)wifiState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

