//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SafeWifiWizzardPage.h"

@class NSButton, NSImageView, NSTextField, NSView, SafeWifiFirstViewModel;

@interface SafeWifiFirstController : SafeWifiWizzardPage
{
    id <SafeWifiFirstControllerDelegate> _delegate;
    NSImageView *_mainImage;
    NSTextField *_titleLabel;
    NSTextField *_descriptionLabel;
    NSView *_notSupportedView;
    NSImageView *_notSupportedImageView;
    NSTextField *_notSupportedLabel;
    NSButton *_mainButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <SafeWifiFirstControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(nonatomic) __weak NSButton *mainButton; // @synthesize mainButton=_mainButton;
- (void)mainButtonToggled:(id)arg1;
@property(nonatomic) __weak NSImageView *mainImage; // @synthesize mainImage=_mainImage;
@property(nonatomic) __weak NSImageView *notSupportedImageView; // @synthesize notSupportedImageView=_notSupportedImageView;
@property(nonatomic) __weak NSTextField *notSupportedLabel; // @synthesize notSupportedLabel=_notSupportedLabel;
@property(nonatomic) __weak NSView *notSupportedView; // @synthesize notSupportedView=_notSupportedView;
@property(nonatomic) __weak NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)showIssue:(int)arg1;
- (void)updateStrings;
- (void)updateViewForViewModel;
- (void)viewDidLoad;

// Remaining properties
@property(retain, nonatomic) SafeWifiFirstViewModel *viewModel; // @dynamic viewModel;

@end

