//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLPageViewControllerExtended.h"

#import "SafeWifiAddNewWifiControllerDelegate.h"
#import "SafeWifiEditControllerDelegate.h"
#import "SafeWifiFinishControllerDelegate.h"
#import "SafeWifiFirstControllerDelegate.h"

@class NSString, SafeWifiAddNewWifiController, SafeWifiEditController, SafeWifiFinishController, SafeWifiFirstController, SafeWifiManager, SafeWifiViewModelFactory, SafeWifiWizzardContext;

@interface SafeWifiWizzard : NLPageViewControllerExtended <SafeWifiFirstControllerDelegate, SafeWifiAddNewWifiControllerDelegate, SafeWifiFinishControllerDelegate, SafeWifiEditControllerDelegate>
{
    id <SafeWifiWizzardDelegate> _delegate;
    SafeWifiManager *_wifiManager;
    SafeWifiFirstController *_welcomeController;
    SafeWifiEditController *_editController;
    SafeWifiAddNewWifiController *_addNewWifiController;
    SafeWifiFinishController *_finishController;
    SafeWifiWizzardContext *_context;
    SafeWifiViewModelFactory *_viewModelFactory;
}

- (void).cxx_destruct;
- (void)SafeWifiAddNewWifiController:(id)arg1 didSelectOption:(int)arg2;
@property(retain, nonatomic) SafeWifiAddNewWifiController *addNewWifiController; // @synthesize addNewWifiController=_addNewWifiController;
- (void)addNewWifiNetwork;
@property(retain, nonatomic) SafeWifiWizzardContext *context; // @synthesize context=_context;
@property(nonatomic) __weak id <SafeWifiWizzardDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) SafeWifiEditController *editController; // @synthesize editController=_editController;
@property(retain, nonatomic) SafeWifiFinishController *finishController; // @synthesize finishController=_finishController;
- (void)initializePages;
- (void)safeWifiEditController:(id)arg1 didSelectDeleteWifi:(id)arg2;
- (void)safeWifiEditController:(id)arg1 didSelectOption:(int)arg2;
- (void)safeWifiFinishController:(id)arg1 didSelectOption:(int)arg2;
- (void)safeWifiFirstController:(id)arg1 didSelectOption:(int)arg2;
- (void)saveCurrentWifiAndShowFinish;
@property(retain, nonatomic) SafeWifiViewModelFactory *viewModelFactory; // @synthesize viewModelFactory=_viewModelFactory;
@property(retain, nonatomic) SafeWifiFirstController *welcomeController; // @synthesize welcomeController=_welcomeController;
@property(retain, nonatomic) SafeWifiManager *wifiManager; // @synthesize wifiManager=_wifiManager;
- (void)showAppropriateScreen;
- (void)showAppropriateScreen:(BOOL)arg1;
- (void)showEditWifi;
- (void)showFinishWifi;
- (void)showNotEnabledViewController;
- (void)showWelcomeScreen;
- (void)updateContextForCurrentState;
- (void)updatePageForCurrentState;
- (void)updateViewModelForWizzardPage:(id)arg1;
- (void)windowDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

