//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SafeWifiViewModel.h"

@interface SafeWifiFirstViewModel : SafeWifiViewModel
{
    BOOL _canEditWifi;
    BOOL _canAddNewWifi;
    int _issueReason;
}

@property(nonatomic) BOOL canAddNewWifi; // @synthesize canAddNewWifi=_canAddNewWifi;
@property(nonatomic) BOOL canEditWifi; // @synthesize canEditWifi=_canEditWifi;
@property(nonatomic) int issueReason; // @synthesize issueReason=_issueReason;

@end

