//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearLockListViewCell.h"

@class NSTextField, SafeWifiEntry;

@interface SafeWifiCell : NearLockListViewCell
{
    id <SafeWifiCellDelegate> _delegate;
    NSTextField *_ssidNameLabel;
    SafeWifiEntry *_entry;
}

- (void).cxx_destruct;
- (void)dealloc;
@property(nonatomic) __weak id <SafeWifiCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deleteToggled:(id)arg1;
- (void)didChangeSwitch:(id)arg1;
@property(retain, nonatomic) SafeWifiEntry *entry; // @synthesize entry=_entry;
- (void)prepareForReuse;
@property(retain, nonatomic) NSTextField *ssidNameLabel; // @synthesize ssidNameLabel=_ssidNameLabel;

@end

