//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSTimer;

@interface ScanningIndicator : NSObject
{
    BOOL _timerIsActive;
    BOOL _timerIsEnabled;
    NSTimer *_timer;
    double _timerDuration;
}

+ (id)shared;
- (void).cxx_destruct;
- (id)init;
- (void)invalidateTimerAndSendNotification:(BOOL)arg1;
- (void)restartTimer;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) double timerDuration; // @synthesize timerDuration=_timerDuration;
@property(nonatomic) BOOL timerIsActive; // @synthesize timerIsActive=_timerIsActive;
@property(nonatomic) BOOL timerIsEnabled; // @synthesize timerIsEnabled=_timerIsEnabled;
- (void)startTimer;
- (void)stopTimer;

@end

