//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp, NSTimer;

@interface ScanIntervalController : NSObject
{
    int _currentlyActiveScanInterval;
    id <ScanIntervalControllerDelegate> _delegate;
    NSTimer *_scanTimer;
    EventTimestamp *_intenseDurationTimestamp;
    long long _intenseDuration;
}

- (void).cxx_destruct;
@property(nonatomic) int currentlyActiveScanInterval; // @synthesize currentlyActiveScanInterval=_currentlyActiveScanInterval;
- (void)dealloc;
@property(nonatomic) __weak id <ScanIntervalControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (double)durationForScanInterval:(int)arg1;
- (id)init;
@property(nonatomic) long long intenseDuration; // @synthesize intenseDuration=_intenseDuration;
@property(retain, nonatomic) EventTimestamp *intenseDurationTimestamp; // @synthesize intenseDurationTimestamp=_intenseDurationTimestamp;
- (BOOL)intenseScanIsActive;
- (void)invalidateScanTimer;
@property(retain, nonatomic) NSTimer *scanTimer; // @synthesize scanTimer=_scanTimer;
- (void)scanTimerTriggered;
- (BOOL)shouldDowngradeScanTimerFromIntenseToNorma;
- (void)startIntenseScanTimerWithDurationInSeconds:(long long)arg1;
- (void)startScanTimerWithDuration:(double)arg1;
- (id)stringForScanInterval:(int)arg1;
- (void)updateScanInterval:(int)arg1;
- (void)updateScanTimerIntervalIfNeeded;

@end

