//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ScreensaverPreconditions : NSObject
{
    BOOL _screensaverPreconditionsFalse;
}

+ (id)shared;
- (void)checkForValidScreensaverPreferancesAfterLogin;
@property(nonatomic) BOOL screensaverPreconditionsFalse; // @synthesize screensaverPreconditionsFalse=_screensaverPreconditionsFalse;
- (BOOL)screensaverPreconditionsUnknown;
- (BOOL)screensaverPreferencesCurrentSetupIsWrong;
- (BOOL)shouldWarnUserAboutScreensaverPreconditions;
- (void)userUpdatedScreensaverPreconditions;

@end

