//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSRunningApplication;

@interface SecurityAgentListener : NSObject
{
    BOOL _securityAgentActive;
    BOOL _nearLockActive;
    BOOL _systemPreferancesActive;
    id <SecurityAgentListenerDelegate> _delegate;
    NSRunningApplication *_runningApplication;
}

+ (id)shared;
- (void).cxx_destruct;
- (void)authenticateSecurityAgent;
- (void)checkFrontMostApplication;
- (void)dealloc;
@property(nonatomic) __weak id <SecurityAgentListenerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
@property(nonatomic) BOOL nearLockActive; // @synthesize nearLockActive=_nearLockActive;
- (BOOL)nearLockIsActive;
@property(retain, nonatomic) NSRunningApplication *runningApplication; // @synthesize runningApplication=_runningApplication;
@property(nonatomic) BOOL securityAgentActive; // @synthesize securityAgentActive=_securityAgentActive;
- (BOOL)securityAgentIsActive;
@property(nonatomic) BOOL systemPreferancesActive; // @synthesize systemPreferancesActive=_systemPreferancesActive;
- (BOOL)systemPreferancesIsActive;
- (void)wsNotificationHook:(id)arg1;

@end

