//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSNumber, NSString;

@interface SessionInfo : NSObject <NSCoding>
{
    NSNumber *_userIsLoggedIn;
    NSString *_userIdLoggedIn;
    NSNumber *_deviceResponsibleForLastChange;
    NSNumber *_laptopLidIsDownAndNoExternalMonitor;
}

- (void).cxx_destruct;
- (id)copyCustom;
- (void)decodeWithCoder:(id)arg1;
@property(retain, nonatomic) NSNumber *deviceResponsibleForLastChange; // @synthesize deviceResponsibleForLastChange=_deviceResponsibleForLastChange;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@property(retain, nonatomic) NSNumber *laptopLidIsDownAndNoExternalMonitor; // @synthesize laptopLidIsDownAndNoExternalMonitor=_laptopLidIsDownAndNoExternalMonitor;
@property(retain, nonatomic) NSString *userIdLoggedIn; // @synthesize userIdLoggedIn=_userIdLoggedIn;
@property(retain, nonatomic) NSNumber *userIsLoggedIn; // @synthesize userIsLoggedIn=_userIsLoggedIn;

@end

