//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ListViewModelController.h"

@class NSString, NSTextField;

@interface SettingsMasterViewController : ListViewModelController
{
    NSString *_bottomText;
    NSTextField *_bottomTextField;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *bottomText; // @synthesize bottomText=_bottomText;
@property(retain, nonatomic) NSTextField *bottomTextField; // @synthesize bottomTextField=_bottomTextField;
- (void)viewDidLoad;

@end

