//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

#import "NSWindowDelegate.h"

@class AnimationViewModel, NLButtonIcon, NSString, NSTextField, NSView;

@interface SettingsDetailViewController : BaseViewController <NSWindowDelegate>
{
    BOOL _isAnimating;
    BOOL _hasNavbar;
    CDUnknownBlockType _backToggled;
    NLButtonIcon *_backButton;
    NSTextField *_titleText;
    NSView *_separator;
    NSView *_contentViewContainer;
    NSView *_navbar;
    NSView *_fullscreenContentContainer;
    NSView *_navbarContentContainer;
    NSView *_currentContentView;
    NSView *_oldContentView;
    AnimationViewModel *_queuedAnimation;
}

- (void).cxx_destruct;
@property(nonatomic) NLButtonIcon *backButton; // @synthesize backButton=_backButton;
- (void)backButtonToggled:(id)arg1;
@property(copy) CDUnknownBlockType backToggled; // @synthesize backToggled=_backToggled;
@property(nonatomic) NSView *contentViewContainer; // @synthesize contentViewContainer=_contentViewContainer;
@property(nonatomic) NSView *currentContentView; // @synthesize currentContentView=_currentContentView;
- (void)finishAnimation:(CDUnknownBlockType)arg1;
@property(nonatomic) NSView *fullscreenContentContainer; // @synthesize fullscreenContentContainer=_fullscreenContentContainer;
@property(nonatomic) BOOL hasNavbar; // @synthesize hasNavbar=_hasNavbar;
@property(nonatomic) BOOL isAnimating; // @synthesize isAnimating=_isAnimating;
@property(nonatomic) NSView *navbar; // @synthesize navbar=_navbar;
@property(nonatomic) NSView *navbarContentContainer; // @synthesize navbarContentContainer=_navbarContentContainer;
@property(nonatomic) NSView *oldContentView; // @synthesize oldContentView=_oldContentView;
- (void)processQueuedAnimation;
@property(retain, nonatomic) AnimationViewModel *queuedAnimation; // @synthesize queuedAnimation=_queuedAnimation;
@property(nonatomic) NSView *separator; // @synthesize separator=_separator;
@property(nonatomic) NSTextField *titleText; // @synthesize titleText=_titleText;
- (void)updateContentView:(id)arg1 animationDirection:(int)arg2;
- (void)updateContentView:(id)arg1 animationDirection:(int)arg2 completion:(CDUnknownBlockType)arg3;
- (void)updateContentView:(id)arg1 animationDirection:(int)arg2 hasNavbar:(BOOL)arg3;
- (void)updateContentView:(id)arg1 animationDirection:(int)arg2 hasNavbar:(BOOL)arg3 completion:(CDUnknownBlockType)arg4;
- (void)updateNavbar:(BOOL)arg1;
- (void)viewDidLoad;
- (void)windowDidResize:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

