//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearLockBaseItemManager.h"

@interface SetupMenuManager : NearLockBaseItemManager
{
    BOOL _test;
    BOOL _notConnectedExpanded;
    BOOL _noPairedDevicesExpanded;
}

- (id)allowLockOnApproach;
- (id)allowUnlockOnApproach;
- (id)createViewModel;
- (id)disable;
- (id)doubleKnock;
- (id)estimatedDistance:(id)arg1;
- (id)lockMacOnDisconnect;
- (id)lockOptionsSection;
- (id)macWakeUnlockTitle;
@property(nonatomic) BOOL noPairedDevicesExpanded; // @synthesize noPairedDevicesExpanded=_noPairedDevicesExpanded;
@property(nonatomic) BOOL notConnectedExpanded; // @synthesize notConnectedExpanded=_notConnectedExpanded;
- (id)openSpace;
- (id)otherSection;
- (id)proximityUnlock;
- (id)proximityUnlockSection;
- (id)screensaver;
@property(nonatomic) BOOL test; // @synthesize test=_test;
- (id)sleep;
- (id)slider:(id)arg1 settings:(id)arg2;
- (id)smallerDistances;
- (id)touchId;
- (id)yesNo;

@end

