//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSPasteboardWriting.h"

@class NSImage, NSString;

@interface ShareImageModel : NSObject <NSPasteboardWriting>
{
    NSString *_text;
    NSImage *_image;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
- (id)pasteboardPropertyListForType:(id)arg1;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
- (id)writableTypesForPasteboard:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

