//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSViewController, NSWindow;

@interface ShieldWindowManger : NSObject
{
    NSWindow *shieldWindow;
    NSViewController *_currentViewController;
}

- (void).cxx_destruct;
- (void)addViewController:(id)arg1;
- (struct CGRect)createFrameWithSize:(struct CGSize)arg1 inCenterOfFrame:(struct CGRect)arg2 andMoveUpwardFor:(double)arg3;
@property(retain, nonatomic) NSViewController *currentViewController; // @synthesize currentViewController=_currentViewController;
- (void)hideShieldWindowView;
- (BOOL)ifShieldWindowShown;
- (void)setBackgroundColor;
@property(retain, nonatomic) NSWindow *shieldWindow; // @synthesize shieldWindow;
- (void)showShieldWindowView;
- (void)updateViewController;

@end

