//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class EventTimestamp, NSImageView, NSTextField;

@interface ShieldViewController : NSViewController
{
    id <ShieldViewControllerDelegate> _delegate;
    NSImageView *_iphoneImageView;
    NSTextField *_mobileDeviceName;
    NSTextField *_mobileDeviceRSSI;
    NSTextField *_mobileDeviceInfo;
    NSTextField *_pressKeyToLogon;
    EventTimestamp *_rssiUpdater;
}

+ (BOOL)shouldAddPressKeyToLoginForSettings:(id)arg1;
- (void).cxx_destruct;
- (void)animateKnockEffect;
@property(nonatomic) __weak id <ShieldViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (struct CGRect)endFrameForKnockAnimation;
- (id)init;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)initialize;
@property(nonatomic) __weak NSImageView *iphoneImageView; // @synthesize iphoneImageView=_iphoneImageView;
@property(nonatomic) __weak NSTextField *mobileDeviceInfo; // @synthesize mobileDeviceInfo=_mobileDeviceInfo;
@property(nonatomic) __weak NSTextField *mobileDeviceName; // @synthesize mobileDeviceName=_mobileDeviceName;
@property(nonatomic) __weak NSTextField *mobileDeviceRSSI; // @synthesize mobileDeviceRSSI=_mobileDeviceRSSI;
@property(nonatomic) __weak NSTextField *pressKeyToLogon; // @synthesize pressKeyToLogon=_pressKeyToLogon;
@property(retain, nonatomic) EventTimestamp *rssiUpdater; // @synthesize rssiUpdater=_rssiUpdater;
- (void)showDeviceInfo:(id)arg1;
- (void)showPressKeyForLogin:(BOOL)arg1 forConnectedDevice:(BOOL)arg2;
- (void)showRSSIStrigng:(id)arg1;
- (struct CGRect)startFrameForKnockAnimation;
- (void)updateViewForTrackingMobileDevice;
- (void)viewDidLoad;

@end

