//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ShieldViewControllerDelegate.h"

@class EventTimestamp, NSString, ShieldViewController, ShieldWindowManger;

@interface ShieldManager : NSObject <ShieldViewControllerDelegate>
{
    ShieldWindowManger *_shieldManager;
    ShieldViewController *_shieldViewController;
    EventTimestamp *_effectAnimationTimestamp;
}

- (void).cxx_destruct;
- (void)animateEffect:(int)arg1;
- (void)creatAndPrepareShieldView;
- (void)dealloc;
@property(retain, nonatomic) EventTimestamp *effectAnimationTimestamp; // @synthesize effectAnimationTimestamp=_effectAnimationTimestamp;
- (void)hideShieldWindow;
- (id)init;
- (void)mainScreenHasChanged;
- (void)registerForViewUpdates;
- (void)reloadAndShowShieldViewIfNeeded;
- (void)reloadShieldViewController;
@property(retain, nonatomic) ShieldWindowManger *shieldManager; // @synthesize shieldManager=_shieldManager;
@property(retain, nonatomic) ShieldViewController *shieldViewController; // @synthesize shieldViewController=_shieldViewController;
- (void)shieldViewControllerReloadView:(id)arg1;
- (BOOL)shouldShowShieldController;
- (void)updateShieldWindowIfShown;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

