//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class DDHotKey;

@interface ShortCutManager : NSObject
{
    id <ShortCutManagerDelegate> _delegate;
    DDHotKey *_clipboardShortcut;
    DDHotKey *_lockShortcut;
}

+ (id)shared;
- (void).cxx_destruct;
@property(retain, nonatomic) DDHotKey *clipboardShortcut; // @synthesize clipboardShortcut=_clipboardShortcut;
@property(nonatomic) __weak id <ShortCutManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void)deregisterForOption:(int)arg1;
- (void)hotkeyWithEvent:(id)arg1 object:(id)arg2;
@property(retain, nonatomic) DDHotKey *lockShortcut; // @synthesize lockShortcut=_lockShortcut;
- (void)registerForOption:(int)arg1;
- (void)updateShortcutsEnabled;

@end

