//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "InternetNotifierDelegate.h"

@class InternetNotifier, NSString;

@interface SilentPushNotificationManager : NSObject <InternetNotifierDelegate>
{
    BOOL _sendSilentPushWhenInternetAvailable;
    InternetNotifier *_internetNotifier;
}

+ (id)shared;
- (void).cxx_destruct;
- (id)init;
@property(retain, nonatomic) InternetNotifier *internetNotifier; // @synthesize internetNotifier=_internetNotifier;
- (void)internetNotifier:(id)arg1 hasAccesToInternet:(BOOL)arg2;
- (void)sendSilentNotificationIfNeeded;
- (void)sendSilentPushFromDeviceId:(id)arg1 pushId:(id)arg2 string:(id)arg3;
- (void)sendSilentPushToMobileDevice:(id)arg1 withString:(id)arg2;
@property(nonatomic) BOOL sendSilentPushWhenInternetAvailable; // @synthesize sendSilentPushWhenInternetAvailable=_sendSilentPushWhenInternetAvailable;
- (void)testSilentPush;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

