//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSImageView, NSString, NSTextField;

@interface SimpleButtonBaseController : BaseViewController
{
    NSString *_imageName;
    NSString *_labelText;
    NSString *_descriptionLabelText;
    NSString *_buttonTitle;
    CDUnknownBlockType _action;
    NSButton *_button;
    NSTextField *_label;
    NSTextField *_descriptionLabel;
    NSImageView *_imageView;
}

- (void).cxx_destruct;
@property(copy) CDUnknownBlockType action; // @synthesize action=_action;
@property(retain, nonatomic) NSButton *button; // @synthesize button=_button;
@property(retain, nonatomic) NSString *buttonTitle; // @synthesize buttonTitle=_buttonTitle;
- (void)buttonToggled:(id)arg1;
@property(retain, nonatomic) NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) NSString *descriptionLabelText; // @synthesize descriptionLabelText=_descriptionLabelText;
@property(retain, nonatomic) NSString *imageName; // @synthesize imageName=_imageName;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSTextField *label; // @synthesize label=_label;
@property(retain, nonatomic) NSString *labelText; // @synthesize labelText=_labelText;
- (void)updateView;
- (void)viewDidLoad;

@end

