//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SingleError : NSObject
{
    double _errorTimeStamp;
    NSString *_errorType;
}

- (void).cxx_destruct;
@property(nonatomic) double errorTimeStamp; // @synthesize errorTimeStamp=_errorTimeStamp;
@property(retain, nonatomic) NSString *errorType; // @synthesize errorType=_errorType;
- (id)initWithErrorType:(id)arg1;

@end

