//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

@class NSButton, NSImageView, NSString, NSTextField;

@interface SingleMobileDeviceView : NSTableCellView
{
    NSTextField *_nameLabel;
    NSTextField *_distanceLabel;
    NSButton *_helpButton;
    NSButton *_pingButton;
    NSButton *_notificationButton;
    NSImageView *_mobileImageView;
    NSTextField *_noteLabel;
    NSImageView *_loadingImage;
    NSButton *_rescanButton;
    NSString *_savedLabelText;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTextField *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(retain, nonatomic) NSButton *helpButton; // @synthesize helpButton=_helpButton;
@property(retain, nonatomic) NSImageView *loadingImage; // @synthesize loadingImage=_loadingImage;
@property(retain, nonatomic) NSImageView *mobileImageView; // @synthesize mobileImageView=_mobileImageView;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
@property(retain, nonatomic) NSTextField *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) NSTextField *noteLabel; // @synthesize noteLabel=_noteLabel;
@property(retain, nonatomic) NSButton *notificationButton; // @synthesize notificationButton=_notificationButton;
@property(retain, nonatomic) NSButton *pingButton; // @synthesize pingButton=_pingButton;
@property(retain, nonatomic) NSButton *rescanButton; // @synthesize rescanButton=_rescanButton;
@property(retain, nonatomic) NSString *savedLabelText; // @synthesize savedLabelText=_savedLabelText;
- (void)setFramesForProVersion:(BOOL)arg1;
- (void)setLoaderVisible:(BOOL)arg1;
- (void)setRescanButtonMouseoverEffect;

@end

