//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface SleepDurationTracker : NSObject
{
    EventTimestamp *_sleepTimestamp;
    EventTimestamp *_wakeTimestamp;
    EventTimestamp *_longSleepWakeTimestamp;
}

+ (id)shared;
- (void).cxx_destruct;
- (void)applicationDidWake;
- (void)applicationWillSleep;
- (void)dealloc;
- (double)durationInSecondsForLongSleepNotification;
- (id)init;
@property(retain, nonatomic) EventTimestamp *longSleepWakeTimestamp; // @synthesize longSleepWakeTimestamp=_longSleepWakeTimestamp;
- (double)secondsSinceLastLongWakeNotification;
- (double)secondsSinceLastWakeNotification;
@property(retain, nonatomic) EventTimestamp *sleepTimestamp; // @synthesize sleepTimestamp=_sleepTimestamp;
@property(retain, nonatomic) EventTimestamp *wakeTimestamp; // @synthesize wakeTimestamp=_wakeTimestamp;

@end

