//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearLockListViewCell.h"

#import "NearLockListViewCellProtocol.h"

@class CustomSlider, NSString, NSTextField;

@interface SliderCell : NearLockListViewCell <NearLockListViewCellProtocol>
{
    CustomSlider *_distanceSlider;
    NSTextField *_sliderTextLabel;
    NSTextField *_valueTextLabel;
}

+ (double)cellHeight;
+ (id)nibName;
- (void).cxx_destruct;
- (id)castViewModel;
@property(retain, nonatomic) CustomSlider *distanceSlider; // @synthesize distanceSlider=_distanceSlider;
- (void)distanceSliderDidChange:(id)arg1;
@property(retain, nonatomic) NSTextField *sliderTextLabel; // @synthesize sliderTextLabel=_sliderTextLabel;
@property(retain, nonatomic) NSTextField *valueTextLabel; // @synthesize valueTextLabel=_valueTextLabel;
- (void)updateCellForCellViewModel:(id)arg1;
- (void)updateLabelForValue:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

