//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SocketIO : NSObject
{
}

- (void)connect;
- (void)disconnect;
- (void)emit:(id)arg1 withItems:(id)arg2;
- (void)emitWithAck:(id)arg1 withItems:(id)arg2 ack:(CDUnknownBlockType)arg3;
- (id)initWithSocketURL:(id)arg1 options:(id)arg2;
- (BOOL)isConnected;
- (void)on:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (void)onAny:(CDUnknownBlockType)arg1;
- (void)onConnectionStateChange:(CDUnknownBlockType)arg1;

@end

