//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SoundManager : NSObject
{
}

+ (void)playClap;
+ (void)playDingSound;
+ (void)playErrorSound;
+ (void)playErrorSound2;
+ (void)playFinishSound;
+ (void)playFoundNewDeviceSound;
+ (void)playSoundWithFileName:(id)arg1 type:(id)arg2;
+ (id)shared;

@end

