//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSImage, NSStatusItem;

@interface StatusItemView : NSView
{
    NSImage *_image;
    NSImage *_alternateImage;
    NSStatusItem *_statusItem;
    BOOL _isHighlighted;
    SEL _action;
    id _target;
    SEL _rightClickAction;
}

- (void).cxx_destruct;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(retain, nonatomic) NSImage *alternateImage; // @synthesize alternateImage=_alternateImage;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly, nonatomic) struct CGRect globalRect;
@property(retain, nonatomic) NSImage *image; // @synthesize image=_image;
- (id)initWithStatusItem:(id)arg1;
- (BOOL)isDarkModeOn;
@property(nonatomic, setter=setHighlighted:) BOOL isHighlighted; // @synthesize isHighlighted=_isHighlighted;
- (void)mouseDown:(id)arg1;
@property(nonatomic) SEL rightClickAction; // @synthesize rightClickAction=_rightClickAction;
- (void)rightMouseDown:(id)arg1;
@property(nonatomic) id target; // @synthesize target=_target;
@property(readonly, nonatomic) NSStatusItem *statusItem; // @synthesize statusItem=_statusItem;

@end

