//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ClearCacheControllerDelegate.h"
#import "ClipboardInfoViewControllerDelegate.h"
#import "FailedLoginAttemptListenerDelegate.h"
#import "HelpDelegate.h"
#import "LoginLogoutControllerDelegate.h"
#import "LogoutOnDIsconnectManagerDelegate.h"
#import "MacSleepScreenViewControllerDelegate.h"
#import "MainMenuBarControllerDelegate.h"
#import "NLWindowControllerDelegate.h"
#import "NavigationDelegate.h"
#import "PeriodicNotifierControllerDelegate.h"
#import "RSSILoginLogoutDeciderDelegate.h"
#import "RemoteSyncMacDelegate.h"
#import "RequestControllerDelegate.h"
#import "SafeWifiWizzardDelegate.h"
#import "SecurityAgentListenerDelegate.h"
#import "ShortCutManagerDelegate.h"
#import "WizzardViewControllerDelegate.h"

@class ActivityVizualizationController, BaseViewController, ConfirmationRequestHandler, CustomAnimationHelper, EventTimestamp, FailedLoginAttemptListener, FailedLoginFactory, LoginLogoutController, LoginTrackerFactory, LogoutOnDIsconnectManager, MainMenuBarController, MenuManagerFactory, MigrationManager, NSString, NSTimer, NearLockMasterDetailNavManager, PeriodicNotifierController, PhotoManager, RSSILoginLogoutDecider, RemoteSyncMac, RequestController, SecurityAgentListener, ShieldManager, ShortCutManager, SilentPushNotificationManager, TutorialFactory, UpdateNotificationHelper, WAYSourceListWindow;

@interface StateMachine : NSObject <WizzardViewControllerDelegate, LoginLogoutControllerDelegate, MainMenuBarControllerDelegate, RSSILoginLogoutDeciderDelegate, LogoutOnDIsconnectManagerDelegate, PeriodicNotifierControllerDelegate, SecurityAgentListenerDelegate, FailedLoginAttemptListenerDelegate, MacSleepScreenViewControllerDelegate, ClipboardInfoViewControllerDelegate, RequestControllerDelegate, NLWindowControllerDelegate, SafeWifiWizzardDelegate, RemoteSyncMacDelegate, ShortCutManagerDelegate, ClearCacheControllerDelegate, NavigationDelegate, HelpDelegate>
{
    BOOL _didFinishSyncWithDevice;
    BOOL _applicationInShutdownProcess;
    id <StateMachineDelegate> _delegate;
    MainMenuBarController *_mainMenuBarController;
    PeriodicNotifierController *_periodicIgnoreListCleaner;
    LoginLogoutController *_loginLogoutController;
    RequestController *_requestController;
    RSSILoginLogoutDecider *_loginLogoutDecider;
    SecurityAgentListener *_securityAgentListener;
    MigrationManager *_migrationManager;
    LogoutOnDIsconnectManager *_logoutOnDisconnectManager;
    SilentPushNotificationManager *_silentPushNotificationManager;
    RemoteSyncMac *_remoteSync;
    FailedLoginFactory *_failedLoginFactory;
    FailedLoginAttemptListener *_failedLoginListener;
    ShortCutManager *_shortCutmanager;
    PhotoManager *_photoManager;
    LoginTrackerFactory *_loginTrackerFactory;
    MenuManagerFactory *_menuFactory;
    TutorialFactory *_tutorialFactory;
    WAYSourceListWindow *_splitWindow;
    NearLockMasterDetailNavManager *_navManager;
    ShieldManager *_shieldManager;
    ActivityVizualizationController *_activityController;
    BaseViewController *_modalController;
    CustomAnimationHelper *_animationHelper;
    EventTimestamp *_syncStartedTimestamp;
    EventTimestamp *_lockAppearedActionTimestamp;
    EventTimestamp *_recheckRSSITimestamp;
    EventTimestamp *_confirmRSSILoginRequest;
    ConfirmationRequestHandler *_confirmationHandler;
    UpdateNotificationHelper *_updateHelper;
    NSTimer *_failSafeConnectTimer;
}

- (void).cxx_destruct;
- (void)RSSILoginLogoutDecider:(id)arg1 didEnterNearLockRadius:(id)arg2;
- (void)RSSILoginLogoutDecider:(id)arg1 didExitNearLockRadius:(id)arg2;
- (void)RSSILoginLogoutDecider:(id)arg1 didUpdateOverAllInfoForMobileDevice:(id)arg2;
- (void)RSSILoginLogoutDecider:(id)arg1 didUpdateRSSIForMobileDevice:(id)arg2;
- (void)RSSILoginLogoutDecider:(id)arg1 loginForMobileDevice:(id)arg2;
- (void)RSSILoginLogoutDecider:(id)arg1 logoutForMobileDevice:(id)arg2;
- (void)RSSILoginLogoutDecider:(id)arg1 recheckRssiForMobileDevice:(id)arg2;
@property(retain, nonatomic) ActivityVizualizationController *activityController; // @synthesize activityController=_activityController;
- (void)addNearLockToAccessilibityToUnlockMac;
@property(retain, nonatomic) CustomAnimationHelper *animationHelper; // @synthesize animationHelper=_animationHelper;
- (void)anyNearLockWindowWillClose;
- (void)applicationDidFinishLoading;
- (BOOL)applicationDidRestartProgramaticallyInTheLastSeconds:(long long)arg1;
- (void)applicationDidWake;
@property(nonatomic) BOOL applicationInShutdownProcess; // @synthesize applicationInShutdownProcess=_applicationInShutdownProcess;
- (void)applicationWillSleep;
- (void)applicationWillTerminate;
- (void)bluetoothStateChanged;
- (void)checkIfShouldUnlockMacBecauseOfSafeWifi;
- (void)cleanTheIgnoreListOfBadConnectionsIfNeeded;
- (void)cleanUpAndQuitNearLock;
- (void)clearBluetoothCache;
- (void)clearBluetoothCacheAfterCorruptedCacheDetected;
- (void)clearCacheControllerClearCache:(id)arg1;
- (void)clipboardInfoViewController:(id)arg1 didSelectOption:(int)arg2;
- (void)confirmPasswordLoginAfterPasswordFieldShownForMobileDevice:(id)arg1;
- (void)confirmRSSILoginForDevice:(id)arg1;
@property(retain, nonatomic) EventTimestamp *confirmRSSILoginRequest; // @synthesize confirmRSSILoginRequest=_confirmRSSILoginRequest;
@property(retain, nonatomic) ConfirmationRequestHandler *confirmationHandler; // @synthesize confirmationHandler=_confirmationHandler;
- (void)dealloc;
@property(nonatomic) __weak id <StateMachineDelegate> delegate; // @synthesize delegate=_delegate;
- (void)detectedCorruptedBluetoothCache;
- (void)didChangeLoginStateBy:(int)arg1;
- (void)didFinishPairing;
@property(nonatomic) BOOL didFinishSyncWithDevice; // @synthesize didFinishSyncWithDevice=_didFinishSyncWithDevice;
- (void)didReceiveUpdatesUpdate;
- (void)didUnlindFromIphone;
- (void)didUnlink;
- (void)didUnlinkFromMac;
- (void)didUpdateBluetoothState;
- (void)didUpdateMacSleepScreenUnlock;
- (void)didUpdateMobileTrackInfoFromMac;
- (void)didUpdateProximityLockInfo;
- (void)disableTempProxTrackingAfterLoginIfOn;
- (void)disableTempProxTrackingIfOn;
- (void)dockItemToggled;
- (void)executePasswordConfirmationReqeustForDevice:(id)arg1;
- (void)executeRSSIConfirmationReqeustForDevice:(id)arg1;
@property(retain, nonatomic) NSTimer *failSafeConnectTimer; // @synthesize failSafeConnectTimer=_failSafeConnectTimer;
- (void)failSafeTimerTrigered;
@property(retain, nonatomic) FailedLoginFactory *failedLoginFactory; // @synthesize failedLoginFactory=_failedLoginFactory;
@property(retain, nonatomic) FailedLoginAttemptListener *failedLoginListener; // @synthesize failedLoginListener=_failedLoginListener;
- (void)failedloginAttemptListenerDidDetectFailedLogin:(id)arg1;
- (void)forgetAndDisconnectMobileDevice:(id)arg1;
- (void)getClipboardFromIos;
- (void)handleLockAppearedAction;
- (void)helpDelegate:(id)arg1 didSelectOption:(int)arg2;
- (void)iOSAppEnteredForegroundForMobileDevice:(id)arg1;
- (void)initalizeView;
- (void)invalidateFailSafeTimer;
- (void)laptopLidChangedOrExternalMonitorChanged;
@property(retain, nonatomic) EventTimestamp *lockAppearedActionTimestamp; // @synthesize lockAppearedActionTimestamp=_lockAppearedActionTimestamp;
- (void)lockAppearedOnScreen;
- (void)lockHiddenFromScreen;
- (void)loginFailed;
- (void)loginForMobileDeviceBecauseOfLoginConfirmation:(id)arg1;
@property(retain, nonatomic) LoginLogoutController *loginLogoutController; // @synthesize loginLogoutController=_loginLogoutController;
- (void)loginLogoutController:(id)arg1 canNotLoginWithGivenPasswordForMobileDevice:(id)arg2;
- (void)loginLogoutController:(id)arg1 didLoginbyMobileDevice:(id)arg2 commandReason:(int)arg3;
- (void)loginLogoutController:(id)arg1 didLogoutbyMobileDevice:(id)arg2 commandReason:(int)arg3;
- (void)loginLogoutControllerDidFailToLogin:(id)arg1;
- (void)loginLogoutControllerDidLoginManualyByUser:(id)arg1;
- (void)loginLogoutControllerDidLogoutManualyByUser:(id)arg1;
- (void)loginLogoutControllerDisplayOnButUserNotLoggedIn:(id)arg1;
- (void)loginLogoutControllerUnableToLockMac:(id)arg1;
- (void)loginLogoutControllerUnableToUnlockMac:(id)arg1;
@property(retain, nonatomic) RSSILoginLogoutDecider *loginLogoutDecider; // @synthesize loginLogoutDecider=_loginLogoutDecider;
- (void)loginLogoutHistoryWindow:(id)arg1 didSelectFailedLoginEntry:(id)arg2;
@property(retain, nonatomic) LoginTrackerFactory *loginTrackerFactory; // @synthesize loginTrackerFactory=_loginTrackerFactory;
- (void)logoutIfDeviceTrackingIsActiveForMobileDevice:(id)arg1 commadReason:(int)arg2;
@property(retain, nonatomic) LogoutOnDIsconnectManager *logoutOnDisconnectManager; // @synthesize logoutOnDisconnectManager=_logoutOnDisconnectManager;
- (void)logoutOnDisconnectManagerShouldLogout:(id)arg1;
- (void)logoutTrackingDeviceForCommadReason:(int)arg1;
- (void)lostConnectionToMobileDevice:(id)arg1;
- (void)macSleepScreenViewController:(id)arg1 didSelectOption:(int)arg2;
- (void)macWillShutDown;
@property(retain, nonatomic) MainMenuBarController *mainMenuBarController; // @synthesize mainMenuBarController=_mainMenuBarController;
- (void)mainMenuBarController:(id)arg1 didSelectOption:(int)arg2 forMobileDevice:(id)arg3;
- (BOOL)mainWindowIsShown;
@property(retain, nonatomic) MenuManagerFactory *menuFactory; // @synthesize menuFactory=_menuFactory;
@property(retain, nonatomic) MigrationManager *migrationManager; // @synthesize migrationManager=_migrationManager;
@property(retain, nonatomic) BaseViewController *modalController; // @synthesize modalController=_modalController;
@property(retain, nonatomic) NearLockMasterDetailNavManager *navManager; // @synthesize navManager=_navManager;
- (void)nearLockDidChange:(id)arg1;
- (void)openWindowOrBounceDock:(BOOL)arg1;
- (void)performTasksAfterStartupDelay;
@property(retain, nonatomic) PeriodicNotifierController *periodicIgnoreListCleaner; // @synthesize periodicIgnoreListCleaner=_periodicIgnoreListCleaner;
- (void)periodicNotifierControllerDidTrigger:(id)arg1;
@property(retain, nonatomic) PhotoManager *photoManager; // @synthesize photoManager=_photoManager;
- (void)pingTrackingDevice;
- (void)popViewModelAnimated:(BOOL)arg1;
- (void)prepareForShutdown:(BOOL)arg1;
- (void)processFailedLockOrUnlock;
- (void)pushModalController:(id)arg1;
- (void)recheckRSSIAfterShortDelayForMobileDevice:(id)arg1;
@property(retain, nonatomic) EventTimestamp *recheckRSSITimestamp; // @synthesize recheckRSSITimestamp=_recheckRSSITimestamp;
- (void)registerForNotifications;
@property(retain, nonatomic) RemoteSyncMac *remoteSync; // @synthesize remoteSync=_remoteSync;
- (void)remoteSyncMac:(id)arg1 didUnlinkFromDevice:(id)arg2;
@property(retain, nonatomic) RequestController *requestController; // @synthesize requestController=_requestController;
- (void)requestController:(id)arg1 didChangeSettings:(id)arg2 forMobileDevice:(id)arg3;
- (void)requestController:(id)arg1 didChangeTrackingDistance:(int)arg2 forMobileDevice:(id)arg3;
- (void)requestController:(id)arg1 didConfirmAuthRequest:(id)arg2 forDevice:(id)arg3;
- (void)requestController:(id)arg1 didConfirmLogin:(id)arg2 fromMobileDevice:(id)arg3;
- (void)requestController:(id)arg1 didDisconnectFromMobileDevice:(id)arg2;
- (void)requestController:(id)arg1 didReceiveLoginCommandFromMobileDevice:(id)arg2;
- (void)requestController:(id)arg1 didReceiveLogoutCommandFromMobileDevice:(id)arg2;
- (void)requestController:(id)arg1 didReceiveMobileNotification:(int)arg2;
- (void)requestController:(id)arg1 didReceiveRequestToConnectToMobileDevice:(id)arg2;
- (void)requestController:(id)arg1 didStartSyncingWithMobileDevice:(id)arg2;
- (void)requestController:(id)arg1 didSuccessfullyPair:(BOOL)arg2 withMobileDevice:(id)arg3;
- (void)requestController:(id)arg1 didUpdateApplicationStateFromMobileDevice:(id)arg2 withState:(id)arg3;
- (void)requestController:(id)arg1 didUpdateClipboardText:(id)arg2 forDevice:(id)arg3;
- (void)requestController:(id)arg1 didUpdateConnectionStatus:(id)arg2 fromMobileDevice:(id)arg3;
- (void)requestController:(id)arg1 didUpdateIosClipboard:(BOOL)arg2 forDevice:(id)arg3;
- (void)requestController:(id)arg1 didUpdateMobileDeviceSettings:(id)arg2;
- (void)requestController:(id)arg1 didUpdateRSSI:(id)arg2 fromMobileDevice:(id)arg3;
- (void)requestController:(id)arg1 didUpdateSessionInfoForDevice:(id)arg2;
- (void)requestControllerDidExperienceCorruptedBluetoothCache:(id)arg1;
- (void)requestControllerDidExperienceFatalError:(id)arg1;
- (void)resendUnlockRequestForPasswordScreenIfNeededForMobileDevice:(id)arg1;
- (void)safeWifiWizzard:(id)arg1 udpateSafeWifi:(BOOL)arg2;
- (void)safeWifiWizzardShowPro:(id)arg1;
- (void)scanningUpdated;
- (void)securitAgentDidChange:(id)arg1;
@property(retain, nonatomic) SecurityAgentListener *securityAgentListener; // @synthesize securityAgentListener=_securityAgentListener;
- (void)sendClipboardToIos;
- (void)sendConfirmationRequestAfterLockAppeardIfNeeded;
- (void)sendNotification:(int)arg1 usePushNotificationIfNeeded:(BOOL)arg2;
- (void)sendRSSILoginConfirmationRequestIfNeededAfterPasswordHidden;
- (void)sendRemoteLoginRequestBecausePassAppeared:(id)arg1;
- (void)sendRemoteNotificationForFailedLoginAttempt;

@property(retain, nonatomic) ShieldManager *shieldManager; // @synthesize shieldManager=_shieldManager;
@property(retain, nonatomic) ShortCutManager *shortCutmanager; // @synthesize shortCutmanager=_shortCutmanager;
@property(retain, nonatomic) SilentPushNotificationManager *silentPushNotificationManager; // @synthesize silentPushNotificationManager=_silentPushNotificationManager;
@property(retain, nonatomic) WAYSourceListWindow *splitWindow; // @synthesize splitWindow=_splitWindow;
@property(retain, nonatomic) EventTimestamp *syncStartedTimestamp; // @synthesize syncStartedTimestamp=_syncStartedTimestamp;
@property(retain, nonatomic) TutorialFactory *tutorialFactory; // @synthesize tutorialFactory=_tutorialFactory;
@property(retain, nonatomic) UpdateNotificationHelper *updateHelper; // @synthesize updateHelper=_updateHelper;
- (void)setupNearLockAfterSystemWake;
- (void)setupSettingsSplitView;
- (void)setupShortCutManager;
- (void)shortCutManager:(id)arg1 didSelectOption:(int)arg2;
- (BOOL)shouldConfirmRSSILoginForDevice:(id)arg1;
- (BOOL)shouldHandleLockAppeardAction;
- (BOOL)shouldShowDockItem;
- (BOOL)shouldStartLogoutOnDisconnect:(id)arg1;
- (void)showAccessibilityPreferenceOptionForSource:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)showActivityController;
- (void)showAddNewDeviceView;
- (void)showAddNewDeviceViewOpen:(BOOL)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)showAuthRequest;
- (void)showBluetoothNotSupportedTutorial;
- (void)showClearBluetoothCacheTutorial;
- (void)showClipboardHowDoesItWork;
- (void)showDetailController:(id)arg1 source:(int)arg2;
- (void)showDetailController:(id)arg1 source:(int)arg2 popToRoot:(BOOL)arg3;
- (void)showDetailList:(id)arg1 source:(int)arg2;
- (void)showDetailList:(id)arg1 source:(int)arg2 popToRoot:(BOOL)arg3;
- (void)showEstimatedDistanceDescription;
- (void)showFailedLoginWindowWithEntry:(id)arg1;
- (void)showFailedLogins;
- (void)showHelpTranslation;
- (void)showHelpViewAndCheck;
- (void)showHelpViewController;
- (void)showHowToGetProVersion;
- (void)showInitialTutorialWithCompletion:(CDUnknownBlockType)arg1;
- (void)showLockUnlockHistory;
- (void)showLoginEntriesWithSelectedEntry:(id)arg1;
- (void)showLoginPhotos;
- (void)showMacControlTutorial;
- (void)showMacOSNotifications;
- (void)showMacSleepScreenOverlay;
- (void)showMacSleepScreenTutorial;
- (void)showMainMenu;
- (void)showMainScreenWithRowId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showMainWindow;
- (void)showManualPhotos;
- (void)showManualPhotosInfo;
- (void)showManualSnapshotsWindowWithEntry:(id)arg1;
- (void)showOpenSpaceInfo;
- (void)showProximityLockDisabledBecauseWifi;
- (void)showProximityLockDisabledManualLogin;
- (void)showProximityLockTutorial;
- (void)showRateOnAppStore;
- (void)showSystemPreferenceOptionForSource:(int)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)showTemporaryDisabledInformationWindow;
- (void)showTroubleConnectingToDeviceTutorial;
- (void)showTroubleShootInitialConnection;
- (void)showUnlockHistory;
- (void)showUpdateNearLockOnYourPhone;
- (void)showUpdateToPro;
- (void)showUpdates;
- (void)showWifiUnlock;
- (void)showWifiUnlockOptionForSource:(int)arg1;
- (void)showWizzardOpenWindow:(BOOL)arg1;
- (void)showWizzardWithCompletion:(CDUnknownBlockType)arg1;
- (void)sleepToggled;
- (void)startFailSafeTimerWithDelay:(long long)arg1;
- (void)startFailsafeTimeAfterDelayIfNeeded;
- (void)startScanningAndConnection;
- (void)startScanningIndicatorIfNeeded;
- (void)systemPreferancesDidChange:(id)arg1;
- (void)takeManualPhoto;
- (void)temporaryDisabledToggled;
- (void)testAfterStart;
- (void)toggleAllowLogin;
- (void)toggleAllowLogout;
- (void)toggleAllowSmallerDistances;
- (void)toggleClipboardShortcut;
- (void)toggleClipboardShownOnMainScreen;
- (void)toggleHelp;
- (void)toggleLockShortcut;
- (void)toggleLogoutOnDisconnect;
- (void)toggleOpenSpaceMode;
- (void)togglePauseMusicOnLogout;
- (void)togglePhotoAfterEachLogin;
- (void)toggleProximityLock;
- (void)toggleRescan;
- (void)toggleShowMacControlOnMainScreen;
- (void)toggleShowMainView;
- (void)toggleShowProximityLockOnMainScreen;
- (void)toggleStartNearLockOnLogin;
- (void)toggleTakePhotoOnFailedLogin;
- (void)toggleUpdateNearLockAutomatically;
- (void)toggleWarnUserOnFailedLogin;
- (void)toggleWifiUnlock;
- (void)toggleWifiUnlockOnMainScreen;
- (void)trackInfoUpdatedForDevice:(id)arg1;
- (void)trackingDeviceConnectedAndReady:(id)arg1;
- (void)tryToLoginInCaseNearLockTemporarilyDisabled;
- (void)unlinkDevices;
- (void)updateAccessibilityPreferancesWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateAndSyncData;
- (void)updateConnectionStatus:(id)arg1 forDevice:(id)arg2 andNotifyDevice:(BOOL)arg3;
- (void)updateDataModelBeforeStartingToScan;
- (void)updateDeviceLidIsDownAndNoExtMonitorInfoIfNeeded;
- (void)updateDockItem;
- (void)updateLanguageIfNeededForDevice:(id)arg1;
- (void)updateLastConnectionTimestamp;
- (void)updateLogoutAction:(int)arg1;
- (void)updateMacSleepScreenAuth:(int)arg1;
- (void)updateSafeWifi:(BOOL)arg1;
- (void)updateSecuritySettingsWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateSettingsSplitView;
- (void)updateSmallerDistancesIfNeeded;
- (void)updateStatuIcon;
- (void)updateTempDisableTrackingForDeviceRequest:(int)arg1;
- (void)updateTempDisableWhenLogin:(id)arg1;
- (void)updateTrackingDistance:(int)arg1;
- (void)updateTrackingDistance:(int)arg1 responsileDevice:(int)arg2;
- (void)updateViewForLanguageUpdate;
- (void)updateViewsForMobileTrackUpdate;
- (void)updateiOSVersion;
- (void)userDidClickAddNewDevice;
- (void)userDidLogin;
- (void)userDidLogout;
- (void)userDidSelectLockMac;
- (void)userDidSelectTurnBluetoothOn;
- (void)userDidToggleCheckForUpdates;
- (void)userDidTurnBluetoothOn;
- (void)warnUserAboutNewSoftwareUpdateIfNeccesary;
- (void)warnUserAboutScreensaverPreconditions;
- (void)windowControllerWillClose:(id)arg1;
- (void)wizzardViewController:(id)arg1 didAcceptConnection:(BOOL)arg2 forMobileDevice:(id)arg3;
- (void)wizzardViewController:(id)arg1 didSelectOption:(int)arg2;
- (void)wizzardViewController:(id)arg1 shouldScanForNewDevices:(BOOL)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

