//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSStatusItem, NSTimer, StatusItemView;

@interface StatusItemController : NSObject
{
    StatusItemView *_statusItemView;
    id <MenubarControllerDelegate> delegate;
    NSTimer *_animationTimer;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTimer *animationTimer; // @synthesize animationTimer=_animationTimer;
- (void)dealloc;
@property(nonatomic) __weak id <MenubarControllerDelegate> delegate; // @synthesize delegate;
@property(nonatomic) BOOL hasActiveIcon;
- (id)imageForStatusBarHighlighted:(BOOL)arg1;
- (id)initWithDelegate:(id)arg1;
- (BOOL)isConnected;
- (BOOL)isOnlineAndTracking;
- (void)removeIcon;
- (void)rightClickTogglePanel:(id)arg1;
- (void)setUpStatusItem;
@property(readonly, nonatomic) NSStatusItem *statusItem;
@property(readonly, nonatomic) StatusItemView *statusItemView; // @synthesize statusItemView=_statusItemView;
- (void)togglePanel:(id)arg1;
- (void)updateStatusItem;

@end

