//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class Device, MobileSettings, NSNumber;

@interface SyncObject : NSObject
{
    Device *_device;
    MobileSettings *_mobileSettings;
    NSNumber *_connectionStatus;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSNumber *connectionStatus; // @synthesize connectionStatus=_connectionStatus;
@property(retain, nonatomic) Device *device; // @synthesize device=_device;
@property(retain, nonatomic) MobileSettings *mobileSettings; // @synthesize mobileSettings=_mobileSettings;

@end

