//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SystemPreferences : NSObject
{
}

+ (BOOL)askForPasswordSet;
+ (BOOL)canReadBothAskForPasswordAndLockDelay;
+ (void)executeAppleScript:(id)arg1;
+ (void)forceUpdateCachedValues;
+ (void)initalizeIfNeeded;
+ (BOOL)isSetRequirePasswordToWakeAndIntervalZeroForSierra;
+ (BOOL)isSetRequirePasswordToWakeMojave;
+ (void)launchSecurityPreferences;
+ (BOOL)lockDelayIsImmediate;
+ (BOOL)preconditionsToLockMacOnScreensaverAreSet;
+ (BOOL)preconditionsToLockMacOnScreensaverAreSetForceUpdate;
+ (void)quitSystemPreferences;
+ (int)readAskForPassword;
+ (int)readIntArgumentFromScreensaverDefaultsWithKey:(id)arg1;
+ (int)readScreensaveDelay;
+ (void)updateAskForPasswordSet;
+ (void)updateLockDelayImmediate;

@end

