//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NLPageViewControllerExtended.h"

@class SimpleButtonBaseController, SystemPreferencesUpdateViewModel, UpdateSecuritySettingsViewController;

@interface SystemPreferencesViewController : NLPageViewControllerExtended
{
    CDUnknownBlockType _didUpdateSystemPreferences;
    SimpleButtonBaseController *_introViewController;
    UpdateSecuritySettingsViewController *_securityScreen;
    SimpleButtonBaseController *_doneScreen;
    SystemPreferencesUpdateViewModel *_viewModel;
}

- (void).cxx_destruct;
@property(copy) CDUnknownBlockType didUpdateSystemPreferences; // @synthesize didUpdateSystemPreferences=_didUpdateSystemPreferences;
@property(retain, nonatomic) SimpleButtonBaseController *doneScreen; // @synthesize doneScreen=_doneScreen;
- (long long)firstPageIndex;
- (id)initWithVM:(id)arg1;
- (void)initializePages;
@property(retain, nonatomic) SimpleButtonBaseController *introViewController; // @synthesize introViewController=_introViewController;
- (void)nearLockBroughtToFront;
- (BOOL)performCustomActionOnBackButtonToggled;
@property(retain, nonatomic) UpdateSecuritySettingsViewController *securityScreen; // @synthesize securityScreen=_securityScreen;
@property(retain, nonatomic) SystemPreferencesUpdateViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void)showFinishScreen;
- (void)start;
- (id)titleDescriptionText;
- (void)windowDidLoad;

@end

