//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TextFileManagement : NSObject
{
}

+ (id)appendEmptyStringToString:(id)arg1 toCharacterIndex:(long long)arg2;
+ (id)lastLineOfFile:(id)arg1;
+ (id)stringContentOfFileAtPath:(id)arg1;
+ (id)stringFromTimeInterval:(double)arg1;
+ (id)stringWithSpaces:(long long)arg1;

@end

