//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NearLockListViewCell.h"

#import "NearLockListViewCellProtocol.h"

@class NSString, NSTextField;

@interface TitleCell : NearLockListViewCell <NearLockListViewCellProtocol>
{
    NSTextField *_readMoreTextField;
}

+ (double)cellHeight;
+ (id)nibName;
- (void).cxx_destruct;
- (void)dealloc;
- (void)didToggleAction:(id)arg1;
- (void)prepareForReuse;
@property(retain, nonatomic) NSTextField *readMoreTextField; // @synthesize readMoreTextField=_readMoreTextField;
- (void)updateCellForCellViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

