//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "TitleCell.h"

@class NSTextField;

@interface TItleCellRoundedValue : TitleCell
{
    NSTextField *_valueTextField;
}

+ (double)cellHeight;
+ (id)nibName;
- (void).cxx_destruct;
@property(retain, nonatomic) NSTextField *valueTextField; // @synthesize valueTextField=_valueTextField;
- (void)updateCellForCellViewModel:(id)arg1;

@end

