//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TrackEventCellStyler : NSObject
{
}

+ (id)styleCell:(id)arg1 forFailedLoginEntry:(id)arg2;
+ (id)styleCell:(id)arg1 forLoginLogoutEntry:(id)arg2;
+ (id)styleCell:(id)arg1 forSessionEntry:(id)arg2;
+ (id)styleDumyCell:(id)arg1;

@end

