//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface TrackUser : NSObject
{
}

+ (void)trackErrorType:(id)arg1;
+ (void)trackEventType:(id)arg1 eventName:(id)arg2;

@end

