//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSString, NSTextField;

@interface TutorialSetUpNearLock : BaseViewController
{
    int _showViewReason;
    id <TutorialSetUpNearLockDelegate> _delegate;
    NSString *_iPhoneName;
    NSButton *_finishButton;
    NSButton *_openMainMenuButton;
    NSTextField *_topTitleLabel;
    NSTextField *_bottomTitleLabel;
    NSTextField *_nearLockTitleLabel;
    NSTextField *_nearLockSwitchLabel;
    NSTextField *_distanceLabel;
    NSTextField *_firstText;
    NSTextField *_secondText;
    NSTextField *_iPhoneNameTitle;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSTextField *bottomTitleLabel; // @synthesize bottomTitleLabel=_bottomTitleLabel;
@property(nonatomic) __weak id <TutorialSetUpNearLockDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSTextField *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(retain, nonatomic) NSButton *finishButton; // @synthesize finishButton=_finishButton;
@property(retain, nonatomic) NSTextField *firstText; // @synthesize firstText=_firstText;
@property(retain, nonatomic) NSString *iPhoneName; // @synthesize iPhoneName=_iPhoneName;
@property(retain, nonatomic) NSTextField *iPhoneNameTitle; // @synthesize iPhoneNameTitle=_iPhoneNameTitle;
@property(retain, nonatomic) NSTextField *nearLockSwitchLabel; // @synthesize nearLockSwitchLabel=_nearLockSwitchLabel;
@property(retain, nonatomic) NSTextField *nearLockTitleLabel; // @synthesize nearLockTitleLabel=_nearLockTitleLabel;
@property(retain, nonatomic) NSButton *openMainMenuButton; // @synthesize openMainMenuButton=_openMainMenuButton;
- (void)openMainMenuToggled:(id)arg1;
@property(retain, nonatomic) NSTextField *secondText; // @synthesize secondText=_secondText;
@property(nonatomic) int showViewReason; // @synthesize showViewReason=_showViewReason;
@property(retain, nonatomic) NSTextField *topTitleLabel; // @synthesize topTitleLabel=_topTitleLabel;
- (void)setUpView;
- (void)updateStrings;

@end

