//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class LOTAnimationView, NSTextField, NSView;

@interface TutorialFinished : BaseViewController
{
    NSTextField *_titleTextField;
    NSTextField *_shareTextField;
    NSView *_animationContainer;
    LOTAnimationView *_animation;
}

- (void).cxx_destruct;
@property(retain, nonatomic) LOTAnimationView *animation; // @synthesize animation=_animation;
@property(retain, nonatomic) NSView *animationContainer; // @synthesize animationContainer=_animationContainer;
- (void)executeCelebrateAnimation;
- (void)facebookShare:(id)arg1;
- (void)playCelebrateAnimation;
@property(retain, nonatomic) NSTextField *shareTextField; // @synthesize shareTextField=_shareTextField;
@property(retain, nonatomic) NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
- (void)twitterShare:(id)arg1;
- (void)updateStrings;
- (void)viewDidLoad;

@end

