//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ClearCacheController, ClipboardInfoViewController, HelpTutorialController, InitalWizzardController, InitialConnectionTroubleShoot, InitialTutorialController, MacSleepScreenViewController, SafeWifiWizzard, SystemPreferencesViewController;

@interface TutorialFactory : NSObject
{
    InitalWizzardController *_wizzardViewController;
    InitialTutorialController *_initialTutorialController;
    MacSleepScreenViewController *_macSleepScreenWIzzard;
    HelpTutorialController *_helpTutorialController;
    ClipboardInfoViewController *_clipboardInfoViewController;
    ClearCacheController *_clearCacheController;
    SystemPreferencesViewController *_systemPreferenceViewController;
    SystemPreferencesViewController *_accessibilityPreferenceViewController;
    InitialConnectionTroubleShoot *_initialSetupTroubleshoot;
    SafeWifiWizzard *_safeWifiWizzard;
}

- (void).cxx_destruct;
@property(retain, nonatomic) SystemPreferencesViewController *accessibilityPreferenceViewController; // @synthesize accessibilityPreferenceViewController=_accessibilityPreferenceViewController;
- (id)accessilityPreferenceTutorialwithCompletion:(CDUnknownBlockType)arg1;
@property(retain, nonatomic) ClearCacheController *clearCacheController; // @synthesize clearCacheController=_clearCacheController;
- (id)clearCacheTutorial:(id)arg1;
@property(retain, nonatomic) ClipboardInfoViewController *clipboardInfoViewController; // @synthesize clipboardInfoViewController=_clipboardInfoViewController;
- (id)clipboardTutorial:(id)arg1;
- (void)didSyncWithMobileDevice:(id)arg1;
- (void)didUnlockMacWithUserConfirmation;
- (void)didUpdateBluetoothState;
- (id)helpTutorial:(id)arg1;
@property(retain, nonatomic) HelpTutorialController *helpTutorialController; // @synthesize helpTutorialController=_helpTutorialController;
- (id)initialConnectionTroubleShoot:(id)arg1;
@property(retain, nonatomic) InitialConnectionTroubleShoot *initialSetupTroubleshoot; // @synthesize initialSetupTroubleshoot=_initialSetupTroubleshoot;
- (id)initialTutorial:(id)arg1;
@property(retain, nonatomic) InitialTutorialController *initialTutorialController; // @synthesize initialTutorialController=_initialTutorialController;
- (void)lostConnectionToMobileDevice:(id)arg1;
- (id)macSleepScreenTutorial:(id)arg1;
@property(retain, nonatomic) MacSleepScreenViewController *macSleepScreenWIzzard; // @synthesize macSleepScreenWIzzard=_macSleepScreenWIzzard;
- (id)proximityUnlockTutorial:(id)arg1;
@property(retain, nonatomic) SafeWifiWizzard *safeWifiWizzard; // @synthesize safeWifiWizzard=_safeWifiWizzard;
@property(retain, nonatomic) SystemPreferencesViewController *systemPreferenceViewController; // @synthesize systemPreferenceViewController=_systemPreferenceViewController;
@property(retain, nonatomic) InitalWizzardController *wizzardViewController; // @synthesize wizzardViewController=_wizzardViewController;
- (id)systemPreferenceTutorialwithCompletion:(CDUnknownBlockType)arg1;
- (void)updateClipboardInfoControllerIfNeeded;
- (void)updateMacSleepScreenTutorialIfNeeded;
- (void)updatePairingWizzard;
- (id)wifiWizzard:(id)arg1;
- (void)windowControllerWillClose:(id)arg1;

@end

