//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseViewController.h"

@class NSButton, NSImageView, NSTextField, SystemPreferencesUpdateViewModel;

@interface UpdateSecuritySettingsViewController : BaseViewController
{
    BOOL _didLaunchManually;
    SystemPreferencesUpdateViewModel *_viewModel;
    CDUnknownBlockType _didFinishAction;
    NSTextField *_topLabel;
    NSButton *_topButton;
    NSImageView *_imageView;
    NSTextField *_label2;
    NSTextField *_label3;
    NSButton *_bottomButton;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSButton *bottomButton; // @synthesize bottomButton=_bottomButton;
@property(copy) CDUnknownBlockType didFinishAction; // @synthesize didFinishAction=_didFinishAction;
@property(nonatomic) BOOL didLaunchManually; // @synthesize didLaunchManually=_didLaunchManually;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSTextField *label2; // @synthesize label2=_label2;
@property(retain, nonatomic) NSTextField *label3; // @synthesize label3=_label3;
- (void)nearLockBroughtToFront;
- (void)openSettingsToggled:(id)arg1;
@property(retain, nonatomic) NSButton *topButton; // @synthesize topButton=_topButton;
@property(retain, nonatomic) NSTextField *topLabel; // @synthesize topLabel=_topLabel;
@property(retain, nonatomic) SystemPreferencesUpdateViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void)updateLabelColors;
- (void)updateStrings;
- (void)verifySettigns;
- (void)verifySettingsToggled:(id)arg1;
- (void)viewDidAppear;
- (void)viewDidLoad;

@end

