//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EventTimestamp;

@interface UpdateNotificationHelper : NSObject
{
    EventTimestamp *_iosUpdateWarningTimestamp;
    EventTimestamp *_macOsWarningTimestamp;
}

- (void).cxx_destruct;
- (void)didWarnUserAboutOSXUpdate;
- (void)didWarnUserAboutiOSUpdate;
- (id)init;
@property(retain, nonatomic) EventTimestamp *iosUpdateWarningTimestamp; // @synthesize iosUpdateWarningTimestamp=_iosUpdateWarningTimestamp;
@property(retain, nonatomic) EventTimestamp *macOsWarningTimestamp; // @synthesize macOsWarningTimestamp=_macOsWarningTimestamp;
- (BOOL)shouldWarnUserAboutNewIosUpdate;
- (BOOL)shouldWarnUserAboutNewNearLockVersionForMacOSX;

@end

