//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "BaseMenuItemManager.h"

@interface UpdatesMenuManager : BaseMenuItemManager
{
}

- (id)actionTextForiOSAppUpdateState:(int)arg1;
- (id)createViewModel;
- (int)currentMacUpdateState;
- (int)currentiOSUpdateState;
- (void)didToggleActionForState:(int)arg1;
- (id)iPhoneUpdateSection;
- (id)iPhoneVersion;
- (id)macAutomaticallyUpdate;
- (id)macCheckForUpdates;
- (id)macUpdateSection;
- (id)stringForMacAppUpdateActionStateForState:(int)arg1;
- (id)stringForMacAppUpdateStateForState:(int)arg1;
- (id)stringForiOSAppUpdateState:(int)arg1;
- (void)updateMacVersionToggledForState:(int)arg1;
- (id)viewModelForMacUpdateState:(int)arg1;

@end

