//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Utilities : NSObject
{
}

+ (id)applicationDataNearLockDirectory;
+ (id)applicationDataNearLockDirectoryFilePath;
+ (id)applicationDataNearLockFailedLoginImagesDirectory;
+ (id)applicationDataNearLockLoginImagesDirectory;
+ (id)applicationDataNearLockManualSnapshotsImagesDirectory;
+ (id)applicationDirectory;
+ (id)applicationFilesDirectory;
+ (id)applicationLibraryDirectory;
+ (id)applicationNearLockLibraryDirectory;
+ (id)applicationSupportDirectory;
+ (BOOL)createDirectoryIfItDoesntExist:(id)arg1;
+ (id)createDirectoryOrReturnDocuments:(id)arg1;
+ (id)currentVersionString;
+ (id)desktopDirectory;
+ (id)documentsDirectory;
+ (id)machineModel;
+ (id)nearLockDocumentsDirectory;
+ (void)openAndSelectFileAtPathInFinder:(id)arg1;
+ (void)openNearLockDocumentDirectory;
+ (id)operatingSystemVersion;
+ (id)pathForFileInDocumentsDirectory:(id)arg1;
+ (long long)randomNumberBetweenLower:(long long)arg1 andUpper:(long long)arg2;
+ (BOOL)removeFileAtPath:(id)arg1;
+ (id)systemVersionNumeric;
+ (id)systemVersionOSX;

@end

