//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface VersionFeatureChecker : NSObject
{
}

+ (id)earliestIosVersionForFeature:(int)arg1;
+ (BOOL)feature:(int)arg1 supportedOnDevice:(id)arg2;

@end

