//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MovableWindow.h"

#import "NSSplitViewDelegate.h"

@class NSColor, NSSplitView, NSString, NSView, NSVisualEffectView;

@interface WAYSourceListWindow : MovableWindow <NSSplitViewDelegate>
{
    BOOL _darkMasterViewMaterial;
    NSSplitView *_splitView;
    NSView *_masterView;
    NSView *_detailView;
    NSColor *_detailViewBackgroundColor;
    double _minimumMasterViewWidth;
    double _maximumMasterViewWidth;
    double _initialMasterViewWidth;
    NSView *_customContentView;
    NSVisualEffectView *_masterViewWrapper;
    NSView *_detailViewWrapper;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property(retain) NSView *customContentView; // @synthesize customContentView=_customContentView;
@property(nonatomic) BOOL darkMasterViewMaterial; // @synthesize darkMasterViewMaterial=_darkMasterViewMaterial;
@property(retain, nonatomic) NSView *detailView; // @synthesize detailView=_detailView;
@property(copy, nonatomic) NSColor *detailViewBackgroundColor; // @synthesize detailViewBackgroundColor=_detailViewBackgroundColor;
@property(retain) NSView *detailViewWrapper; // @synthesize detailViewWrapper=_detailViewWrapper;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4;
- (id)initWithContentRect:(struct CGRect)arg1 styleMask:(unsigned long long)arg2 backing:(unsigned long long)arg3 defer:(BOOL)arg4 screen:(id)arg5;
@property(nonatomic) double initialMasterViewWidth; // @synthesize initialMasterViewWidth=_initialMasterViewWidth;
@property(retain, nonatomic) NSView *masterView; // @synthesize masterView=_masterView;
@property(retain) NSVisualEffectView *masterViewWrapper; // @synthesize masterViewWrapper=_masterViewWrapper;
@property(nonatomic) double maximumMasterViewWidth; // @synthesize maximumMasterViewWidth=_maximumMasterViewWidth;
@property(nonatomic) double minimumMasterViewWidth; // @synthesize minimumMasterViewWidth=_minimumMasterViewWidth;
- (void)restoreStateWithCoder:(id)arg1;
- (void)setContentView:(id)arg1;
- (void)setMasterViewWidth:(double)arg1;
- (void)setNeedsLayout;
@property(retain) NSSplitView *splitView; // @synthesize splitView=_splitView;
- (void)setUp;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 shouldAdjustSizeOfSubview:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

