//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MovableSplitView.h"

@class NSColor;

@interface WAYSourceListSplitView : MovableSplitView
{
    NSColor *_customDividerColor;
}

- (void).cxx_destruct;
@property(retain) NSColor *customDividerColor; // @synthesize customDividerColor=_customDividerColor;
- (id)dividerColor;

@end

