//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class ITSwitch, NSButton, NSImageView, NSTextField;

@interface WifiUnlockView : NSView
{
    ITSwitch *_wifiUnlockSwitch;
    NSTextField *_wifiUnlockLabel;
    NSImageView *_wifiUnlockIcon;
    NSImageView *_wifiUnlockSeparator;
    NSButton *_checkBox;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSButton *checkBox; // @synthesize checkBox=_checkBox;
@property(retain, nonatomic) NSImageView *wifiUnlockIcon; // @synthesize wifiUnlockIcon=_wifiUnlockIcon;
@property(retain, nonatomic) NSTextField *wifiUnlockLabel; // @synthesize wifiUnlockLabel=_wifiUnlockLabel;
@property(retain, nonatomic) NSImageView *wifiUnlockSeparator; // @synthesize wifiUnlockSeparator=_wifiUnlockSeparator;
@property(retain, nonatomic) ITSwitch *wifiUnlockSwitch; // @synthesize wifiUnlockSwitch=_wifiUnlockSwitch;

@end

