//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CWEventDelegate.h"

@class CWInterface, CWWiFiClient;

@interface WifiHelper : NSObject <CWEventDelegate>
{
    id <WifiHelperDelegate> _delegate;
    CWWiFiClient *_wifiClient;
    CWInterface *_wifiInterface;
}

- (void).cxx_destruct;
- (id)connectedWifi;
- (id)connectedWifiBSSID;
- (id)connectedWifiHardwareAddress;
- (id)connectedWifiName;
- (void)dealloc;
@property(nonatomic) __weak id <WifiHelperDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (BOOL)isConnectedToWifi;
- (void)registerForDeprecatedCallbacks;
- (void)registerForNewAvailableCallbacks;
- (void)registerForWifiChanges;
@property(retain, nonatomic) CWWiFiClient *wifiClient; // @synthesize wifiClient=_wifiClient;
@property(retain, nonatomic) CWInterface *wifiInterface; // @synthesize wifiInterface=_wifiInterface;
- (void)ssidDidChangeForWiFiInterfaceWithName:(id)arg1;
- (void)wifiDidChange;

@end

