//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class InitalWizzardController, MobileDevice;

@protocol WizzardViewControllerDelegate <NSObject>
- (void)wizzardViewController:(InitalWizzardController *)arg1 didAcceptConnection:(BOOL)arg2 forMobileDevice:(MobileDevice *)arg3;
- (void)wizzardViewController:(InitalWizzardController *)arg1 didSelectOption:(int)arg2;
- (void)wizzardViewController:(InitalWizzardController *)arg1 shouldScanForNewDevices:(BOOL)arg2;
@end

